// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sql

import (
	"database/sql"
)

type CacheEntry struct {
	ID                 int64
	Provider           string
	Namespace          string
	RequestFingerprint string
	ResponseStatus     int64
	PayloadArtifactID  sql.NullInt64
	FetchedAt          string
	ExpiresAt          sql.NullString
	ExtractorVersion   string
	CreatedAt          string
	UpdatedAt          string
}
