// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: probe.sql

package sql

import (
	"context"
	"database/sql"
)

const insertProbeEntry = `-- name: InsertProbeEntry :execresult
INSERT INTO cache_entries (
    provider,
    namespace,
    request_fingerprint,
    response_status,
    payload_artifact_id,
    fetched_at,
    expires_at,
    extractor_version
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8
)
`

type InsertProbeEntryParams struct {
	Provider           string
	Namespace          string
	RequestFingerprint string
	ResponseStatus     int64
	PayloadArtifactID  sql.NullInt64
	FetchedAt          string
	ExpiresAt          sql.NullString
	ExtractorVersion   string
}

func (q *Queries) InsertProbeEntry(ctx context.Context, arg InsertProbeEntryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertProbeEntry,
		arg.Provider,
		arg.Namespace,
		arg.RequestFingerprint,
		arg.ResponseStatus,
		arg.PayloadArtifactID,
		arg.FetchedAt,
		arg.ExpiresAt,
		arg.ExtractorVersion,
	)
}

const latestProbeEntry = `-- name: LatestProbeEntry :one
SELECT
    id,
    provider,
    namespace,
    request_fingerprint,
    response_status,
    payload_artifact_id,
    fetched_at,
    expires_at,
    extractor_version,
    created_at,
    updated_at
FROM cache_entries
WHERE provider = ?1
  AND namespace = ?2
ORDER BY id DESC
LIMIT 1
`

type LatestProbeEntryParams struct {
	Provider  string
	Namespace string
}

func (q *Queries) LatestProbeEntry(ctx context.Context, arg LatestProbeEntryParams) (CacheEntry, error) {
	row := q.db.QueryRowContext(ctx, latestProbeEntry, arg.Provider, arg.Namespace)
	var i CacheEntry
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Namespace,
		&i.RequestFingerprint,
		&i.ResponseStatus,
		&i.PayloadArtifactID,
		&i.FetchedAt,
		&i.ExpiresAt,
		&i.ExtractorVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProbeEntries = `-- name: ListProbeEntries :many
SELECT
    id,
    provider,
    namespace,
    request_fingerprint,
    response_status,
    payload_artifact_id,
    fetched_at,
    expires_at,
    extractor_version,
    created_at,
    updated_at
FROM cache_entries
WHERE provider = ?1
ORDER BY id
`

func (q *Queries) ListProbeEntries(ctx context.Context, provider string) ([]CacheEntry, error) {
	rows, err := q.db.QueryContext(ctx, listProbeEntries, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CacheEntry
	for rows.Next() {
		var i CacheEntry
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Namespace,
			&i.RequestFingerprint,
			&i.ResponseStatus,
			&i.PayloadArtifactID,
			&i.FetchedAt,
			&i.ExpiresAt,
			&i.ExtractorVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
