// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: binding.sql

package sql

import (
	"context"
)

const getPDFStoreBinding = `-- name: GetPDFStoreBinding :one

SELECT relative_path
FROM pdf_store_binding
WHERE id = 1
`

// Metadata-side companion PDF binding queries. The binding is a singleton row
// that records the portable bundle-relative companion path.
func (q *Queries) GetPDFStoreBinding(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getPDFStoreBinding)
	var relative_path string
	err := row.Scan(&relative_path)
	return relative_path, err
}

const insertPDFStoreBinding = `-- name: InsertPDFStoreBinding :exec
INSERT INTO pdf_store_binding (id, relative_path, configured_at, config_fingerprint)
VALUES (1, ?1, ?2, ?3)
`

type InsertPDFStoreBindingParams struct {
	RelativePath      string
	ConfiguredAt      string
	ConfigFingerprint string
}

func (q *Queries) InsertPDFStoreBinding(ctx context.Context, arg InsertPDFStoreBindingParams) error {
	_, err := q.db.ExecContext(ctx, insertPDFStoreBinding, arg.RelativePath, arg.ConfiguredAt, arg.ConfigFingerprint)
	return err
}
