// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delivery.sql

package sql

import (
	"context"
	"database/sql"
)

const getPDFAuditLink = `-- name: GetPDFAuditLink :one

SELECT audit_event_id
FROM pdf_audit_links
WHERE event_key = ?1
`

// Delivered-event link queries. The metadata audit row and its delivery link
// commit atomically in the caller's metadata transaction, and the link guards
// retries so a crash between the metadata and companion commits cannot
// duplicate an append-only audit row.
func (q *Queries) GetPDFAuditLink(ctx context.Context, eventKey string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPDFAuditLink, eventKey)
	var audit_event_id int64
	err := row.Scan(&audit_event_id)
	return audit_event_id, err
}

const insertPDFAuditLink = `-- name: InsertPDFAuditLink :exec
INSERT INTO pdf_audit_links (event_key, audit_event_id, created_at)
VALUES (?1, ?2, ?3)
`

type InsertPDFAuditLinkParams struct {
	EventKey     string
	AuditEventID int64
	CreatedAt    string
}

func (q *Queries) InsertPDFAuditLink(ctx context.Context, arg InsertPDFAuditLinkParams) error {
	_, err := q.db.ExecContext(ctx, insertPDFAuditLink, arg.EventKey, arg.AuditEventID, arg.CreatedAt)
	return err
}

const insertPDFMetadataAuditEvent = `-- name: InsertPDFMetadataAuditEvent :execresult
INSERT INTO audit_events (
    occurred_at, actor, pipeline_run_id, entity_type,
    entity_id, action, metadata_json, correlation_id
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7, ?8
)
`

type InsertPDFMetadataAuditEventParams struct {
	OccurredAt    string
	Actor         string
	PipelineRunID sql.NullInt64
	EntityType    string
	EntityID      string
	Action        string
	MetadataJson  sql.NullString
	CorrelationID sql.NullString
}

func (q *Queries) InsertPDFMetadataAuditEvent(ctx context.Context, arg InsertPDFMetadataAuditEventParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertPDFMetadataAuditEvent,
		arg.OccurredAt,
		arg.Actor,
		arg.PipelineRunID,
		arg.EntityType,
		arg.EntityID,
		arg.Action,
		arg.MetadataJson,
		arg.CorrelationID,
	)
}

const pipelineRunExists = `-- name: PipelineRunExists :one
SELECT 1
FROM pipeline_runs
WHERE id = ?1
`

func (q *Queries) PipelineRunExists(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, pipelineRunExists, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
