// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hierarchy.sql

package sql

import (
	"context"
)

const getHierarchyTotals = `-- name: GetHierarchyTotals :one

SELECT
    (SELECT COUNT(*) FROM searches) AS searches,
    (SELECT COUNT(*) FROM search_revisions) AS revisions,
    (SELECT COUNT(*) FROM execution_plans) AS plans,
    (SELECT COUNT(*) FROM pipeline_runs) AS runs,
    (SELECT COUNT(*) FROM pipeline_runs WHERE status='completed') AS completed_runs
`

type GetHierarchyTotalsRow struct {
	Searches      int64
	Revisions     int64
	Plans         int64
	Runs          int64
	CompletedRuns int64
}

// Viewer hierarchy totals for the Home discovery summary. Counts planned and
// completed attempts without transferring run lifecycle ownership.
func (q *Queries) GetHierarchyTotals(ctx context.Context) (GetHierarchyTotalsRow, error) {
	row := q.db.QueryRowContext(ctx, getHierarchyTotals)
	var i GetHierarchyTotalsRow
	err := row.Scan(
		&i.Searches,
		&i.Revisions,
		&i.Plans,
		&i.Runs,
		&i.CompletedRuns,
	)
	return i, err
}
