// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sql

import (
	"database/sql"
)

type ExecutionPlan struct {
	ID                   int64
	SearchRevisionID     int64
	ExecutionFingerprint string
	ResolvedManifestHash string
	InputManifestHash    string
	EnrichmentEnabled    int64
	CreatedAt            string
}

type Search struct {
	ID        int64
	SearchID  string
	CreatedAt string
}

type SearchRevision struct {
	ID                   int64
	SearchID             int64
	RevisionLabel        string
	ConfigArtifactHash   string
	ResolvedManifestHash string
	CreatedAt            string
	UpdatedAt            sql.NullString
}
