// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package sql

import (
	"context"
	"database/sql"
)

const getPlanByFingerprint = `-- name: GetPlanByFingerprint :one
SELECT
    id,
    search_revision_id,
    execution_fingerprint,
    resolved_manifest_hash,
    input_manifest_hash,
    enrichment_enabled,
    created_at
FROM execution_plans
WHERE search_revision_id = ?1
  AND execution_fingerprint = ?2
`

type GetPlanByFingerprintParams struct {
	SearchRevisionID     int64
	ExecutionFingerprint string
}

func (q *Queries) GetPlanByFingerprint(ctx context.Context, arg GetPlanByFingerprintParams) (ExecutionPlan, error) {
	row := q.db.QueryRowContext(ctx, getPlanByFingerprint, arg.SearchRevisionID, arg.ExecutionFingerprint)
	var i ExecutionPlan
	err := row.Scan(
		&i.ID,
		&i.SearchRevisionID,
		&i.ExecutionFingerprint,
		&i.ResolvedManifestHash,
		&i.InputManifestHash,
		&i.EnrichmentEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const getPlanByID = `-- name: GetPlanByID :one
SELECT
    id,
    search_revision_id,
    execution_fingerprint,
    resolved_manifest_hash,
    input_manifest_hash,
    enrichment_enabled,
    created_at
FROM execution_plans
WHERE id = ?1
`

func (q *Queries) GetPlanByID(ctx context.Context, id int64) (ExecutionPlan, error) {
	row := q.db.QueryRowContext(ctx, getPlanByID, id)
	var i ExecutionPlan
	err := row.Scan(
		&i.ID,
		&i.SearchRevisionID,
		&i.ExecutionFingerprint,
		&i.ResolvedManifestHash,
		&i.InputManifestHash,
		&i.EnrichmentEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const insertPlanIgnore = `-- name: InsertPlanIgnore :execresult
INSERT OR IGNORE INTO execution_plans (
    search_revision_id,
    execution_fingerprint,
    resolved_manifest_hash,
    input_manifest_hash,
    enrichment_enabled
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5
)
`

type InsertPlanIgnoreParams struct {
	SearchRevisionID     int64
	ExecutionFingerprint string
	ResolvedManifestHash string
	InputManifestHash    string
	EnrichmentEnabled    int64
}

func (q *Queries) InsertPlanIgnore(ctx context.Context, arg InsertPlanIgnoreParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertPlanIgnore,
		arg.SearchRevisionID,
		arg.ExecutionFingerprint,
		arg.ResolvedManifestHash,
		arg.InputManifestHash,
		arg.EnrichmentEnabled,
	)
}

const listLegacyPlans = `-- name: ListLegacyPlans :many
SELECT
    id,
    search_revision_id,
    execution_fingerprint,
    resolved_manifest_hash,
    input_manifest_hash,
    enrichment_enabled,
    created_at
FROM execution_plans
WHERE search_revision_id = ?1
ORDER BY id DESC
LIMIT ?2
`

type ListLegacyPlansParams struct {
	SearchRevisionID int64
	Limit            int64
}

func (q *Queries) ListLegacyPlans(ctx context.Context, arg ListLegacyPlansParams) ([]ExecutionPlan, error) {
	rows, err := q.db.QueryContext(ctx, listLegacyPlans, arg.SearchRevisionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExecutionPlan
	for rows.Next() {
		var i ExecutionPlan
		if err := rows.Scan(
			&i.ID,
			&i.SearchRevisionID,
			&i.ExecutionFingerprint,
			&i.ResolvedManifestHash,
			&i.InputManifestHash,
			&i.EnrichmentEnabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlansBySearchRevision = `-- name: ListPlansBySearchRevision :many
SELECT
    id,
    search_revision_id,
    execution_fingerprint,
    resolved_manifest_hash,
    input_manifest_hash,
    enrichment_enabled,
    created_at
FROM execution_plans
WHERE search_revision_id = ?1
ORDER BY id
`

func (q *Queries) ListPlansBySearchRevision(ctx context.Context, searchRevisionID int64) ([]ExecutionPlan, error) {
	rows, err := q.db.QueryContext(ctx, listPlansBySearchRevision, searchRevisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExecutionPlan
	for rows.Next() {
		var i ExecutionPlan
		if err := rows.Scan(
			&i.ID,
			&i.SearchRevisionID,
			&i.ExecutionFingerprint,
			&i.ResolvedManifestHash,
			&i.InputManifestHash,
			&i.EnrichmentEnabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
