// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: revisions.sql

package sql

import (
	"context"
	"database/sql"
)

const getRevisionByID = `-- name: GetRevisionByID :one
SELECT
    id,
    search_id,
    revision_label,
    config_artifact_hash,
    resolved_manifest_hash,
    created_at,
    updated_at
FROM search_revisions
WHERE id = ?1
`

func (q *Queries) GetRevisionByID(ctx context.Context, id int64) (SearchRevision, error) {
	row := q.db.QueryRowContext(ctx, getRevisionByID, id)
	var i SearchRevision
	err := row.Scan(
		&i.ID,
		&i.SearchID,
		&i.RevisionLabel,
		&i.ConfigArtifactHash,
		&i.ResolvedManifestHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRevisionBySearchAndLabel = `-- name: GetRevisionBySearchAndLabel :one
SELECT
    id,
    search_id,
    revision_label,
    config_artifact_hash,
    resolved_manifest_hash,
    created_at,
    updated_at
FROM search_revisions
WHERE search_id = ?1
  AND revision_label = ?2
`

type GetRevisionBySearchAndLabelParams struct {
	SearchID      int64
	RevisionLabel string
}

func (q *Queries) GetRevisionBySearchAndLabel(ctx context.Context, arg GetRevisionBySearchAndLabelParams) (SearchRevision, error) {
	row := q.db.QueryRowContext(ctx, getRevisionBySearchAndLabel, arg.SearchID, arg.RevisionLabel)
	var i SearchRevision
	err := row.Scan(
		&i.ID,
		&i.SearchID,
		&i.RevisionLabel,
		&i.ConfigArtifactHash,
		&i.ResolvedManifestHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRevisionIgnore = `-- name: InsertRevisionIgnore :execresult
INSERT OR IGNORE INTO search_revisions (
    search_id,
    revision_label,
    config_artifact_hash,
    resolved_manifest_hash
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4
)
`

type InsertRevisionIgnoreParams struct {
	SearchID             int64
	RevisionLabel        string
	ConfigArtifactHash   string
	ResolvedManifestHash string
}

func (q *Queries) InsertRevisionIgnore(ctx context.Context, arg InsertRevisionIgnoreParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertRevisionIgnore,
		arg.SearchID,
		arg.RevisionLabel,
		arg.ConfigArtifactHash,
		arg.ResolvedManifestHash,
	)
}

const listRevisionsBySearch = `-- name: ListRevisionsBySearch :many
SELECT
    id,
    search_id,
    revision_label,
    config_artifact_hash,
    resolved_manifest_hash,
    created_at,
    updated_at
FROM search_revisions
WHERE search_id = ?1
ORDER BY id
`

func (q *Queries) ListRevisionsBySearch(ctx context.Context, searchID int64) ([]SearchRevision, error) {
	rows, err := q.db.QueryContext(ctx, listRevisionsBySearch, searchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchRevision
	for rows.Next() {
		var i SearchRevision
		if err := rows.Scan(
			&i.ID,
			&i.SearchID,
			&i.RevisionLabel,
			&i.ConfigArtifactHash,
			&i.ResolvedManifestHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRevisionHashes = `-- name: UpdateRevisionHashes :exec
UPDATE search_revisions
SET
    config_artifact_hash = ?1,
    resolved_manifest_hash = ?2,
    updated_at = datetime('now')
WHERE id = ?3
`

type UpdateRevisionHashesParams struct {
	ConfigArtifactHash   string
	ResolvedManifestHash string
	ID                   int64
}

func (q *Queries) UpdateRevisionHashes(ctx context.Context, arg UpdateRevisionHashesParams) error {
	_, err := q.db.ExecContext(ctx, updateRevisionHashes, arg.ConfigArtifactHash, arg.ResolvedManifestHash, arg.ID)
	return err
}
