// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package sql

import (
	"context"
	"database/sql"
)

const getSearchByID = `-- name: GetSearchByID :one
SELECT
    id,
    search_id,
    created_at
FROM searches
WHERE id = ?1
`

func (q *Queries) GetSearchByID(ctx context.Context, id int64) (Search, error) {
	row := q.db.QueryRowContext(ctx, getSearchByID, id)
	var i Search
	err := row.Scan(&i.ID, &i.SearchID, &i.CreatedAt)
	return i, err
}

const getSearchBySearchID = `-- name: GetSearchBySearchID :one
SELECT
    id,
    search_id,
    created_at
FROM searches
WHERE search_id = ?1
`

func (q *Queries) GetSearchBySearchID(ctx context.Context, searchID string) (Search, error) {
	row := q.db.QueryRowContext(ctx, getSearchBySearchID, searchID)
	var i Search
	err := row.Scan(&i.ID, &i.SearchID, &i.CreatedAt)
	return i, err
}

const getSearchIDBySearchID = `-- name: GetSearchIDBySearchID :one
SELECT id
FROM searches
WHERE search_id = ?1
`

func (q *Queries) GetSearchIDBySearchID(ctx context.Context, searchID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSearchIDBySearchID, searchID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertSearchIgnore = `-- name: InsertSearchIgnore :execresult
INSERT OR IGNORE INTO searches (search_id)
VALUES (?1)
`

func (q *Queries) InsertSearchIgnore(ctx context.Context, searchID string) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertSearchIgnore, searchID)
}

const listSearches = `-- name: ListSearches :many
SELECT
    id,
    search_id,
    created_at
FROM searches
ORDER BY id
`

func (q *Queries) ListSearches(ctx context.Context) ([]Search, error) {
	rows, err := q.db.QueryContext(ctx, listSearches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Search
	for rows.Next() {
		var i Search
		if err := rows.Scan(&i.ID, &i.SearchID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
