// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package sql

import (
	"context"
	"database/sql"
)

const getSearchByID = `-- name: GetSearchByID :one
SELECT
    id,
    search_id,
    created_at
FROM searches
WHERE id = ?1
`

func (q *Queries) GetSearchByID(ctx context.Context, id int64) (Search, error) {
	row := q.db.QueryRowContext(ctx, getSearchByID, id)
	var i Search
	err := row.Scan(&i.ID, &i.SearchID, &i.CreatedAt)
	return i, err
}

const getSearchBySearchID = `-- name: GetSearchBySearchID :one
SELECT
    id,
    search_id,
    created_at
FROM searches
WHERE search_id = ?1
`

func (q *Queries) GetSearchBySearchID(ctx context.Context, searchID string) (Search, error) {
	row := q.db.QueryRowContext(ctx, getSearchBySearchID, searchID)
	var i Search
	err := row.Scan(&i.ID, &i.SearchID, &i.CreatedAt)
	return i, err
}

const getSearchIDBySearchID = `-- name: GetSearchIDBySearchID :one
SELECT id
FROM searches
WHERE search_id = ?1
`

func (q *Queries) GetSearchIDBySearchID(ctx context.Context, searchID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSearchIDBySearchID, searchID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertSearchIgnore = `-- name: InsertSearchIgnore :execresult
INSERT OR IGNORE INTO searches (search_id)
VALUES (?1)
`

func (q *Queries) InsertSearchIgnore(ctx context.Context, searchID string) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertSearchIgnore, searchID)
}

const listLegacySearches = `-- name: ListLegacySearches :many
WITH selected_searches AS (
    SELECT id, search_id, created_at
    FROM searches
    ORDER BY id DESC
    LIMIT ?2
)
SELECT
    s.id,
    s.search_id,
    s.created_at,
    sr.id AS revision_id,
    sr.revision_label,
    sr.config_artifact_hash,
    sr.resolved_manifest_hash,
    sr.created_at AS revision_created_at
FROM selected_searches s
LEFT JOIN search_revisions sr ON sr.search_id=s.id
    AND (SELECT COUNT(*) FROM search_revisions newer
        WHERE newer.search_id=s.id AND newer.id>sr.id) < ?1
ORDER BY s.id DESC, sr.id DESC
`

type ListLegacySearchesParams struct {
	RevisionLimit int64
	Limit         int64
}

type ListLegacySearchesRow struct {
	ID                   int64
	SearchID             string
	CreatedAt            string
	RevisionID           sql.NullInt64
	RevisionLabel        sql.NullString
	ConfigArtifactHash   sql.NullString
	ResolvedManifestHash sql.NullString
	RevisionCreatedAt    sql.NullString
}

func (q *Queries) ListLegacySearches(ctx context.Context, arg ListLegacySearchesParams) ([]ListLegacySearchesRow, error) {
	rows, err := q.db.QueryContext(ctx, listLegacySearches, arg.RevisionLimit, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLegacySearchesRow
	for rows.Next() {
		var i ListLegacySearchesRow
		if err := rows.Scan(
			&i.ID,
			&i.SearchID,
			&i.CreatedAt,
			&i.RevisionID,
			&i.RevisionLabel,
			&i.ConfigArtifactHash,
			&i.ResolvedManifestHash,
			&i.RevisionCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSearches = `-- name: ListSearches :many
SELECT
    id,
    search_id,
    created_at
FROM searches
ORDER BY id
`

func (q *Queries) ListSearches(ctx context.Context) ([]Search, error) {
	rows, err := q.db.QueryContext(ctx, listSearches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Search
	for rows.Next() {
		var i Search
		if err := rows.Scan(&i.ID, &i.SearchID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
