// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artifact.sql

package sql

import (
	"context"
	"database/sql"
)

const getArtifactByHash = `-- name: GetArtifactByHash :one
SELECT
    id,
    content_hash,
    byte_size,
    content_type,
    created_at
FROM artifacts
WHERE content_hash = ?1
`

func (q *Queries) GetArtifactByHash(ctx context.Context, contentHash string) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, getArtifactByHash, contentHash)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.ContentHash,
		&i.ByteSize,
		&i.ContentType,
		&i.CreatedAt,
	)
	return i, err
}

const getArtifactByID = `-- name: GetArtifactByID :one
SELECT
    id,
    content_hash,
    byte_size,
    content_type,
    created_at
FROM artifacts
WHERE id = ?1
`

func (q *Queries) GetArtifactByID(ctx context.Context, id int64) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, getArtifactByID, id)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.ContentHash,
		&i.ByteSize,
		&i.ContentType,
		&i.CreatedAt,
	)
	return i, err
}

const getArtifactMetadataByHash = `-- name: GetArtifactMetadataByHash :one
SELECT
    id,
    byte_size,
    content_type
FROM artifacts
WHERE content_hash = ?1
`

type GetArtifactMetadataByHashRow struct {
	ID          int64
	ByteSize    int64
	ContentType string
}

func (q *Queries) GetArtifactMetadataByHash(ctx context.Context, contentHash string) (GetArtifactMetadataByHashRow, error) {
	row := q.db.QueryRowContext(ctx, getArtifactMetadataByHash, contentHash)
	var i GetArtifactMetadataByHashRow
	err := row.Scan(&i.ID, &i.ByteSize, &i.ContentType)
	return i, err
}

const getArtifactMetadataByID = `-- name: GetArtifactMetadataByID :one
SELECT
    byte_size,
    content_type
FROM artifacts
WHERE id = ?1
`

type GetArtifactMetadataByIDRow struct {
	ByteSize    int64
	ContentType string
}

func (q *Queries) GetArtifactMetadataByID(ctx context.Context, id int64) (GetArtifactMetadataByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getArtifactMetadataByID, id)
	var i GetArtifactMetadataByIDRow
	err := row.Scan(&i.ByteSize, &i.ContentType)
	return i, err
}

const insertArtifact = `-- name: InsertArtifact :execresult
INSERT OR IGNORE INTO artifacts (content_hash, byte_size, content_type)
VALUES (
    ?1,
    ?2,
    ?3
)
`

type InsertArtifactParams struct {
	ContentHash string
	ByteSize    int64
	ContentType string
}

func (q *Queries) InsertArtifact(ctx context.Context, arg InsertArtifactParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertArtifact, arg.ContentHash, arg.ByteSize, arg.ContentType)
}
