// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blob.sql

package sql

import (
	"context"
	"database/sql"
)

const getArtifactBlobByArtifactID = `-- name: GetArtifactBlobByArtifactID :one
SELECT
    id,
    artifact_id,
    pipeline_run_id,
    data,
    created_at
FROM artifact_blobs
WHERE artifact_id = ?1
`

func (q *Queries) GetArtifactBlobByArtifactID(ctx context.Context, artifactID int64) (ArtifactBlob, error) {
	row := q.db.QueryRowContext(ctx, getArtifactBlobByArtifactID, artifactID)
	var i ArtifactBlob
	err := row.Scan(
		&i.ID,
		&i.ArtifactID,
		&i.PipelineRunID,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const getArtifactBlobDataByArtifactID = `-- name: GetArtifactBlobDataByArtifactID :one
SELECT data
FROM artifact_blobs
WHERE artifact_id = ?1
`

func (q *Queries) GetArtifactBlobDataByArtifactID(ctx context.Context, artifactID int64) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getArtifactBlobDataByArtifactID, artifactID)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const insertArtifactBlob = `-- name: InsertArtifactBlob :execresult
INSERT OR IGNORE INTO artifact_blobs (artifact_id, pipeline_run_id, data)
VALUES (
    ?1,
    ?2,
    ?3
)
`

type InsertArtifactBlobParams struct {
	ArtifactID    int64
	PipelineRunID int64
	Data          []byte
}

func (q *Queries) InsertArtifactBlob(ctx context.Context, arg InsertArtifactBlobParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertArtifactBlob, arg.ArtifactID, arg.PipelineRunID, arg.Data)
}
