// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sql

type Artifact struct {
	ID          int64
	ContentHash string
	ByteSize    int64
	ContentType string
	CreatedAt   string
}

type ArtifactBlob struct {
	ID            int64
	ArtifactID    int64
	PipelineRunID int64
	Data          []byte
	CreatedAt     string
}
