// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: run_artifact.sql

package sql

import (
	"context"
	"database/sql"
)

const getRunArtifactByRunAndRole = `-- name: GetRunArtifactByRunAndRole :one
SELECT artifact_id
FROM run_artifacts
WHERE pipeline_run_id = ?1
  AND artifact_role = ?2
`

type GetRunArtifactByRunAndRoleParams struct {
	PipelineRunID int64
	ArtifactRole  string
}

func (q *Queries) GetRunArtifactByRunAndRole(ctx context.Context, arg GetRunArtifactByRunAndRoleParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getRunArtifactByRunAndRole, arg.PipelineRunID, arg.ArtifactRole)
	var artifact_id int64
	err := row.Scan(&artifact_id)
	return artifact_id, err
}

const insertRunArtifact = `-- name: InsertRunArtifact :execresult
INSERT OR IGNORE INTO run_artifacts (pipeline_run_id, artifact_id, artifact_role)
VALUES (
    ?1,
    ?2,
    ?3
)
`

type InsertRunArtifactParams struct {
	PipelineRunID int64
	ArtifactID    int64
	ArtifactRole  string
}

func (q *Queries) InsertRunArtifact(ctx context.Context, arg InsertRunArtifactParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertRunArtifact, arg.PipelineRunID, arg.ArtifactID, arg.ArtifactRole)
}
