// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sql

import (
	"context"
	"database/sql"
)

const insertRunRecoveryAudit = `-- name: InsertRunRecoveryAudit :exec
INSERT INTO audit_events (
    occurred_at,
    actor,
    pipeline_run_id,
    entity_type,
    entity_id,
    action,
    metadata_json,
    correlation_id
) VALUES (
    ?1,
    'operator',
    ?2,
    'pipeline_run',
    ?3,
    ?4,
    '{"reason":"abandoned_attempt_recovery"}',
    ?5
)
`

type InsertRunRecoveryAuditParams struct {
	OccurredAt    string
	PipelineRunID sql.NullInt64
	EntityID      string
	Action        string
	CorrelationID sql.NullString
}

func (q *Queries) InsertRunRecoveryAudit(ctx context.Context, arg InsertRunRecoveryAuditParams) error {
	_, err := q.db.ExecContext(ctx, insertRunRecoveryAudit,
		arg.OccurredAt,
		arg.PipelineRunID,
		arg.EntityID,
		arg.Action,
		arg.CorrelationID,
	)
	return err
}
