// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lifecycle.sql

package sql

import (
	"context"
	"database/sql"
)

const failRunningSteps = `-- name: FailRunningSteps :exec
UPDATE run_steps
SET
    step_status = 'failed',
    finished_at = ?1
WHERE pipeline_run_id = ?2
  AND step_status IN ('pending', 'running')
`

type FailRunningStepsParams struct {
	FinishedAt    sql.NullString
	PipelineRunID int64
}

func (q *Queries) FailRunningSteps(ctx context.Context, arg FailRunningStepsParams) error {
	_, err := q.db.ExecContext(ctx, failRunningSteps, arg.FinishedAt, arg.PipelineRunID)
	return err
}

const findRunningAttemptByPlan = `-- name: FindRunningAttemptByPlan :one
SELECT id
FROM pipeline_runs
WHERE execution_plan_id = ?1
  AND status = 'running'
ORDER BY attempt_number DESC
LIMIT 1
`

func (q *Queries) FindRunningAttemptByPlan(ctx context.Context, executionPlanID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, findRunningAttemptByPlan, executionPlanID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const finishRun = `-- name: FinishRun :exec
UPDATE pipeline_runs
SET
    finished_at = ?1,
    status = ?2,
    summary = ?3
WHERE id = ?4
`

type FinishRunParams struct {
	FinishedAt sql.NullString
	Status     string
	Summary    sql.NullString
	ID         int64
}

func (q *Queries) FinishRun(ctx context.Context, arg FinishRunParams) error {
	_, err := q.db.ExecContext(ctx, finishRun,
		arg.FinishedAt,
		arg.Status,
		arg.Summary,
		arg.ID,
	)
	return err
}

const getRunVisibility = `-- name: GetRunVisibility :one
SELECT
    status,
    visibility_state
FROM pipeline_runs
WHERE id = ?1
`

type GetRunVisibilityRow struct {
	Status          string
	VisibilityState string
}

func (q *Queries) GetRunVisibility(ctx context.Context, id int64) (GetRunVisibilityRow, error) {
	row := q.db.QueryRowContext(ctx, getRunVisibility, id)
	var i GetRunVisibilityRow
	err := row.Scan(&i.Status, &i.VisibilityState)
	return i, err
}

const insertAttempt = `-- name: InsertAttempt :execresult
INSERT INTO pipeline_runs (
    step,
    started_at,
    status,
    search_query,
    execution_plan_id,
    attempt_number
) VALUES (
    ?1,
    ?2,
    'running',
    ?3,
    ?4,
    ?5
)
`

type InsertAttemptParams struct {
	Step            string
	StartedAt       string
	SearchQuery     sql.NullString
	ExecutionPlanID sql.NullInt64
	AttemptNumber   sql.NullInt64
}

func (q *Queries) InsertAttempt(ctx context.Context, arg InsertAttemptParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertAttempt,
		arg.Step,
		arg.StartedAt,
		arg.SearchQuery,
		arg.ExecutionPlanID,
		arg.AttemptNumber,
	)
}

const nextAttemptNumber = `-- name: NextAttemptNumber :one
SELECT CAST(COALESCE(MAX(attempt_number), 0) AS INTEGER) AS max_attempt_number
FROM pipeline_runs
WHERE execution_plan_id = ?1
`

func (q *Queries) NextAttemptNumber(ctx context.Context, executionPlanID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextAttemptNumber, executionPlanID)
	var max_attempt_number int64
	err := row.Scan(&max_attempt_number)
	return max_attempt_number, err
}

const recoverRun = `-- name: RecoverRun :execresult
UPDATE pipeline_runs
SET
    status = 'failed',
    finished_at = ?1,
    summary = 'abandoned attempt recovered by operator'
WHERE id = ?2
  AND status = 'running'
`

type RecoverRunParams struct {
	FinishedAt sql.NullString
	ID         int64
}

func (q *Queries) RecoverRun(ctx context.Context, arg RecoverRunParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, recoverRun, arg.FinishedAt, arg.ID)
}

const restoreRun = `-- name: RestoreRun :exec
UPDATE pipeline_runs
SET
    visibility_state = 'active',
    trashed_at = NULL,
    trash_reason = NULL
WHERE id = ?1
`

func (q *Queries) RestoreRun(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, restoreRun, id)
	return err
}

const trashRun = `-- name: TrashRun :exec
UPDATE pipeline_runs
SET
    visibility_state = 'trashed',
    trashed_at = ?1,
    trash_reason = ?2
WHERE id = ?3
`

type TrashRunParams struct {
	TrashedAt   sql.NullString
	TrashReason sql.NullString
	ID          int64
}

func (q *Queries) TrashRun(ctx context.Context, arg TrashRunParams) error {
	_, err := q.db.ExecContext(ctx, trashRun, arg.TrashedAt, arg.TrashReason, arg.ID)
	return err
}
