// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lifecycle.sql

package sql

import (
	"context"
	"database/sql"
)

const failRunningSteps = `-- name: FailRunningSteps :exec
UPDATE run_steps
SET
    step_status = 'failed',
    finished_at = ?1
WHERE pipeline_run_id = ?2
  AND step_status IN ('pending', 'running')
`

type FailRunningStepsParams struct {
	FinishedAt    sql.NullString
	PipelineRunID int64
}

func (q *Queries) FailRunningSteps(ctx context.Context, arg FailRunningStepsParams) error {
	_, err := q.db.ExecContext(ctx, failRunningSteps, arg.FinishedAt, arg.PipelineRunID)
	return err
}

const findRunningAttemptByPlan = `-- name: FindRunningAttemptByPlan :one
SELECT id
FROM pipeline_runs
WHERE execution_plan_id = ?1
  AND status = 'running'
ORDER BY attempt_number DESC
LIMIT 1
`

func (q *Queries) FindRunningAttemptByPlan(ctx context.Context, executionPlanID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, findRunningAttemptByPlan, executionPlanID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const finishRun = `-- name: FinishRun :exec
UPDATE pipeline_runs
SET
    finished_at = ?1,
    status = ?2,
    summary = ?3
WHERE id = ?4
`

type FinishRunParams struct {
	FinishedAt sql.NullString
	Status     string
	Summary    sql.NullString
	ID         int64
}

func (q *Queries) FinishRun(ctx context.Context, arg FinishRunParams) error {
	_, err := q.db.ExecContext(ctx, finishRun,
		arg.FinishedAt,
		arg.Status,
		arg.Summary,
		arg.ID,
	)
	return err
}

const getRunContext = `-- name: GetRunContext :one
SELECT
    s.id AS search_pk,
    s.search_id AS search_name,
    s.created_at AS search_created_at,
    sr.id AS revision_pk,
    sr.search_id AS revision_search_id,
    sr.revision_label,
    sr.config_artifact_hash,
    sr.resolved_manifest_hash,
    sr.created_at AS revision_created_at,
    ep.id AS plan_pk,
    ep.search_revision_id AS plan_search_revision_id,
    ep.execution_fingerprint,
    ep.resolved_manifest_hash AS plan_resolved_manifest_hash,
    ep.input_manifest_hash,
    ep.enrichment_enabled,
    ep.created_at AS plan_created_at,
    pr.id AS run_pk,
    pr.execution_plan_id AS run_execution_plan_id,
    pr.step,
    pr.started_at,
    pr.finished_at,
    pr.status,
    pr.summary,
    pr.attempt_number,
    pr.visibility_state,
    pr.trashed_at,
    pr.trash_reason,
    rc.id AS review_context_id
FROM pipeline_runs pr
JOIN execution_plans ep ON ep.id=pr.execution_plan_id
JOIN search_revisions sr ON sr.id=ep.search_revision_id
JOIN searches s ON s.id=sr.search_id
LEFT JOIN review_contexts rc ON rc.pipeline_run_id=pr.id
WHERE pr.id = ?1
`

type GetRunContextRow struct {
	SearchPk                 int64
	SearchName               string
	SearchCreatedAt          string
	RevisionPk               int64
	RevisionSearchID         int64
	RevisionLabel            string
	ConfigArtifactHash       string
	ResolvedManifestHash     string
	RevisionCreatedAt        string
	PlanPk                   int64
	PlanSearchRevisionID     int64
	ExecutionFingerprint     string
	PlanResolvedManifestHash string
	InputManifestHash        string
	EnrichmentEnabled        int64
	PlanCreatedAt            string
	RunPk                    int64
	RunExecutionPlanID       sql.NullInt64
	Step                     string
	StartedAt                string
	FinishedAt               sql.NullString
	Status                   string
	Summary                  sql.NullString
	AttemptNumber            sql.NullInt64
	VisibilityState          string
	TrashedAt                sql.NullString
	TrashReason              sql.NullString
	ReviewContextID          sql.NullInt64
}

func (q *Queries) GetRunContext(ctx context.Context, id int64) (GetRunContextRow, error) {
	row := q.db.QueryRowContext(ctx, getRunContext, id)
	var i GetRunContextRow
	err := row.Scan(
		&i.SearchPk,
		&i.SearchName,
		&i.SearchCreatedAt,
		&i.RevisionPk,
		&i.RevisionSearchID,
		&i.RevisionLabel,
		&i.ConfigArtifactHash,
		&i.ResolvedManifestHash,
		&i.RevisionCreatedAt,
		&i.PlanPk,
		&i.PlanSearchRevisionID,
		&i.ExecutionFingerprint,
		&i.PlanResolvedManifestHash,
		&i.InputManifestHash,
		&i.EnrichmentEnabled,
		&i.PlanCreatedAt,
		&i.RunPk,
		&i.RunExecutionPlanID,
		&i.Step,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.Summary,
		&i.AttemptNumber,
		&i.VisibilityState,
		&i.TrashedAt,
		&i.TrashReason,
		&i.ReviewContextID,
	)
	return i, err
}

const getRunVisibility = `-- name: GetRunVisibility :one
SELECT
    status,
    visibility_state
FROM pipeline_runs
WHERE id = ?1
`

type GetRunVisibilityRow struct {
	Status          string
	VisibilityState string
}

func (q *Queries) GetRunVisibility(ctx context.Context, id int64) (GetRunVisibilityRow, error) {
	row := q.db.QueryRowContext(ctx, getRunVisibility, id)
	var i GetRunVisibilityRow
	err := row.Scan(&i.Status, &i.VisibilityState)
	return i, err
}

const insertAttempt = `-- name: InsertAttempt :execresult
INSERT INTO pipeline_runs (
    step,
    started_at,
    status,
    search_query,
    execution_plan_id,
    attempt_number
) VALUES (
    ?1,
    ?2,
    'running',
    ?3,
    ?4,
    ?5
)
`

type InsertAttemptParams struct {
	Step            string
	StartedAt       string
	SearchQuery     sql.NullString
	ExecutionPlanID sql.NullInt64
	AttemptNumber   sql.NullInt64
}

func (q *Queries) InsertAttempt(ctx context.Context, arg InsertAttemptParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertAttempt,
		arg.Step,
		arg.StartedAt,
		arg.SearchQuery,
		arg.ExecutionPlanID,
		arg.AttemptNumber,
	)
}

const nextAttemptNumber = `-- name: NextAttemptNumber :one
SELECT CAST(COALESCE(MAX(attempt_number), 0) AS INTEGER) AS max_attempt_number
FROM pipeline_runs
WHERE execution_plan_id = ?1
`

func (q *Queries) NextAttemptNumber(ctx context.Context, executionPlanID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextAttemptNumber, executionPlanID)
	var max_attempt_number int64
	err := row.Scan(&max_attempt_number)
	return max_attempt_number, err
}

const recoverRun = `-- name: RecoverRun :execresult
UPDATE pipeline_runs
SET
    status = 'failed',
    finished_at = ?1,
    summary = 'abandoned attempt recovered by operator'
WHERE id = ?2
  AND status = 'running'
`

type RecoverRunParams struct {
	FinishedAt sql.NullString
	ID         int64
}

func (q *Queries) RecoverRun(ctx context.Context, arg RecoverRunParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, recoverRun, arg.FinishedAt, arg.ID)
}

const restoreRun = `-- name: RestoreRun :exec
UPDATE pipeline_runs
SET
    visibility_state = 'active',
    trashed_at = NULL,
    trash_reason = NULL
WHERE id = ?1
`

func (q *Queries) RestoreRun(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, restoreRun, id)
	return err
}

const trashRun = `-- name: TrashRun :exec
UPDATE pipeline_runs
SET
    visibility_state = 'trashed',
    trashed_at = ?1,
    trash_reason = ?2
WHERE id = ?3
`

type TrashRunParams struct {
	TrashedAt   sql.NullString
	TrashReason sql.NullString
	ID          int64
}

func (q *Queries) TrashRun(ctx context.Context, arg TrashRunParams) error {
	_, err := q.db.ExecContext(ctx, trashRun, arg.TrashedAt, arg.TrashReason, arg.ID)
	return err
}
