// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metric.sql

package sql

import (
	"context"
)

const getRunMetric = `-- name: GetRunMetric :one
SELECT
    pipeline_run_id,
    metric,
    source,
    value
FROM pipeline_run_metrics
WHERE pipeline_run_id = ?1
  AND metric = ?2
  AND source = ?3
`

type GetRunMetricParams struct {
	PipelineRunID int64
	Metric        string
	Source        string
}

func (q *Queries) GetRunMetric(ctx context.Context, arg GetRunMetricParams) (PipelineRunMetric, error) {
	row := q.db.QueryRowContext(ctx, getRunMetric, arg.PipelineRunID, arg.Metric, arg.Source)
	var i PipelineRunMetric
	err := row.Scan(
		&i.PipelineRunID,
		&i.Metric,
		&i.Source,
		&i.Value,
	)
	return i, err
}

const listRunMetricsByRun = `-- name: ListRunMetricsByRun :many
SELECT
    pipeline_run_id,
    metric,
    source,
    value
FROM pipeline_run_metrics
WHERE pipeline_run_id = ?1
ORDER BY metric, source
`

func (q *Queries) ListRunMetricsByRun(ctx context.Context, pipelineRunID int64) ([]PipelineRunMetric, error) {
	rows, err := q.db.QueryContext(ctx, listRunMetricsByRun, pipelineRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PipelineRunMetric
	for rows.Next() {
		var i PipelineRunMetric
		if err := rows.Scan(
			&i.PipelineRunID,
			&i.Metric,
			&i.Source,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRunMetric = `-- name: UpsertRunMetric :exec
INSERT OR REPLACE INTO pipeline_run_metrics (
    pipeline_run_id,
    metric,
    source,
    value
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4
)
`

type UpsertRunMetricParams struct {
	PipelineRunID int64
	Metric        string
	Source        string
	Value         int64
}

func (q *Queries) UpsertRunMetric(ctx context.Context, arg UpsertRunMetricParams) error {
	_, err := q.db.ExecContext(ctx, upsertRunMetric,
		arg.PipelineRunID,
		arg.Metric,
		arg.Source,
		arg.Value,
	)
	return err
}
