// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sql

type PipelineRunMetric struct {
	PipelineRunID int64
	Metric        string
	Source        string
	Value         int64
}

type PipelineRunReviewer struct {
	PipelineRunID int64
	Username      string
	Email         string
	CreatedAt     string
}
