// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: overview.sql

package sql

import (
	"context"
	"database/sql"
)

const countDependentReviewContexts = `-- name: CountDependentReviewContexts :one
WITH RECURSIVE descendants(id) AS (
    SELECT child.id
    FROM review_contexts root
    JOIN review_contexts child ON child.parent_context_id = root.id
    WHERE root.pipeline_run_id = ?1
    UNION ALL
    SELECT child.id
    FROM review_contexts child
    JOIN descendants parent ON child.parent_context_id = parent.id
)
SELECT COUNT(*) FROM descendants
`

func (q *Queries) CountDependentReviewContexts(ctx context.Context, pipelineRunID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDependentReviewContexts, pipelineRunID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOwnedReviewContexts = `-- name: CountOwnedReviewContexts :one
SELECT COUNT(*)
FROM review_contexts
WHERE pipeline_run_id = ?1
`

func (q *Queries) CountOwnedReviewContexts(ctx context.Context, pipelineRunID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOwnedReviewContexts, pipelineRunID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRunsReusingRun = `-- name: CountRunsReusingRun :one
SELECT COUNT(DISTINCT pipeline_run_id)
FROM run_steps
WHERE reused_from_run_id = ?1
  AND pipeline_run_id != ?2
`

type CountRunsReusingRunParams struct {
	ReusedFromRunID sql.NullInt64
	PipelineRunID   int64
}

func (q *Queries) CountRunsReusingRun(ctx context.Context, arg CountRunsReusingRunParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRunsReusingRun, arg.ReusedFromRunID, arg.PipelineRunID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSharedRunArtifacts = `-- name: CountSharedRunArtifacts :one
SELECT COUNT(DISTINCT other.artifact_id)
FROM (
    SELECT rs.input_artifact_id AS artifact_id
    FROM run_steps rs
    WHERE rs.pipeline_run_id != ?1
    UNION ALL
    SELECT rs.output_artifact_id AS artifact_id
    FROM run_steps rs
    WHERE rs.pipeline_run_id != ?1
) other
WHERE other.artifact_id IN (
    SELECT rs.output_artifact_id
    FROM run_steps rs
    WHERE rs.pipeline_run_id = ?1
)
`

func (q *Queries) CountSharedRunArtifacts(ctx context.Context, pipelineRunID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSharedRunArtifacts, pipelineRunID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
