// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviewer.sql

package sql

import (
	"context"
)

const getReviewerByRun = `-- name: GetReviewerByRun :one
SELECT
    pipeline_run_id,
    username,
    email,
    created_at
FROM pipeline_run_reviewers
WHERE pipeline_run_id = ?1
`

func (q *Queries) GetReviewerByRun(ctx context.Context, pipelineRunID int64) (PipelineRunReviewer, error) {
	row := q.db.QueryRowContext(ctx, getReviewerByRun, pipelineRunID)
	var i PipelineRunReviewer
	err := row.Scan(
		&i.PipelineRunID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const insertReviewer = `-- name: InsertReviewer :exec
INSERT INTO pipeline_run_reviewers (
    pipeline_run_id,
    username,
    email,
    created_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4
)
`

type InsertReviewerParams struct {
	PipelineRunID int64
	Username      string
	Email         string
	CreatedAt     string
}

func (q *Queries) InsertReviewer(ctx context.Context, arg InsertReviewerParams) error {
	_, err := q.db.ExecContext(ctx, insertReviewer,
		arg.PipelineRunID,
		arg.Username,
		arg.Email,
		arg.CreatedAt,
	)
	return err
}
