// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: run.sql

package sql

import (
	"context"
	"database/sql"
)

const getRunByID = `-- name: GetRunByID :one
SELECT
    id,
    step,
    started_at,
    finished_at,
    status,
    summary,
    search_query,
    execution_plan_id,
    attempt_number,
    visibility_state,
    trashed_at,
    trash_reason
FROM pipeline_runs
WHERE id = ?1
`

type GetRunByIDRow struct {
	ID              int64
	Step            string
	StartedAt       string
	FinishedAt      sql.NullString
	Status          string
	Summary         sql.NullString
	SearchQuery     sql.NullString
	ExecutionPlanID sql.NullInt64
	AttemptNumber   sql.NullInt64
	VisibilityState string
	TrashedAt       sql.NullString
	TrashReason     sql.NullString
}

func (q *Queries) GetRunByID(ctx context.Context, id int64) (GetRunByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getRunByID, id)
	var i GetRunByIDRow
	err := row.Scan(
		&i.ID,
		&i.Step,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.Summary,
		&i.SearchQuery,
		&i.ExecutionPlanID,
		&i.AttemptNumber,
		&i.VisibilityState,
		&i.TrashedAt,
		&i.TrashReason,
	)
	return i, err
}

const insertRun = `-- name: InsertRun :execresult
INSERT INTO pipeline_runs (
    step,
    started_at,
    status,
    search_query
) VALUES (
    ?1,
    ?2,
    'running',
    ?3
)
`

type InsertRunParams struct {
	Step        string
	StartedAt   string
	SearchQuery sql.NullString
}

func (q *Queries) InsertRun(ctx context.Context, arg InsertRunParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertRun, arg.Step, arg.StartedAt, arg.SearchQuery)
}

const listRunsByPlan = `-- name: ListRunsByPlan :many
SELECT
    id,
    step,
    started_at,
    finished_at,
    status,
    summary,
    search_query,
    execution_plan_id,
    attempt_number,
    visibility_state,
    trashed_at,
    trash_reason
FROM pipeline_runs
WHERE execution_plan_id = ?1
ORDER BY attempt_number
`

type ListRunsByPlanRow struct {
	ID              int64
	Step            string
	StartedAt       string
	FinishedAt      sql.NullString
	Status          string
	Summary         sql.NullString
	SearchQuery     sql.NullString
	ExecutionPlanID sql.NullInt64
	AttemptNumber   sql.NullInt64
	VisibilityState string
	TrashedAt       sql.NullString
	TrashReason     sql.NullString
}

func (q *Queries) ListRunsByPlan(ctx context.Context, executionPlanID sql.NullInt64) ([]ListRunsByPlanRow, error) {
	rows, err := q.db.QueryContext(ctx, listRunsByPlan, executionPlanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunsByPlanRow
	for rows.Next() {
		var i ListRunsByPlanRow
		if err := rows.Scan(
			&i.ID,
			&i.Step,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.Summary,
			&i.SearchQuery,
			&i.ExecutionPlanID,
			&i.AttemptNumber,
			&i.VisibilityState,
			&i.TrashedAt,
			&i.TrashReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByVisibility = `-- name: ListRunsByVisibility :many
SELECT
    id,
    step,
    started_at,
    finished_at,
    status,
    summary,
    search_query,
    execution_plan_id,
    attempt_number,
    visibility_state,
    trashed_at,
    trash_reason
FROM pipeline_runs
WHERE visibility_state = ?1
ORDER BY id
`

type ListRunsByVisibilityRow struct {
	ID              int64
	Step            string
	StartedAt       string
	FinishedAt      sql.NullString
	Status          string
	Summary         sql.NullString
	SearchQuery     sql.NullString
	ExecutionPlanID sql.NullInt64
	AttemptNumber   sql.NullInt64
	VisibilityState string
	TrashedAt       sql.NullString
	TrashReason     sql.NullString
}

func (q *Queries) ListRunsByVisibility(ctx context.Context, visibilityState string) ([]ListRunsByVisibilityRow, error) {
	rows, err := q.db.QueryContext(ctx, listRunsByVisibility, visibilityState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunsByVisibilityRow
	for rows.Next() {
		var i ListRunsByVisibilityRow
		if err := rows.Scan(
			&i.ID,
			&i.Step,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.Summary,
			&i.SearchQuery,
			&i.ExecutionPlanID,
			&i.AttemptNumber,
			&i.VisibilityState,
			&i.TrashedAt,
			&i.TrashReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
