// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: step.sql

package sql

import (
	"context"
	"database/sql"
)

const insertRunStep = `-- name: InsertRunStep :execresult
INSERT INTO run_steps (
    pipeline_run_id,
    step_name,
    started_at
) VALUES (
    ?1,
    ?2,
    ?3
)
`

type InsertRunStepParams struct {
	PipelineRunID int64
	StepName      string
	StartedAt     sql.NullString
}

func (q *Queries) InsertRunStep(ctx context.Context, arg InsertRunStepParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertRunStep, arg.PipelineRunID, arg.StepName, arg.StartedAt)
}

const linkRunStepInputArtifact = `-- name: LinkRunStepInputArtifact :exec
UPDATE run_steps
SET input_artifact_id = ?1
WHERE id = ?2
`

type LinkRunStepInputArtifactParams struct {
	InputArtifactID sql.NullInt64
	ID              int64
}

func (q *Queries) LinkRunStepInputArtifact(ctx context.Context, arg LinkRunStepInputArtifactParams) error {
	_, err := q.db.ExecContext(ctx, linkRunStepInputArtifact, arg.InputArtifactID, arg.ID)
	return err
}

const linkRunStepOutputArtifact = `-- name: LinkRunStepOutputArtifact :exec
UPDATE run_steps
SET output_artifact_id = ?1
WHERE id = ?2
`

type LinkRunStepOutputArtifactParams struct {
	OutputArtifactID sql.NullInt64
	ID               int64
}

func (q *Queries) LinkRunStepOutputArtifact(ctx context.Context, arg LinkRunStepOutputArtifactParams) error {
	_, err := q.db.ExecContext(ctx, linkRunStepOutputArtifact, arg.OutputArtifactID, arg.ID)
	return err
}

const linkRunStepReuse = `-- name: LinkRunStepReuse :exec
UPDATE run_steps
SET
    reused_from_run_id = ?1,
    step_status = 'reused',
    finished_at = ?2
WHERE id = ?3
`

type LinkRunStepReuseParams struct {
	ReusedFromRunID sql.NullInt64
	FinishedAt      sql.NullString
	ID              int64
}

func (q *Queries) LinkRunStepReuse(ctx context.Context, arg LinkRunStepReuseParams) error {
	_, err := q.db.ExecContext(ctx, linkRunStepReuse, arg.ReusedFromRunID, arg.FinishedAt, arg.ID)
	return err
}

const listRunStepsByRun = `-- name: ListRunStepsByRun :many
SELECT
    id,
    pipeline_run_id,
    step_name,
    step_status,
    input_artifact_id,
    output_artifact_id,
    reused_from_run_id,
    input_fingerprint,
    output_fingerprint,
    started_at,
    finished_at
FROM run_steps
WHERE pipeline_run_id = ?1
ORDER BY id
`

type ListRunStepsByRunRow struct {
	ID                int64
	PipelineRunID     int64
	StepName          string
	StepStatus        string
	InputArtifactID   sql.NullInt64
	OutputArtifactID  sql.NullInt64
	ReusedFromRunID   sql.NullInt64
	InputFingerprint  string
	OutputFingerprint string
	StartedAt         sql.NullString
	FinishedAt        sql.NullString
}

func (q *Queries) ListRunStepsByRun(ctx context.Context, pipelineRunID int64) ([]ListRunStepsByRunRow, error) {
	rows, err := q.db.QueryContext(ctx, listRunStepsByRun, pipelineRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunStepsByRunRow
	for rows.Next() {
		var i ListRunStepsByRunRow
		if err := rows.Scan(
			&i.ID,
			&i.PipelineRunID,
			&i.StepName,
			&i.StepStatus,
			&i.InputArtifactID,
			&i.OutputArtifactID,
			&i.ReusedFromRunID,
			&i.InputFingerprint,
			&i.OutputFingerprint,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRunStepFingerprints = `-- name: SetRunStepFingerprints :exec
UPDATE run_steps
SET
    input_fingerprint = ?1,
    output_fingerprint = ?2
WHERE id = ?3
`

type SetRunStepFingerprintsParams struct {
	InputFingerprint  string
	OutputFingerprint string
	ID                int64
}

func (q *Queries) SetRunStepFingerprints(ctx context.Context, arg SetRunStepFingerprintsParams) error {
	_, err := q.db.ExecContext(ctx, setRunStepFingerprints, arg.InputFingerprint, arg.OutputFingerprint, arg.ID)
	return err
}

const updateRunStepStatus = `-- name: UpdateRunStepStatus :exec
UPDATE run_steps
SET
    step_status = ?1,
    finished_at = ?2
WHERE id = ?3
`

type UpdateRunStepStatusParams struct {
	StepStatus string
	FinishedAt sql.NullString
	ID         int64
}

func (q *Queries) UpdateRunStepStatus(ctx context.Context, arg UpdateRunStepStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateRunStepStatus, arg.StepStatus, arg.FinishedAt, arg.ID)
	return err
}
