import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const frontendDirectory = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const stylesheetPaths = [
  "styles/tokens.css",
  "styles/base.css",
  "styles/elements.css",
  "styles/collections.css",
  "styles/views.css",
  "styles/graph.css",
] as const;
const registryPath = resolve(frontendDirectory, "src/jsx/classes.ts");

/** Extracts sorted, unique class tokens from CSS selector preludes. */
export function extractClassTokens(css: string): string[] {
  const tokens = new Set<string>();
  const withoutComments = css.replace(/\/\*[\s\S]*?\*\//g, "");

  for (const match of withoutComments.matchAll(/([^{}]+)\{/g)) {
    const prelude = match[1].trim();
    if (prelude.startsWith("@")) continue;

    const withoutAttributes = prelude.replace(/\[[^\]]*\]/g, "");
    const selectors = withoutAttributes.replace(/"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'/g, "");
    for (const tokenMatch of selectors.matchAll(/\.([-_A-Za-z][-_A-Za-z0-9]*)/g)) {
      tokens.add(tokenMatch[1]);
    }
  }

  const sortedTokens = Array.from(tokens);
  sortedTokens.sort();
  return sortedTokens;
}

/** Renders the committed TypeScript class registry. */
export function renderClassRegistry(tokens: readonly string[]): string {
  const registryLines = tokens.map((token) => `  ${JSON.stringify(token)},`);
  const entries = registryLines.join("\n");
  return `// Code generated by frontend/scripts/generate-classes.ts. DO NOT EDIT.\n\nexport const classTokens = [\n${entries}\n] as const;\n\nexport type ClassName = (typeof classTokens)[number];\n`;
}

/** Builds the expected registry contents from the authoritative stylesheets. */
export function generateClassRegistry(): string {
  const tokens = new Set<string>();
  for (const stylesheetPath of stylesheetPaths) {
    const css = readFileSync(resolve(frontendDirectory, stylesheetPath), "utf8");
    for (const token of extractClassTokens(css)) {
      tokens.add(token);
    }
  }
  const sortedTokens = Array.from(tokens);
  sortedTokens.sort();
  return renderClassRegistry(sortedTokens);
}

/** Returns whether committed registry contents match freshly generated contents. */
export function isClassRegistryFresh(committed: string, generated: string): boolean {
  return committed === generated;
}

/** Generates or verifies the committed class registry for command-line use. */
export function main(args: readonly string[] = process.argv.slice(2)): void {
  const generated = generateClassRegistry();
  if (args[0] === "--check") {
    let committed = "";
    try {
      committed = readFileSync(registryPath, "utf8");
    } catch {
      console.error("The generated class registry is missing. Run make frontend-classes.");
      process.exitCode = 1;
      return;
    }
    if (!isClassRegistryFresh(committed, generated)) {
      console.error("The generated class registry is stale. Run make frontend-classes and review the diff.");
      process.exitCode = 1;
    }
    return;
  }
  if (args.length !== 0) {
    console.error(`Unknown argument: ${args[0]}`);
    process.exitCode = 2;
    return;
  }
  writeFileSync(registryPath, generated);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
