// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authorship.sql

package sql

import (
	"context"
	"database/sql"
)

const insertAuthorship = `-- name: InsertAuthorship :execresult
INSERT INTO authorships (
    work_revision_id,
    author_occurrence_id,
    author_order,
    affiliation
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4
)
`

type InsertAuthorshipParams struct {
	WorkRevisionID     int64
	AuthorOccurrenceID int64
	AuthorOrder        int64
	Affiliation        sql.NullString
}

func (q *Queries) InsertAuthorship(ctx context.Context, arg InsertAuthorshipParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertAuthorship,
		arg.WorkRevisionID,
		arg.AuthorOccurrenceID,
		arg.AuthorOrder,
		arg.Affiliation,
	)
}

const listAuthorshipsByOccurrenceID = `-- name: ListAuthorshipsByOccurrenceID :many
SELECT
    id,
    work_revision_id,
    author_occurrence_id,
    author_order,
    affiliation,
    created_at
FROM authorships
WHERE author_occurrence_id = ?1
ORDER BY id
`

func (q *Queries) ListAuthorshipsByOccurrenceID(ctx context.Context, authorOccurrenceID int64) ([]Authorship, error) {
	rows, err := q.db.QueryContext(ctx, listAuthorshipsByOccurrenceID, authorOccurrenceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Authorship
	for rows.Next() {
		var i Authorship
		if err := rows.Scan(
			&i.ID,
			&i.WorkRevisionID,
			&i.AuthorOccurrenceID,
			&i.AuthorOrder,
			&i.Affiliation,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthorshipsByRevisionID = `-- name: ListAuthorshipsByRevisionID :many
SELECT
    id,
    work_revision_id,
    author_occurrence_id,
    author_order,
    affiliation,
    created_at
FROM authorships
WHERE work_revision_id = ?1
ORDER BY author_order
`

func (q *Queries) ListAuthorshipsByRevisionID(ctx context.Context, workRevisionID int64) ([]Authorship, error) {
	rows, err := q.db.QueryContext(ctx, listAuthorshipsByRevisionID, workRevisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Authorship
	for rows.Next() {
		var i Authorship
		if err := rows.Scan(
			&i.ID,
			&i.WorkRevisionID,
			&i.AuthorOccurrenceID,
			&i.AuthorOrder,
			&i.Affiliation,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
