// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: author.sql

package sql

import (
	"context"
	"database/sql"
)

const getPersonByID = `-- name: GetPersonByID :one
SELECT
    id,
    orcid,
    created_at
FROM people
WHERE id = ?1
`

func (q *Queries) GetPersonByID(ctx context.Context, id int64) (Person, error) {
	row := q.db.QueryRowContext(ctx, getPersonByID, id)
	var i Person
	err := row.Scan(&i.ID, &i.Orcid, &i.CreatedAt)
	return i, err
}

const getPersonByORCID = `-- name: GetPersonByORCID :one
SELECT
    id,
    orcid,
    created_at
FROM people
WHERE orcid = ?1
`

func (q *Queries) GetPersonByORCID(ctx context.Context, orcid sql.NullString) (Person, error) {
	row := q.db.QueryRowContext(ctx, getPersonByORCID, orcid)
	var i Person
	err := row.Scan(&i.ID, &i.Orcid, &i.CreatedAt)
	return i, err
}

const insertPersonByORCID = `-- name: InsertPersonByORCID :execresult
INSERT OR IGNORE INTO people (orcid)
VALUES (?1)
`

func (q *Queries) InsertPersonByORCID(ctx context.Context, orcid sql.NullString) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertPersonByORCID, orcid)
}
