// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: evidence.sql

package sql

import (
	"context"
	"database/sql"
)

const insertAuthorIdentityCandidate = `-- name: InsertAuthorIdentityCandidate :execresult
INSERT INTO author_identity_candidates (
    identity_resolution_id,
    candidate_orcid,
    provider_display_name,
    query_url,
    payload_artifact_id,
    provider_rank
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6
)
`

type InsertAuthorIdentityCandidateParams struct {
	IdentityResolutionID int64
	CandidateOrcid       string
	ProviderDisplayName  sql.NullString
	QueryUrl             string
	PayloadArtifactID    sql.NullInt64
	ProviderRank         int64
}

func (q *Queries) InsertAuthorIdentityCandidate(ctx context.Context, arg InsertAuthorIdentityCandidateParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertAuthorIdentityCandidate,
		arg.IdentityResolutionID,
		arg.CandidateOrcid,
		arg.ProviderDisplayName,
		arg.QueryUrl,
		arg.PayloadArtifactID,
		arg.ProviderRank,
	)
}
