// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package sql

import (
	"context"
	"database/sql"
)

const insertAuthorIdentityResolution = `-- name: InsertAuthorIdentityResolution :execresult
INSERT INTO author_identity_resolutions (
    pipeline_run_id,
    author_occurrence_id,
    status,
    provider,
    queried_citation_name,
    error_message,
    resolved_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7
)
`

type InsertAuthorIdentityResolutionParams struct {
	PipelineRunID       int64
	AuthorOccurrenceID  int64
	Status              string
	Provider            string
	QueriedCitationName string
	ErrorMessage        sql.NullString
	ResolvedAt          string
}

func (q *Queries) InsertAuthorIdentityResolution(ctx context.Context, arg InsertAuthorIdentityResolutionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertAuthorIdentityResolution,
		arg.PipelineRunID,
		arg.AuthorOccurrenceID,
		arg.Status,
		arg.Provider,
		arg.QueriedCitationName,
		arg.ErrorMessage,
		arg.ResolvedAt,
	)
}
