// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sql

import (
	"database/sql"
)

type AuthorOccurrence struct {
	ID           int64
	PersonID     sql.NullInt64
	CitationName string
	FirstName    sql.NullString
	LastName     sql.NullString
	Orcid        sql.NullString
	CreatedAt    string
}

type Authorship struct {
	ID                 int64
	WorkRevisionID     int64
	AuthorOccurrenceID int64
	AuthorOrder        int64
	Affiliation        sql.NullString
	CreatedAt          string
}

type Person struct {
	ID        int64
	Orcid     sql.NullString
	CreatedAt string
}
