// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: occurrence.sql

package sql

import (
	"context"
	"database/sql"
)

const getAuthorOccurrenceByID = `-- name: GetAuthorOccurrenceByID :one
SELECT
    id,
    person_id,
    citation_name,
    first_name,
    last_name,
    orcid,
    created_at
FROM author_occurrences
WHERE id = ?1
`

func (q *Queries) GetAuthorOccurrenceByID(ctx context.Context, id int64) (AuthorOccurrence, error) {
	row := q.db.QueryRowContext(ctx, getAuthorOccurrenceByID, id)
	var i AuthorOccurrence
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.CitationName,
		&i.FirstName,
		&i.LastName,
		&i.Orcid,
		&i.CreatedAt,
	)
	return i, err
}

const insertAuthorOccurrence = `-- name: InsertAuthorOccurrence :execresult
INSERT INTO author_occurrences (
    person_id,
    citation_name,
    first_name,
    last_name,
    orcid
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5
)
`

type InsertAuthorOccurrenceParams struct {
	PersonID     sql.NullInt64
	CitationName string
	FirstName    sql.NullString
	LastName     sql.NullString
	Orcid        sql.NullString
}

func (q *Queries) InsertAuthorOccurrence(ctx context.Context, arg InsertAuthorOccurrenceParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertAuthorOccurrence,
		arg.PersonID,
		arg.CitationName,
		arg.FirstName,
		arg.LastName,
		arg.Orcid,
	)
}

const listAuthorOccurrencesByPersonID = `-- name: ListAuthorOccurrencesByPersonID :many
SELECT
    id,
    person_id,
    citation_name,
    first_name,
    last_name,
    orcid,
    created_at
FROM author_occurrences
WHERE person_id = ?1
ORDER BY id
`

func (q *Queries) ListAuthorOccurrencesByPersonID(ctx context.Context, personID sql.NullInt64) ([]AuthorOccurrence, error) {
	rows, err := q.db.QueryContext(ctx, listAuthorOccurrencesByPersonID, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthorOccurrence
	for rows.Next() {
		var i AuthorOccurrence
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.CitationName,
			&i.FirstName,
			&i.LastName,
			&i.Orcid,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
