// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cache_use.sql

package sql

import (
	"context"
	"database/sql"
)

const findAnyRunCacheEntry = `-- name: FindAnyRunCacheEntry :one
SELECT
    ce.id,
    ce.provider,
    ce.namespace,
    ce.request_fingerprint,
    ce.response_status,
    ce.payload_artifact_id,
    ce.fetched_at,
    ce.expires_at,
    ce.extractor_version,
    ce.created_at,
    ce.updated_at
FROM run_cache_uses rcu
JOIN cache_entries ce ON ce.id = rcu.cache_entry_id
WHERE rcu.pipeline_run_id = ?1
  AND ce.provider = ?2
  AND ce.namespace = ?3
  AND ce.request_fingerprint = ?4
  AND (
        ce.extractor_version = ?5
        OR ce.extractor_version LIKE ?6
    )
ORDER BY rcu.id DESC
LIMIT 1
`

type FindAnyRunCacheEntryParams struct {
	PipelineRunID           int64
	Provider                string
	Namespace               string
	RequestFingerprint      string
	ExtractorVersion        string
	ExtractorVersionPattern string
}

func (q *Queries) FindAnyRunCacheEntry(ctx context.Context, arg FindAnyRunCacheEntryParams) (CacheEntry, error) {
	row := q.db.QueryRowContext(ctx, findAnyRunCacheEntry,
		arg.PipelineRunID,
		arg.Provider,
		arg.Namespace,
		arg.RequestFingerprint,
		arg.ExtractorVersion,
		arg.ExtractorVersionPattern,
	)
	var i CacheEntry
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Namespace,
		&i.RequestFingerprint,
		&i.ResponseStatus,
		&i.PayloadArtifactID,
		&i.FetchedAt,
		&i.ExpiresAt,
		&i.ExtractorVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findRunCacheEntry = `-- name: FindRunCacheEntry :one
SELECT
    ce.id,
    ce.provider,
    ce.namespace,
    ce.request_fingerprint,
    ce.response_status,
    ce.payload_artifact_id,
    ce.fetched_at,
    ce.expires_at,
    ce.extractor_version,
    ce.created_at,
    ce.updated_at
FROM run_cache_uses rcu
JOIN cache_entries ce ON ce.id = rcu.cache_entry_id
WHERE rcu.pipeline_run_id = ?1
  AND rcu.cache_layer = ?2
  AND ce.provider = ?3
  AND ce.namespace = ?4
  AND ce.request_fingerprint = ?5
  AND ce.extractor_version = ?6
ORDER BY rcu.id DESC
LIMIT 1
`

type FindRunCacheEntryParams struct {
	PipelineRunID      int64
	CacheLayer         string
	Provider           string
	Namespace          string
	RequestFingerprint string
	ExtractorVersion   string
}

func (q *Queries) FindRunCacheEntry(ctx context.Context, arg FindRunCacheEntryParams) (CacheEntry, error) {
	row := q.db.QueryRowContext(ctx, findRunCacheEntry,
		arg.PipelineRunID,
		arg.CacheLayer,
		arg.Provider,
		arg.Namespace,
		arg.RequestFingerprint,
		arg.ExtractorVersion,
	)
	var i CacheEntry
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Namespace,
		&i.RequestFingerprint,
		&i.ResponseStatus,
		&i.PayloadArtifactID,
		&i.FetchedAt,
		&i.ExpiresAt,
		&i.ExtractorVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRunCacheUse = `-- name: InsertRunCacheUse :execresult
INSERT INTO run_cache_uses (
    pipeline_run_id,
    cache_entry_id,
    cache_layer,
    outcome
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4
)
`

type InsertRunCacheUseParams struct {
	PipelineRunID int64
	CacheEntryID  int64
	CacheLayer    string
	Outcome       string
}

func (q *Queries) InsertRunCacheUse(ctx context.Context, arg InsertRunCacheUseParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertRunCacheUse,
		arg.PipelineRunID,
		arg.CacheEntryID,
		arg.CacheLayer,
		arg.Outcome,
	)
}

const listRunCacheUsesByRun = `-- name: ListRunCacheUsesByRun :many
SELECT
    id,
    pipeline_run_id,
    cache_entry_id,
    cache_layer,
    outcome,
    used_at
FROM run_cache_uses
WHERE pipeline_run_id = ?1
ORDER BY id
`

func (q *Queries) ListRunCacheUsesByRun(ctx context.Context, pipelineRunID int64) ([]RunCacheUse, error) {
	rows, err := q.db.QueryContext(ctx, listRunCacheUsesByRun, pipelineRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunCacheUse
	for rows.Next() {
		var i RunCacheUse
		if err := rows.Scan(
			&i.ID,
			&i.PipelineRunID,
			&i.CacheEntryID,
			&i.CacheLayer,
			&i.Outcome,
			&i.UsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
