// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cache.sql

package sql

import (
	"context"
	"database/sql"
)

const globalCacheEntry = `-- name: GlobalCacheEntry :one
SELECT
    ce.id,
    ce.provider,
    ce.namespace,
    ce.request_fingerprint,
    ce.response_status,
    ce.payload_artifact_id,
    ce.fetched_at,
    ce.expires_at,
    ce.extractor_version,
    ce.created_at,
    ce.updated_at
FROM cache_entries ce
JOIN run_cache_uses rcu ON rcu.cache_entry_id = ce.id
WHERE rcu.cache_layer = 'global'
  AND ce.provider = ?1
  AND ce.namespace = ?2
  AND ce.request_fingerprint = ?3
  AND ce.extractor_version = ?4
ORDER BY ce.id DESC, rcu.id DESC
LIMIT 1
`

type GlobalCacheEntryParams struct {
	Provider           string
	Namespace          string
	RequestFingerprint string
	ExtractorVersion   string
}

func (q *Queries) GlobalCacheEntry(ctx context.Context, arg GlobalCacheEntryParams) (CacheEntry, error) {
	row := q.db.QueryRowContext(ctx, globalCacheEntry,
		arg.Provider,
		arg.Namespace,
		arg.RequestFingerprint,
		arg.ExtractorVersion,
	)
	var i CacheEntry
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Namespace,
		&i.RequestFingerprint,
		&i.ResponseStatus,
		&i.PayloadArtifactID,
		&i.FetchedAt,
		&i.ExpiresAt,
		&i.ExtractorVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCacheEntry = `-- name: InsertCacheEntry :execresult
INSERT INTO cache_entries (
    provider,
    namespace,
    request_fingerprint,
    response_status,
    payload_artifact_id,
    fetched_at,
    expires_at,
    extractor_version
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8
)
`

type InsertCacheEntryParams struct {
	Provider           string
	Namespace          string
	RequestFingerprint string
	ResponseStatus     int64
	PayloadArtifactID  sql.NullInt64
	FetchedAt          string
	ExpiresAt          sql.NullString
	ExtractorVersion   string
}

func (q *Queries) InsertCacheEntry(ctx context.Context, arg InsertCacheEntryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertCacheEntry,
		arg.Provider,
		arg.Namespace,
		arg.RequestFingerprint,
		arg.ResponseStatus,
		arg.PayloadArtifactID,
		arg.FetchedAt,
		arg.ExpiresAt,
		arg.ExtractorVersion,
	)
}

const latestCacheEntry = `-- name: LatestCacheEntry :one
SELECT
    id,
    provider,
    namespace,
    request_fingerprint,
    response_status,
    payload_artifact_id,
    fetched_at,
    expires_at,
    extractor_version,
    created_at,
    updated_at
FROM cache_entries
WHERE provider = ?1
  AND namespace = ?2
  AND request_fingerprint = ?3
  AND extractor_version = ?4
ORDER BY id DESC
LIMIT 1
`

type LatestCacheEntryParams struct {
	Provider           string
	Namespace          string
	RequestFingerprint string
	ExtractorVersion   string
}

func (q *Queries) LatestCacheEntry(ctx context.Context, arg LatestCacheEntryParams) (CacheEntry, error) {
	row := q.db.QueryRowContext(ctx, latestCacheEntry,
		arg.Provider,
		arg.Namespace,
		arg.RequestFingerprint,
		arg.ExtractorVersion,
	)
	var i CacheEntry
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Namespace,
		&i.RequestFingerprint,
		&i.ResponseStatus,
		&i.PayloadArtifactID,
		&i.FetchedAt,
		&i.ExpiresAt,
		&i.ExtractorVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
