// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sql

import (
	"database/sql"
)

type PdfDocument struct {
	Doi           string
	Status        string
	ContentHash   sql.NullString
	InventoriedAt sql.NullString
	UpdatedAt     string
}
