// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sql

import (
	"context"
	"database/sql"
)

const getAvailablePDFDocument = `-- name: GetAvailablePDFDocument :one
SELECT
    d.content_hash,
    d.inventoried_at,
    b.byte_size
FROM pdf_documents d
JOIN pdf_blobs b ON b.content_hash=d.content_hash
WHERE d.doi = ?1
  AND d.status='available'
`

type GetAvailablePDFDocumentRow struct {
	ContentHash   sql.NullString
	InventoriedAt sql.NullString
	ByteSize      int64
}

func (q *Queries) GetAvailablePDFDocument(ctx context.Context, doi string) (GetAvailablePDFDocumentRow, error) {
	row := q.db.QueryRowContext(ctx, getAvailablePDFDocument, doi)
	var i GetAvailablePDFDocumentRow
	err := row.Scan(&i.ContentHash, &i.InventoriedAt, &i.ByteSize)
	return i, err
}

const getPDFBlobData = `-- name: GetPDFBlobData :one
SELECT data
FROM pdf_blobs
WHERE content_hash = ?1
`

func (q *Queries) GetPDFBlobData(ctx context.Context, contentHash string) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getPDFBlobData, contentHash)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const listAvailablePDFDOIs = `-- name: ListAvailablePDFDOIs :many

SELECT document.doi
FROM pdf_documents document
JOIN pdf_blobs blob ON blob.content_hash=document.content_hash
WHERE document.status='available'
ORDER BY document.doi
`

// Viewer-facing companion PDF reads. Registration, insertion, and outbox
// delivery keep their handwritten orchestration and savepoint protocol.
func (q *Queries) ListAvailablePDFDOIs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAvailablePDFDOIs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var doi string
		if err := rows.Scan(&doi); err != nil {
			return nil, err
		}
		items = append(items, doi)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
