// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: export.sql

package sql

import (
	"context"
	"database/sql"
)

const countArtifactReferences = `-- name: CountArtifactReferences :one
SELECT
    (SELECT COUNT(*) FROM run_artifacts WHERE artifact_id = ?1) +
    (SELECT COUNT(*) FROM run_steps WHERE input_artifact_id = ?1 OR output_artifact_id = ?1) +
    (SELECT COUNT(*) FROM cache_entries WHERE payload_artifact_id = ?1) +
    (SELECT COUNT(*) FROM author_identity_candidates WHERE payload_artifact_id = ?1)
`

func (q *Queries) CountArtifactReferences(ctx context.Context, artifactID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countArtifactReferences, artifactID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteArtifact = `-- name: DeleteArtifact :exec
DELETE FROM artifacts
WHERE id = ?1
`

func (q *Queries) DeleteArtifact(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteArtifact, id)
	return err
}

const deleteArtifactBlob = `-- name: DeleteArtifactBlob :exec
DELETE FROM artifact_blobs
WHERE artifact_id = ?1
`

func (q *Queries) DeleteArtifactBlob(ctx context.Context, artifactID int64) error {
	_, err := q.db.ExecContext(ctx, deleteArtifactBlob, artifactID)
	return err
}

const getArtifactByHash = `-- name: GetArtifactByHash :one
SELECT id
FROM artifacts
WHERE content_hash = ?1
`

func (q *Queries) GetArtifactByHash(ctx context.Context, contentHash string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getArtifactByHash, contentHash)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getPDFStoreBinding = `-- name: GetPDFStoreBinding :one

SELECT relative_path
FROM pdf_store_binding
WHERE id = 1
`

// Static prepare-osf export statements. The copy, pragma, integrity, and
// publication orchestration stays handwritten in main.go; these named queries
// only replace the statement text and row scanning.
func (q *Queries) GetPDFStoreBinding(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getPDFStoreBinding)
	var relative_path string
	err := row.Scan(&relative_path)
	return relative_path, err
}

const insertArtifact = `-- name: InsertArtifact :execresult
INSERT INTO artifacts (content_hash, byte_size, content_type)
VALUES (?1, ?2, ?3)
`

type InsertArtifactParams struct {
	ContentHash string
	ByteSize    int64
	ContentType string
}

func (q *Queries) InsertArtifact(ctx context.Context, arg InsertArtifactParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertArtifact, arg.ContentHash, arg.ByteSize, arg.ContentType)
}

const insertArtifactBlob = `-- name: InsertArtifactBlob :exec
INSERT INTO artifact_blobs (artifact_id, pipeline_run_id, data)
VALUES (?1, ?2, ?3)
`

type InsertArtifactBlobParams struct {
	ArtifactID    int64
	PipelineRunID int64
	Data          []byte
}

func (q *Queries) InsertArtifactBlob(ctx context.Context, arg InsertArtifactBlobParams) error {
	_, err := q.db.ExecContext(ctx, insertArtifactBlob, arg.ArtifactID, arg.PipelineRunID, arg.Data)
	return err
}

const listArtifactBlobs = `-- name: ListArtifactBlobs :many
SELECT artifact.content_hash, artifact.byte_size, blob.data
FROM artifacts artifact
JOIN artifact_blobs blob ON blob.artifact_id = artifact.id
`

type ListArtifactBlobsRow struct {
	ContentHash string
	ByteSize    int64
	Data        []byte
}

func (q *Queries) ListArtifactBlobs(ctx context.Context) ([]ListArtifactBlobsRow, error) {
	rows, err := q.db.QueryContext(ctx, listArtifactBlobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArtifactBlobsRow
	for rows.Next() {
		var i ListArtifactBlobsRow
		if err := rows.Scan(&i.ContentHash, &i.ByteSize, &i.Data); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceConfigArtifacts = `-- name: ListWorkspaceConfigArtifacts :many
SELECT DISTINCT artifact.id, artifact.content_hash, artifact.content_type,
    blob.pipeline_run_id, blob.data
FROM run_artifacts link
JOIN artifacts artifact ON artifact.id = link.artifact_id
JOIN artifact_blobs blob ON blob.artifact_id = artifact.id
WHERE link.artifact_role = 'workspace_config'
ORDER BY artifact.id
`

type ListWorkspaceConfigArtifactsRow struct {
	ID            int64
	ContentHash   string
	ContentType   string
	PipelineRunID int64
	Data          []byte
}

func (q *Queries) ListWorkspaceConfigArtifacts(ctx context.Context) ([]ListWorkspaceConfigArtifactsRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceConfigArtifacts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkspaceConfigArtifactsRow
	for rows.Next() {
		var i ListWorkspaceConfigArtifactsRow
		if err := rows.Scan(
			&i.ID,
			&i.ContentHash,
			&i.ContentType,
			&i.PipelineRunID,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const redactReviewers = `-- name: RedactReviewers :exec
UPDATE pipeline_run_reviewers
SET username = '', email = ''
`

func (q *Queries) RedactReviewers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, redactReviewers)
	return err
}

const regenerateReviewCorpusID = `-- name: RegenerateReviewCorpusID :exec
UPDATE review_settings
SET corpus_id = lower(hex(randomblob(16)))
WHERE id = 1
`

func (q *Queries) RegenerateReviewCorpusID(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, regenerateReviewCorpusID)
	return err
}

const rewireRunArtifacts = `-- name: RewireRunArtifacts :exec
UPDATE run_artifacts
SET artifact_id = ?1
WHERE artifact_id = ?2
`

type RewireRunArtifactsParams struct {
	NewArtifactID int64
	OldArtifactID int64
}

func (q *Queries) RewireRunArtifacts(ctx context.Context, arg RewireRunArtifactsParams) error {
	_, err := q.db.ExecContext(ctx, rewireRunArtifacts, arg.NewArtifactID, arg.OldArtifactID)
	return err
}

const rewireRunStepInputs = `-- name: RewireRunStepInputs :exec
UPDATE run_steps
SET input_artifact_id = ?1, input_fingerprint = ?2
WHERE input_artifact_id = ?3
`

type RewireRunStepInputsParams struct {
	NewArtifactID sql.NullInt64
	NewHash       string
	OldArtifactID sql.NullInt64
}

func (q *Queries) RewireRunStepInputs(ctx context.Context, arg RewireRunStepInputsParams) error {
	_, err := q.db.ExecContext(ctx, rewireRunStepInputs, arg.NewArtifactID, arg.NewHash, arg.OldArtifactID)
	return err
}

const rewireRunStepOutputs = `-- name: RewireRunStepOutputs :exec
UPDATE run_steps
SET output_artifact_id = ?1, output_fingerprint = ?2
WHERE output_artifact_id = ?3
`

type RewireRunStepOutputsParams struct {
	NewArtifactID sql.NullInt64
	NewHash       string
	OldArtifactID sql.NullInt64
}

func (q *Queries) RewireRunStepOutputs(ctx context.Context, arg RewireRunStepOutputsParams) error {
	_, err := q.db.ExecContext(ctx, rewireRunStepOutputs, arg.NewArtifactID, arg.NewHash, arg.OldArtifactID)
	return err
}

const rewireSearchRevisions = `-- name: RewireSearchRevisions :exec
UPDATE search_revisions
SET config_artifact_hash = ?1
WHERE config_artifact_hash = ?2
`

type RewireSearchRevisionsParams struct {
	NewHash string
	OldHash string
}

func (q *Queries) RewireSearchRevisions(ctx context.Context, arg RewireSearchRevisionsParams) error {
	_, err := q.db.ExecContext(ctx, rewireSearchRevisions, arg.NewHash, arg.OldHash)
	return err
}
