// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: filter_count.sql

package sql

import (
	"context"
)

const getSourceFilterCount = `-- name: GetSourceFilterCount :one
SELECT
    id,
    pipeline_run_id,
    source_name,
    filter_data
FROM source_filter_counts
WHERE pipeline_run_id = ?1
  AND source_name = ?2
`

type GetSourceFilterCountParams struct {
	PipelineRunID int64
	SourceName    string
}

func (q *Queries) GetSourceFilterCount(ctx context.Context, arg GetSourceFilterCountParams) (SourceFilterCount, error) {
	row := q.db.QueryRowContext(ctx, getSourceFilterCount, arg.PipelineRunID, arg.SourceName)
	var i SourceFilterCount
	err := row.Scan(
		&i.ID,
		&i.PipelineRunID,
		&i.SourceName,
		&i.FilterData,
	)
	return i, err
}

const listSourceFilterCountsByRun = `-- name: ListSourceFilterCountsByRun :many
SELECT
    id,
    pipeline_run_id,
    source_name,
    filter_data
FROM source_filter_counts
WHERE pipeline_run_id = ?1
ORDER BY source_name
`

func (q *Queries) ListSourceFilterCountsByRun(ctx context.Context, pipelineRunID int64) ([]SourceFilterCount, error) {
	rows, err := q.db.QueryContext(ctx, listSourceFilterCountsByRun, pipelineRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SourceFilterCount
	for rows.Next() {
		var i SourceFilterCount
		if err := rows.Scan(
			&i.ID,
			&i.PipelineRunID,
			&i.SourceName,
			&i.FilterData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSourceFilterCount = `-- name: UpsertSourceFilterCount :exec
INSERT INTO source_filter_counts (
    pipeline_run_id,
    source_name,
    filter_data
) VALUES (
    ?1,
    ?2,
    ?3
)
ON CONFLICT(pipeline_run_id, source_name) DO UPDATE SET
    filter_data = excluded.filter_data
`

type UpsertSourceFilterCountParams struct {
	PipelineRunID int64
	SourceName    string
	FilterData    string
}

func (q *Queries) UpsertSourceFilterCount(ctx context.Context, arg UpsertSourceFilterCountParams) error {
	_, err := q.db.ExecContext(ctx, upsertSourceFilterCount, arg.PipelineRunID, arg.SourceName, arg.FilterData)
	return err
}
