// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sql

import (
	"database/sql"
)

type RunSource struct {
	ID                    int64
	PipelineRunID         int64
	SourceName            string
	SourceType            string
	ExpectedFile          string
	Query                 sql.NullString
	RequestedFields       sql.NullString
	ExpectedResultCount   sql.NullInt64
	ObservedResultCount   sql.NullInt64
	ResultCountComparison sql.NullString
	ExportDate            sql.NullString
	CreatedAt             string
}

type SourceFilterCount struct {
	ID            int64
	PipelineRunID int64
	SourceName    string
	FilterData    string
}

type SourceRecord struct {
	ID           int64
	RunSourceID  int64
	RecordIndex  int64
	RawPayload   string
	ContentHash  string
	ParseStatus  string
	RejectReason sql.NullString
	CreatedAt    string
}
