// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: record.sql

package sql

import (
	"context"
	"database/sql"
)

const countSourceRecordsBySource = `-- name: CountSourceRecordsBySource :one
SELECT COUNT(*)
FROM source_records
WHERE run_source_id = ?1
`

func (q *Queries) CountSourceRecordsBySource(ctx context.Context, runSourceID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSourceRecordsBySource, runSourceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertSourceRecord = `-- name: InsertSourceRecord :execresult
INSERT INTO source_records (
    run_source_id,
    record_index,
    raw_payload,
    content_hash
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4
)
`

type InsertSourceRecordParams struct {
	RunSourceID int64
	RecordIndex int64
	RawPayload  string
	ContentHash string
}

func (q *Queries) InsertSourceRecord(ctx context.Context, arg InsertSourceRecordParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertSourceRecord,
		arg.RunSourceID,
		arg.RecordIndex,
		arg.RawPayload,
		arg.ContentHash,
	)
}

const listSourceRecordsBySource = `-- name: ListSourceRecordsBySource :many
SELECT
    id,
    run_source_id,
    record_index,
    raw_payload,
    content_hash,
    parse_status,
    reject_reason,
    created_at
FROM source_records
WHERE run_source_id = ?1
ORDER BY record_index
`

func (q *Queries) ListSourceRecordsBySource(ctx context.Context, runSourceID int64) ([]SourceRecord, error) {
	rows, err := q.db.QueryContext(ctx, listSourceRecordsBySource, runSourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SourceRecord
	for rows.Next() {
		var i SourceRecord
		if err := rows.Scan(
			&i.ID,
			&i.RunSourceID,
			&i.RecordIndex,
			&i.RawPayload,
			&i.ContentHash,
			&i.ParseStatus,
			&i.RejectReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSourceRecordParseStatus = `-- name: UpdateSourceRecordParseStatus :exec
UPDATE source_records
SET
    parse_status = ?1,
    reject_reason = ?2
WHERE id = ?3
`

type UpdateSourceRecordParseStatusParams struct {
	ParseStatus  string
	RejectReason sql.NullString
	ID           int64
}

func (q *Queries) UpdateSourceRecordParseStatus(ctx context.Context, arg UpdateSourceRecordParseStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSourceRecordParseStatus, arg.ParseStatus, arg.RejectReason, arg.ID)
	return err
}
