// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: source.sql

package sql

import (
	"context"
	"database/sql"
)

const insertRunSource = `-- name: InsertRunSource :execresult
INSERT INTO run_sources (
    pipeline_run_id,
    source_name,
    source_type,
    expected_file,
    query,
    requested_fields,
    expected_result_count,
    export_date
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8
)
`

type InsertRunSourceParams struct {
	PipelineRunID       int64
	SourceName          string
	SourceType          string
	ExpectedFile        string
	Query               sql.NullString
	RequestedFields     sql.NullString
	ExpectedResultCount sql.NullInt64
	ExportDate          sql.NullString
}

func (q *Queries) InsertRunSource(ctx context.Context, arg InsertRunSourceParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertRunSource,
		arg.PipelineRunID,
		arg.SourceName,
		arg.SourceType,
		arg.ExpectedFile,
		arg.Query,
		arg.RequestedFields,
		arg.ExpectedResultCount,
		arg.ExportDate,
	)
}

const listRunSourcesByRun = `-- name: ListRunSourcesByRun :many
SELECT
    id,
    pipeline_run_id,
    source_name,
    source_type,
    expected_file,
    query,
    requested_fields,
    expected_result_count,
    observed_result_count,
    result_count_comparison,
    export_date,
    created_at
FROM run_sources
WHERE pipeline_run_id = ?1
ORDER BY id
`

func (q *Queries) ListRunSourcesByRun(ctx context.Context, pipelineRunID int64) ([]RunSource, error) {
	rows, err := q.db.QueryContext(ctx, listRunSourcesByRun, pipelineRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunSource
	for rows.Next() {
		var i RunSource
		if err := rows.Scan(
			&i.ID,
			&i.PipelineRunID,
			&i.SourceName,
			&i.SourceType,
			&i.ExpectedFile,
			&i.Query,
			&i.RequestedFields,
			&i.ExpectedResultCount,
			&i.ObservedResultCount,
			&i.ResultCountComparison,
			&i.ExportDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRunSourceObservedResultCount = `-- name: SetRunSourceObservedResultCount :exec
UPDATE run_sources
SET
    observed_result_count = ?1,
    result_count_comparison = ?2
WHERE id = ?3
`

type SetRunSourceObservedResultCountParams struct {
	ObservedResultCount   sql.NullInt64
	ResultCountComparison sql.NullString
	ID                    int64
}

func (q *Queries) SetRunSourceObservedResultCount(ctx context.Context, arg SetRunSourceObservedResultCountParams) error {
	_, err := q.db.ExecContext(ctx, setRunSourceObservedResultCount, arg.ObservedResultCount, arg.ResultCountComparison, arg.ID)
	return err
}
