// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: viewer.sql

package sql

import (
	"context"
	"database/sql"
)

const listResultCountsForRun = `-- name: ListResultCountsForRun :many

SELECT
    id,
    source_name,
    source_type,
    expected_file,
    query,
    expected_result_count,
    observed_result_count,
    result_count_comparison,
    export_date
FROM run_sources
WHERE pipeline_run_id = ?1
ORDER BY id
`

type ListResultCountsForRunRow struct {
	ID                    int64
	SourceName            string
	SourceType            string
	ExpectedFile          string
	Query                 sql.NullString
	ExpectedResultCount   sql.NullInt64
	ObservedResultCount   sql.NullInt64
	ResultCountComparison sql.NullString
	ExportDate            sql.NullString
}

// viewer.sql holds the source family's viewer result-count projections.
// The four named variants are the finite schema-compatibility set: older
// databases may lack the export_date and result-count columns, so each
// combination projects the absent columns as NULL instead of failing.
func (q *Queries) ListResultCountsForRun(ctx context.Context, pipelineRunID int64) ([]ListResultCountsForRunRow, error) {
	rows, err := q.db.QueryContext(ctx, listResultCountsForRun, pipelineRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListResultCountsForRunRow
	for rows.Next() {
		var i ListResultCountsForRunRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceName,
			&i.SourceType,
			&i.ExpectedFile,
			&i.Query,
			&i.ExpectedResultCount,
			&i.ObservedResultCount,
			&i.ResultCountComparison,
			&i.ExportDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResultCountsForRunWithoutExportDate = `-- name: ListResultCountsForRunWithoutExportDate :many
SELECT
    id,
    source_name,
    source_type,
    expected_file,
    query,
    expected_result_count,
    observed_result_count,
    result_count_comparison,
    CAST(NULL AS TEXT) AS export_date
FROM run_sources
WHERE pipeline_run_id = ?1
ORDER BY id
`

type ListResultCountsForRunWithoutExportDateRow struct {
	ID                    int64
	SourceName            string
	SourceType            string
	ExpectedFile          string
	Query                 sql.NullString
	ExpectedResultCount   sql.NullInt64
	ObservedResultCount   sql.NullInt64
	ResultCountComparison sql.NullString
	ExportDate            sql.NullString
}

func (q *Queries) ListResultCountsForRunWithoutExportDate(ctx context.Context, pipelineRunID int64) ([]ListResultCountsForRunWithoutExportDateRow, error) {
	rows, err := q.db.QueryContext(ctx, listResultCountsForRunWithoutExportDate, pipelineRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListResultCountsForRunWithoutExportDateRow
	for rows.Next() {
		var i ListResultCountsForRunWithoutExportDateRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceName,
			&i.SourceType,
			&i.ExpectedFile,
			&i.Query,
			&i.ExpectedResultCount,
			&i.ObservedResultCount,
			&i.ResultCountComparison,
			&i.ExportDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResultCountsForRunWithoutResultCounts = `-- name: ListResultCountsForRunWithoutResultCounts :many
SELECT
    id,
    source_name,
    source_type,
    expected_file,
    query,
    CAST(NULL AS INTEGER) AS expected_result_count,
    CAST(NULL AS INTEGER) AS observed_result_count,
    CAST(NULL AS TEXT) AS result_count_comparison,
    export_date
FROM run_sources
WHERE pipeline_run_id = ?1
ORDER BY id
`

type ListResultCountsForRunWithoutResultCountsRow struct {
	ID                    int64
	SourceName            string
	SourceType            string
	ExpectedFile          string
	Query                 sql.NullString
	ExpectedResultCount   sql.NullInt64
	ObservedResultCount   sql.NullInt64
	ResultCountComparison sql.NullString
	ExportDate            sql.NullString
}

func (q *Queries) ListResultCountsForRunWithoutResultCounts(ctx context.Context, pipelineRunID int64) ([]ListResultCountsForRunWithoutResultCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listResultCountsForRunWithoutResultCounts, pipelineRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListResultCountsForRunWithoutResultCountsRow
	for rows.Next() {
		var i ListResultCountsForRunWithoutResultCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceName,
			&i.SourceType,
			&i.ExpectedFile,
			&i.Query,
			&i.ExpectedResultCount,
			&i.ObservedResultCount,
			&i.ResultCountComparison,
			&i.ExportDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResultCountsForRunWithoutResultCountsAndExportDate = `-- name: ListResultCountsForRunWithoutResultCountsAndExportDate :many
SELECT
    id,
    source_name,
    source_type,
    expected_file,
    query,
    CAST(NULL AS INTEGER) AS expected_result_count,
    CAST(NULL AS INTEGER) AS observed_result_count,
    CAST(NULL AS TEXT) AS result_count_comparison,
    CAST(NULL AS TEXT) AS export_date
FROM run_sources
WHERE pipeline_run_id = ?1
ORDER BY id
`

type ListResultCountsForRunWithoutResultCountsAndExportDateRow struct {
	ID                    int64
	SourceName            string
	SourceType            string
	ExpectedFile          string
	Query                 sql.NullString
	ExpectedResultCount   sql.NullInt64
	ObservedResultCount   sql.NullInt64
	ResultCountComparison sql.NullString
	ExportDate            sql.NullString
}

func (q *Queries) ListResultCountsForRunWithoutResultCountsAndExportDate(ctx context.Context, pipelineRunID int64) ([]ListResultCountsForRunWithoutResultCountsAndExportDateRow, error) {
	rows, err := q.db.QueryContext(ctx, listResultCountsForRunWithoutResultCountsAndExportDate, pipelineRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListResultCountsForRunWithoutResultCountsAndExportDateRow
	for rows.Next() {
		var i ListResultCountsForRunWithoutResultCountsAndExportDateRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceName,
			&i.SourceType,
			&i.ExpectedFile,
			&i.Query,
			&i.ExpectedResultCount,
			&i.ObservedResultCount,
			&i.ResultCountComparison,
			&i.ExportDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
