// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authorship.sql

package sql

import (
	"context"
	"database/sql"
)

const countArticleAuthors = `-- name: CountArticleAuthors :one
SELECT COUNT(*) FROM authorships
WHERE work_revision_id = ?1
`

func (q *Queries) CountArticleAuthors(ctx context.Context, workRevisionID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countArticleAuthors, workRevisionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listArticleAuthors = `-- name: ListArticleAuthors :many
SELECT
    a.id AS relation_id,
    ao.id,
    ao.person_id,
    ao.citation_name,
    ao.first_name,
    ao.last_name,
    ao.orcid,
    a.author_order,
    a.affiliation
FROM authorships a
JOIN author_occurrences ao ON ao.id = a.author_occurrence_id
WHERE a.work_revision_id = ?1
  AND a.id > ?2
ORDER BY a.id
LIMIT ?3
`

type ListArticleAuthorsParams struct {
	WorkRevisionID int64
	CursorID       int64
	RowLimit       int64
}

type ListArticleAuthorsRow struct {
	RelationID   int64
	ID           int64
	PersonID     sql.NullInt64
	CitationName string
	FirstName    sql.NullString
	LastName     sql.NullString
	Orcid        sql.NullString
	AuthorOrder  int64
	Affiliation  sql.NullString
}

func (q *Queries) ListArticleAuthors(ctx context.Context, arg ListArticleAuthorsParams) ([]ListArticleAuthorsRow, error) {
	rows, err := q.db.QueryContext(ctx, listArticleAuthors, arg.WorkRevisionID, arg.CursorID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArticleAuthorsRow
	for rows.Next() {
		var i ListArticleAuthorsRow
		if err := rows.Scan(
			&i.RelationID,
			&i.ID,
			&i.PersonID,
			&i.CitationName,
			&i.FirstName,
			&i.LastName,
			&i.Orcid,
			&i.AuthorOrder,
			&i.Affiliation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
