// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: corpus.sql

package sql

import (
	"context"
)

const countRunAnalysisReadyArticles = `-- name: CountRunAnalysisReadyArticles :one
SELECT COUNT(*) FROM work_revisions wr
WHERE wr.pipeline_run_id = ?1
  AND wr.producer_stage = 'normalize'
  AND wr.id = (SELECT MAX(normalized_candidate.id) FROM work_revisions normalized_candidate
      WHERE normalized_candidate.pipeline_run_id = wr.pipeline_run_id
        AND normalized_candidate.work_id = wr.work_id
        AND normalized_candidate.producer_stage = 'normalize')
  AND EXISTS (SELECT 1 FROM run_work_stages current_validation
      WHERE current_validation.pipeline_run_id = wr.pipeline_run_id
        AND current_validation.work_id = wr.work_id
        AND current_validation.stage_name = 'validate'
        AND current_validation.outcome = 'valid')
`

func (q *Queries) CountRunAnalysisReadyArticles(ctx context.Context, pipelineRunID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRunAnalysisReadyArticles, pipelineRunID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRunAuthorships = `-- name: CountRunAuthorships :one
SELECT COUNT(*) FROM authorships a
JOIN work_revisions wr ON wr.id = a.work_revision_id
WHERE wr.pipeline_run_id = ?1
  AND wr.producer_stage = 'normalize'
  AND wr.id = (SELECT MAX(normalized_candidate.id) FROM work_revisions normalized_candidate
      WHERE normalized_candidate.pipeline_run_id = wr.pipeline_run_id
        AND normalized_candidate.work_id = wr.work_id
        AND normalized_candidate.producer_stage = 'normalize')
  AND EXISTS (SELECT 1 FROM run_work_stages current_validation
      WHERE current_validation.pipeline_run_id = wr.pipeline_run_id
        AND current_validation.work_id = wr.work_id
        AND current_validation.stage_name = 'validate'
        AND current_validation.outcome = 'valid')
`

func (q *Queries) CountRunAuthorships(ctx context.Context, pipelineRunID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRunAuthorships, pipelineRunID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRunInternalCitations = `-- name: CountRunInternalCitations :one
SELECT COUNT(*) FROM reference_mentions rm
JOIN work_revisions wr ON wr.id = rm.work_revision_id
WHERE wr.pipeline_run_id = ?1
  AND rm.resolved_work_id IS NOT NULL
  AND wr.producer_stage = 'normalize'
  AND wr.id = (SELECT MAX(normalized_candidate.id) FROM work_revisions normalized_candidate
      WHERE normalized_candidate.pipeline_run_id = wr.pipeline_run_id
        AND normalized_candidate.work_id = wr.work_id
        AND normalized_candidate.producer_stage = 'normalize')
  AND EXISTS (SELECT 1 FROM run_work_stages current_validation
      WHERE current_validation.pipeline_run_id = wr.pipeline_run_id
        AND current_validation.work_id = wr.work_id
        AND current_validation.stage_name = 'validate'
        AND current_validation.outcome = 'valid')
`

func (q *Queries) CountRunInternalCitations(ctx context.Context, pipelineRunID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRunInternalCitations, pipelineRunID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRunReferenceMentions = `-- name: CountRunReferenceMentions :one
SELECT COUNT(*) FROM reference_mentions rm
JOIN work_revisions wr ON wr.id = rm.work_revision_id
WHERE wr.pipeline_run_id = ?1
  AND wr.producer_stage = 'normalize'
  AND wr.id = (SELECT MAX(normalized_candidate.id) FROM work_revisions normalized_candidate
      WHERE normalized_candidate.pipeline_run_id = wr.pipeline_run_id
        AND normalized_candidate.work_id = wr.work_id
        AND normalized_candidate.producer_stage = 'normalize')
  AND EXISTS (SELECT 1 FROM run_work_stages current_validation
      WHERE current_validation.pipeline_run_id = wr.pipeline_run_id
        AND current_validation.work_id = wr.work_id
        AND current_validation.stage_name = 'validate'
        AND current_validation.outcome = 'valid')
`

func (q *Queries) CountRunReferenceMentions(ctx context.Context, pipelineRunID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRunReferenceMentions, pipelineRunID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRunWorkRevisions = `-- name: CountRunWorkRevisions :one
SELECT COUNT(*) FROM work_revisions
WHERE pipeline_run_id = ?1
`

func (q *Queries) CountRunWorkRevisions(ctx context.Context, pipelineRunID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRunWorkRevisions, pipelineRunID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const currentCoverage = `-- name: CurrentCoverage :one
SELECT
    COUNT(*),
    CAST(COALESCE(SUM(CASE WHEN journal IS NOT NULL AND journal != '' THEN 1 ELSE 0 END), 0) AS INTEGER)
FROM work_revisions
WHERE pipeline_run_id = ?1
`

type CurrentCoverageRow struct {
	Count   int64
	Column2 int64
}

func (q *Queries) CurrentCoverage(ctx context.Context, pipelineRunID int64) (CurrentCoverageRow, error) {
	row := q.db.QueryRowContext(ctx, currentCoverage, pipelineRunID)
	var i CurrentCoverageRow
	err := row.Scan(&i.Count, &i.Column2)
	return i, err
}

const runStageSummaries = `-- name: RunStageSummaries :many
SELECT
    stage_name,
    outcome,
    COUNT(*) AS count,
    CAST(MIN(created_at) AS TEXT) AS first_recorded_at,
    CAST(MAX(updated_at) AS TEXT) AS last_recorded_at
FROM run_work_stages
WHERE pipeline_run_id = ?1
GROUP BY stage_name, outcome
ORDER BY stage_name, outcome
`

type RunStageSummariesRow struct {
	StageName       string
	Outcome         string
	Count           int64
	FirstRecordedAt string
	LastRecordedAt  string
}

func (q *Queries) RunStageSummaries(ctx context.Context, pipelineRunID int64) ([]RunStageSummariesRow, error) {
	rows, err := q.db.QueryContext(ctx, runStageSummaries, pipelineRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunStageSummariesRow
	for rows.Next() {
		var i RunStageSummariesRow
		if err := rows.Scan(
			&i.StageName,
			&i.Outcome,
			&i.Count,
			&i.FirstRecordedAt,
			&i.LastRecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
