// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: details.sql

package sql

import (
	"context"
	"database/sql"
)

const countArticleReferences = `-- name: CountArticleReferences :one
SELECT COUNT(*) FROM reference_mentions
WHERE work_revision_id = ?1
`

func (q *Queries) CountArticleReferences(ctx context.Context, workRevisionID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countArticleReferences, workRevisionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countArticleStages = `-- name: CountArticleStages :one
SELECT COUNT(*) FROM run_work_stages
WHERE pipeline_run_id = ?1
  AND work_id = ?2
`

type CountArticleStagesParams struct {
	PipelineRunID int64
	WorkID        int64
}

func (q *Queries) CountArticleStages(ctx context.Context, arg CountArticleStagesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countArticleStages, arg.PipelineRunID, arg.WorkID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAuthorArticles = `-- name: CountAuthorArticles :one
SELECT COUNT(*) FROM authorships a
JOIN work_revisions wr ON wr.id=a.work_revision_id
WHERE a.author_occurrence_id = ?1
  AND wr.pipeline_run_id = ?2
`

type CountAuthorArticlesParams struct {
	AuthorOccurrenceID int64
	PipelineRunID      int64
}

func (q *Queries) CountAuthorArticles(ctx context.Context, arg CountAuthorArticlesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuthorArticles, arg.AuthorOccurrenceID, arg.PipelineRunID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getArticleDetailWorkID = `-- name: GetArticleDetailWorkID :one
SELECT wr.work_id
FROM work_revisions wr
WHERE wr.id = ?1
  AND wr.pipeline_run_id = ?2
  AND (wr.producer_stage != 'normalize' OR (
      wr.producer_stage = 'normalize'
      AND wr.id = (SELECT MAX(normalized_candidate.id) FROM work_revisions normalized_candidate
          WHERE normalized_candidate.pipeline_run_id = wr.pipeline_run_id
            AND normalized_candidate.work_id = wr.work_id
            AND normalized_candidate.producer_stage = 'normalize')
      AND EXISTS (SELECT 1 FROM run_work_stages current_validation
          WHERE current_validation.pipeline_run_id = wr.pipeline_run_id
            AND current_validation.work_id = wr.work_id
            AND current_validation.stage_name = 'validate'
            AND current_validation.outcome = 'valid')))
`

type GetArticleDetailWorkIDParams struct {
	ID            int64
	PipelineRunID int64
}

func (q *Queries) GetArticleDetailWorkID(ctx context.Context, arg GetArticleDetailWorkIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getArticleDetailWorkID, arg.ID, arg.PipelineRunID)
	var work_id int64
	err := row.Scan(&work_id)
	return work_id, err
}

const getArticleRevision = `-- name: GetArticleRevision :one
SELECT
    wr.id,
    wr.work_id,
    wr.pipeline_run_id,
    wr.field_schema_version,
    wr.payload_hash,
    wr.title,
    wr.abstract,
    wr.year,
    wr.journal,
    wr.publisher,
    wr.source,
    wr.keywords,
    wr.keywords_plus,
    wr.citation_count,
    wr.reference_count,
    wr.extension_data,
    wr.producer_stage,
    wr.created_at,
    w.doi
FROM work_revisions wr
JOIN works w ON w.id = wr.work_id
WHERE wr.id = ?1
  AND wr.pipeline_run_id = ?2
  AND (wr.producer_stage != 'normalize' OR (
      wr.producer_stage = 'normalize'
      AND wr.id = (SELECT MAX(normalized_candidate.id) FROM work_revisions normalized_candidate
          WHERE normalized_candidate.pipeline_run_id = wr.pipeline_run_id
            AND normalized_candidate.work_id = wr.work_id
            AND normalized_candidate.producer_stage = 'normalize')
      AND EXISTS (SELECT 1 FROM run_work_stages current_validation
          WHERE current_validation.pipeline_run_id = wr.pipeline_run_id
            AND current_validation.work_id = wr.work_id
            AND current_validation.stage_name = 'validate'
            AND current_validation.outcome = 'valid')))
`

type GetArticleRevisionParams struct {
	ID            int64
	PipelineRunID int64
}

type GetArticleRevisionRow struct {
	ID                 int64
	WorkID             int64
	PipelineRunID      int64
	FieldSchemaVersion string
	PayloadHash        string
	Title              sql.NullString
	Abstract           sql.NullString
	Year               sql.NullInt64
	Journal            sql.NullString
	Publisher          sql.NullString
	Source             sql.NullString
	Keywords           sql.NullString
	KeywordsPlus       sql.NullString
	CitationCount      sql.NullInt64
	ReferenceCount     sql.NullInt64
	ExtensionData      sql.NullString
	ProducerStage      string
	CreatedAt          string
	Doi                sql.NullString
}

func (q *Queries) GetArticleRevision(ctx context.Context, arg GetArticleRevisionParams) (GetArticleRevisionRow, error) {
	row := q.db.QueryRowContext(ctx, getArticleRevision, arg.ID, arg.PipelineRunID)
	var i GetArticleRevisionRow
	err := row.Scan(
		&i.ID,
		&i.WorkID,
		&i.PipelineRunID,
		&i.FieldSchemaVersion,
		&i.PayloadHash,
		&i.Title,
		&i.Abstract,
		&i.Year,
		&i.Journal,
		&i.Publisher,
		&i.Source,
		&i.Keywords,
		&i.KeywordsPlus,
		&i.CitationCount,
		&i.ReferenceCount,
		&i.ExtensionData,
		&i.ProducerStage,
		&i.CreatedAt,
		&i.Doi,
	)
	return i, err
}

const getReferenceDetail = `-- name: GetReferenceDetail :one
SELECT
    rm.id,
    rm.work_revision_id,
    rm.resolved_work_id,
    rm.mention_order,
    rm.raw_reference,
    rm.doi,
    rm.title,
    rm.author,
    rm.year,
    rm.source,
    rm.created_at,
    wr.work_id,
    wr.title AS citing_title,
    wr.pipeline_run_id,
    target.id AS resolved_revision_id,
    target.title AS resolved_title
FROM reference_mentions rm
JOIN work_revisions wr ON wr.id = rm.work_revision_id
LEFT JOIN work_revisions target ON target.id = (
    SELECT candidate.id FROM work_revisions candidate
    WHERE candidate.work_id = rm.resolved_work_id
      AND candidate.pipeline_run_id = wr.pipeline_run_id
      AND candidate.producer_stage = 'normalize'
      AND candidate.id = (SELECT MAX(normalized_candidate.id) FROM work_revisions normalized_candidate
          WHERE normalized_candidate.pipeline_run_id = candidate.pipeline_run_id
            AND normalized_candidate.work_id = candidate.work_id
            AND normalized_candidate.producer_stage = 'normalize')
      AND EXISTS (SELECT 1 FROM run_work_stages current_validation
          WHERE current_validation.pipeline_run_id = candidate.pipeline_run_id
            AND current_validation.work_id = candidate.work_id
            AND current_validation.stage_name = 'validate'
            AND current_validation.outcome = 'valid')
    LIMIT 1)
WHERE rm.id = ?1
  AND wr.pipeline_run_id = ?2
`

type GetReferenceDetailParams struct {
	ID            int64
	PipelineRunID int64
}

type GetReferenceDetailRow struct {
	ID                 int64
	WorkRevisionID     int64
	ResolvedWorkID     sql.NullInt64
	MentionOrder       int64
	RawReference       sql.NullString
	Doi                sql.NullString
	Title              sql.NullString
	Author             sql.NullString
	Year               sql.NullInt64
	Source             sql.NullString
	CreatedAt          string
	WorkID             int64
	CitingTitle        sql.NullString
	PipelineRunID      int64
	ResolvedRevisionID sql.NullInt64
	ResolvedTitle      sql.NullString
}

func (q *Queries) GetReferenceDetail(ctx context.Context, arg GetReferenceDetailParams) (GetReferenceDetailRow, error) {
	row := q.db.QueryRowContext(ctx, getReferenceDetail, arg.ID, arg.PipelineRunID)
	var i GetReferenceDetailRow
	err := row.Scan(
		&i.ID,
		&i.WorkRevisionID,
		&i.ResolvedWorkID,
		&i.MentionOrder,
		&i.RawReference,
		&i.Doi,
		&i.Title,
		&i.Author,
		&i.Year,
		&i.Source,
		&i.CreatedAt,
		&i.WorkID,
		&i.CitingTitle,
		&i.PipelineRunID,
		&i.ResolvedRevisionID,
		&i.ResolvedTitle,
	)
	return i, err
}

const listArticleReferences = `-- name: ListArticleReferences :many
SELECT
    rm.id,
    rm.work_revision_id,
    rm.resolved_work_id,
    rm.mention_order,
    rm.doi,
    rm.title,
    rm.author,
    rm.year,
    rm.source,
    rm.created_at,
    target.id AS resolved_revision_id,
    target.title AS resolved_title
FROM reference_mentions rm
JOIN work_revisions source ON source.id = rm.work_revision_id
LEFT JOIN work_revisions target ON target.id = (
    SELECT candidate.id FROM work_revisions candidate
    WHERE candidate.work_id = rm.resolved_work_id
      AND candidate.pipeline_run_id = source.pipeline_run_id
      AND candidate.producer_stage = 'normalize'
      AND candidate.id = (SELECT MAX(normalized_candidate.id) FROM work_revisions normalized_candidate
          WHERE normalized_candidate.pipeline_run_id = candidate.pipeline_run_id
            AND normalized_candidate.work_id = candidate.work_id
            AND normalized_candidate.producer_stage = 'normalize')
      AND EXISTS (SELECT 1 FROM run_work_stages current_validation
          WHERE current_validation.pipeline_run_id = candidate.pipeline_run_id
            AND current_validation.work_id = candidate.work_id
            AND current_validation.stage_name = 'validate'
            AND current_validation.outcome = 'valid')
    LIMIT 1)
WHERE rm.work_revision_id = ?1
  AND rm.id > ?2
ORDER BY rm.id
LIMIT ?3
`

type ListArticleReferencesParams struct {
	WorkRevisionID int64
	CursorID       int64
	RowLimit       int64
}

type ListArticleReferencesRow struct {
	ID                 int64
	WorkRevisionID     int64
	ResolvedWorkID     sql.NullInt64
	MentionOrder       int64
	Doi                sql.NullString
	Title              sql.NullString
	Author             sql.NullString
	Year               sql.NullInt64
	Source             sql.NullString
	CreatedAt          string
	ResolvedRevisionID sql.NullInt64
	ResolvedTitle      sql.NullString
}

func (q *Queries) ListArticleReferences(ctx context.Context, arg ListArticleReferencesParams) ([]ListArticleReferencesRow, error) {
	rows, err := q.db.QueryContext(ctx, listArticleReferences, arg.WorkRevisionID, arg.CursorID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArticleReferencesRow
	for rows.Next() {
		var i ListArticleReferencesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkRevisionID,
			&i.ResolvedWorkID,
			&i.MentionOrder,
			&i.Doi,
			&i.Title,
			&i.Author,
			&i.Year,
			&i.Source,
			&i.CreatedAt,
			&i.ResolvedRevisionID,
			&i.ResolvedTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticleStages = `-- name: ListArticleStages :many
SELECT
    id,
    pipeline_run_id,
    work_id,
    stage_name,
    outcome,
    reason,
    created_at,
    updated_at
FROM run_work_stages
WHERE pipeline_run_id = ?1
  AND work_id = ?2
  AND id > ?3
ORDER BY id
LIMIT ?4
`

type ListArticleStagesParams struct {
	PipelineRunID int64
	WorkID        int64
	CursorID      int64
	RowLimit      int64
}

func (q *Queries) ListArticleStages(ctx context.Context, arg ListArticleStagesParams) ([]RunWorkStage, error) {
	rows, err := q.db.QueryContext(ctx, listArticleStages,
		arg.PipelineRunID,
		arg.WorkID,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunWorkStage
	for rows.Next() {
		var i RunWorkStage
		if err := rows.Scan(
			&i.ID,
			&i.PipelineRunID,
			&i.WorkID,
			&i.StageName,
			&i.Outcome,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthorArticles = `-- name: ListAuthorArticles :many
SELECT
    a.id AS relation_id,
    a.author_order,
    a.affiliation,
    wr.id AS work_revision_id,
    wr.work_id,
    wr.title,
    wr.year,
    wr.pipeline_run_id,
    w.doi
FROM authorships a
JOIN work_revisions wr ON wr.id=a.work_revision_id
JOIN works w ON w.id=wr.work_id
WHERE a.author_occurrence_id = ?1
  AND wr.pipeline_run_id = ?2
  AND a.id > ?3
ORDER BY a.id
LIMIT ?4
`

type ListAuthorArticlesParams struct {
	AuthorOccurrenceID int64
	PipelineRunID      int64
	CursorID           int64
	RowLimit           int64
}

type ListAuthorArticlesRow struct {
	RelationID     int64
	AuthorOrder    int64
	Affiliation    sql.NullString
	WorkRevisionID int64
	WorkID         int64
	Title          sql.NullString
	Year           sql.NullInt64
	PipelineRunID  int64
	Doi            sql.NullString
}

func (q *Queries) ListAuthorArticles(ctx context.Context, arg ListAuthorArticlesParams) ([]ListAuthorArticlesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuthorArticles,
		arg.AuthorOccurrenceID,
		arg.PipelineRunID,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuthorArticlesRow
	for rows.Next() {
		var i ListAuthorArticlesRow
		if err := rows.Scan(
			&i.RelationID,
			&i.AuthorOrder,
			&i.Affiliation,
			&i.WorkRevisionID,
			&i.WorkID,
			&i.Title,
			&i.Year,
			&i.PipelineRunID,
			&i.Doi,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
