// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sql

import (
	"database/sql"
)

type ReferenceMention struct {
	ID             int64
	WorkRevisionID int64
	ResolvedWorkID sql.NullInt64
	MentionOrder   int64
	RawReference   sql.NullString
	Doi            sql.NullString
	Title          sql.NullString
	Author         sql.NullString
	Year           sql.NullInt64
	Source         sql.NullString
	CreatedAt      string
}

type RunSearchTerm struct {
	ID            int64
	PipelineRunID int64
	SourceName    string
	Term          string
	CreatedAt     string
}

type RunWorkStage struct {
	ID            int64
	PipelineRunID int64
	WorkID        int64
	StageName     string
	Outcome       string
	Reason        sql.NullString
	CreatedAt     string
	UpdatedAt     string
}

type Work struct {
	ID        int64
	Doi       sql.NullString
	CreatedAt string
}

type WorkIdentifier struct {
	ID         int64
	WorkID     int64
	Namespace  string
	Identifier string
	CreatedAt  string
}

type WorkRevision struct {
	ID                 int64
	WorkID             int64
	PipelineRunID      int64
	FieldSchemaVersion string
	PayloadHash        string
	Title              sql.NullString
	Abstract           sql.NullString
	Year               sql.NullInt64
	Journal            sql.NullString
	Publisher          sql.NullString
	Source             sql.NullString
	Keywords           sql.NullString
	KeywordsPlus       sql.NullString
	CitationCount      sql.NullInt64
	ReferenceCount     sql.NullInt64
	ExtensionData      sql.NullString
	ProducerStage      string
	CreatedAt          string
}
