// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reference.sql

package sql

import (
	"context"
	"database/sql"
)

const getReferenceMentionByID = `-- name: GetReferenceMentionByID :one
SELECT
    id,
    work_revision_id,
    resolved_work_id,
    mention_order,
    raw_reference,
    doi,
    title,
    author,
    year,
    source,
    created_at
FROM reference_mentions
WHERE id = ?1
`

func (q *Queries) GetReferenceMentionByID(ctx context.Context, id int64) (ReferenceMention, error) {
	row := q.db.QueryRowContext(ctx, getReferenceMentionByID, id)
	var i ReferenceMention
	err := row.Scan(
		&i.ID,
		&i.WorkRevisionID,
		&i.ResolvedWorkID,
		&i.MentionOrder,
		&i.RawReference,
		&i.Doi,
		&i.Title,
		&i.Author,
		&i.Year,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const insertReferenceMention = `-- name: InsertReferenceMention :execresult
INSERT INTO reference_mentions (
    work_revision_id,
    resolved_work_id,
    mention_order,
    raw_reference,
    doi,
    title,
    author,
    year,
    source
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9
)
`

type InsertReferenceMentionParams struct {
	WorkRevisionID int64
	ResolvedWorkID sql.NullInt64
	MentionOrder   int64
	RawReference   sql.NullString
	Doi            sql.NullString
	Title          sql.NullString
	Author         sql.NullString
	Year           sql.NullInt64
	Source         sql.NullString
}

func (q *Queries) InsertReferenceMention(ctx context.Context, arg InsertReferenceMentionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertReferenceMention,
		arg.WorkRevisionID,
		arg.ResolvedWorkID,
		arg.MentionOrder,
		arg.RawReference,
		arg.Doi,
		arg.Title,
		arg.Author,
		arg.Year,
		arg.Source,
	)
}

const listReferenceMentionsByResolvedWorkID = `-- name: ListReferenceMentionsByResolvedWorkID :many
SELECT
    id,
    work_revision_id,
    resolved_work_id,
    mention_order,
    raw_reference,
    doi,
    title,
    author,
    year,
    source,
    created_at
FROM reference_mentions
WHERE resolved_work_id = ?1
ORDER BY id
`

func (q *Queries) ListReferenceMentionsByResolvedWorkID(ctx context.Context, resolvedWorkID sql.NullInt64) ([]ReferenceMention, error) {
	rows, err := q.db.QueryContext(ctx, listReferenceMentionsByResolvedWorkID, resolvedWorkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReferenceMention
	for rows.Next() {
		var i ReferenceMention
		if err := rows.Scan(
			&i.ID,
			&i.WorkRevisionID,
			&i.ResolvedWorkID,
			&i.MentionOrder,
			&i.RawReference,
			&i.Doi,
			&i.Title,
			&i.Author,
			&i.Year,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReferenceMentionsByRevisionID = `-- name: ListReferenceMentionsByRevisionID :many
SELECT
    id,
    work_revision_id,
    resolved_work_id,
    mention_order,
    raw_reference,
    doi,
    title,
    author,
    year,
    source,
    created_at
FROM reference_mentions
WHERE work_revision_id = ?1
ORDER BY mention_order, id
`

func (q *Queries) ListReferenceMentionsByRevisionID(ctx context.Context, workRevisionID int64) ([]ReferenceMention, error) {
	rows, err := q.db.QueryContext(ctx, listReferenceMentionsByRevisionID, workRevisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReferenceMention
	for rows.Next() {
		var i ReferenceMention
		if err := rows.Scan(
			&i.ID,
			&i.WorkRevisionID,
			&i.ResolvedWorkID,
			&i.MentionOrder,
			&i.RawReference,
			&i.Doi,
			&i.Title,
			&i.Author,
			&i.Year,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
