// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: revision.sql

package sql

import (
	"context"
	"database/sql"
)

const countCurrentNormalizedRevisionsByWork = `-- name: CountCurrentNormalizedRevisionsByWork :one
SELECT COUNT(*) FROM work_revisions wr
WHERE wr.pipeline_run_id = ?1
  AND wr.work_id = ?2
  AND wr.producer_stage = 'normalize'
  AND wr.id = (SELECT MAX(normalized_candidate.id) FROM work_revisions normalized_candidate
      WHERE normalized_candidate.pipeline_run_id = wr.pipeline_run_id
        AND normalized_candidate.work_id = wr.work_id
        AND normalized_candidate.producer_stage = 'normalize')
  AND EXISTS (SELECT 1 FROM run_work_stages current_validation
      WHERE current_validation.pipeline_run_id = wr.pipeline_run_id
        AND current_validation.work_id = wr.work_id
        AND current_validation.stage_name = 'validate'
        AND current_validation.outcome = 'valid')
`

type CountCurrentNormalizedRevisionsByWorkParams struct {
	PipelineRunID int64
	WorkID        int64
}

func (q *Queries) CountCurrentNormalizedRevisionsByWork(ctx context.Context, arg CountCurrentNormalizedRevisionsByWorkParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCurrentNormalizedRevisionsByWork, arg.PipelineRunID, arg.WorkID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkRevisionsByWorkID = `-- name: CountWorkRevisionsByWorkID :one
SELECT COUNT(*) FROM work_revisions WHERE work_id = ?1
`

func (q *Queries) CountWorkRevisionsByWorkID(ctx context.Context, workID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWorkRevisionsByWorkID, workID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCurrentNormalizedRevisionWorkID = `-- name: GetCurrentNormalizedRevisionWorkID :one
SELECT wr.work_id FROM work_revisions wr
WHERE wr.id = ?1
  AND wr.pipeline_run_id = ?2
  AND wr.producer_stage = 'normalize'
  AND wr.id = (SELECT MAX(normalized_candidate.id) FROM work_revisions normalized_candidate
      WHERE normalized_candidate.pipeline_run_id = wr.pipeline_run_id
        AND normalized_candidate.work_id = wr.work_id
        AND normalized_candidate.producer_stage = 'normalize')
  AND EXISTS (SELECT 1 FROM run_work_stages current_validation
      WHERE current_validation.pipeline_run_id = wr.pipeline_run_id
        AND current_validation.work_id = wr.work_id
        AND current_validation.stage_name = 'validate'
        AND current_validation.outcome = 'valid')
`

type GetCurrentNormalizedRevisionWorkIDParams struct {
	ID            int64
	PipelineRunID int64
}

func (q *Queries) GetCurrentNormalizedRevisionWorkID(ctx context.Context, arg GetCurrentNormalizedRevisionWorkIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCurrentNormalizedRevisionWorkID, arg.ID, arg.PipelineRunID)
	var work_id int64
	err := row.Scan(&work_id)
	return work_id, err
}

const getWorkRevisionByID = `-- name: GetWorkRevisionByID :one
SELECT
    id,
    work_id,
    pipeline_run_id,
    field_schema_version,
    payload_hash,
    title,
    abstract,
    year,
    journal,
    publisher,
    source,
    keywords,
    keywords_plus,
    citation_count,
    reference_count,
    extension_data,
    producer_stage,
    created_at
FROM work_revisions
WHERE id = ?1
`

func (q *Queries) GetWorkRevisionByID(ctx context.Context, id int64) (WorkRevision, error) {
	row := q.db.QueryRowContext(ctx, getWorkRevisionByID, id)
	var i WorkRevision
	err := row.Scan(
		&i.ID,
		&i.WorkID,
		&i.PipelineRunID,
		&i.FieldSchemaVersion,
		&i.PayloadHash,
		&i.Title,
		&i.Abstract,
		&i.Year,
		&i.Journal,
		&i.Publisher,
		&i.Source,
		&i.Keywords,
		&i.KeywordsPlus,
		&i.CitationCount,
		&i.ReferenceCount,
		&i.ExtensionData,
		&i.ProducerStage,
		&i.CreatedAt,
	)
	return i, err
}

const insertWorkRevision = `-- name: InsertWorkRevision :execresult
INSERT INTO work_revisions (
    work_id,
    pipeline_run_id,
    producer_stage,
    field_schema_version,
    payload_hash,
    title,
    abstract,
    year,
    journal,
    publisher,
    source,
    keywords,
    keywords_plus,
    citation_count,
    reference_count,
    extension_data
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11,
    ?12,
    ?13,
    ?14,
    ?15,
    ?16
)
`

type InsertWorkRevisionParams struct {
	WorkID             int64
	PipelineRunID      int64
	ProducerStage      string
	FieldSchemaVersion string
	PayloadHash        string
	Title              sql.NullString
	Abstract           sql.NullString
	Year               sql.NullInt64
	Journal            sql.NullString
	Publisher          sql.NullString
	Source             sql.NullString
	Keywords           sql.NullString
	KeywordsPlus       sql.NullString
	CitationCount      sql.NullInt64
	ReferenceCount     sql.NullInt64
	ExtensionData      sql.NullString
}

func (q *Queries) InsertWorkRevision(ctx context.Context, arg InsertWorkRevisionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertWorkRevision,
		arg.WorkID,
		arg.PipelineRunID,
		arg.ProducerStage,
		arg.FieldSchemaVersion,
		arg.PayloadHash,
		arg.Title,
		arg.Abstract,
		arg.Year,
		arg.Journal,
		arg.Publisher,
		arg.Source,
		arg.Keywords,
		arg.KeywordsPlus,
		arg.CitationCount,
		arg.ReferenceCount,
		arg.ExtensionData,
	)
}

const listNormalizeRevisionsByRunID = `-- name: ListNormalizeRevisionsByRunID :many
SELECT
    id,
    work_id,
    pipeline_run_id,
    field_schema_version,
    payload_hash,
    title,
    abstract,
    year,
    journal,
    publisher,
    source,
    keywords,
    keywords_plus,
    citation_count,
    reference_count,
    extension_data,
    producer_stage,
    created_at
FROM work_revisions
WHERE pipeline_run_id = ?1
  AND producer_stage = 'normalize'
ORDER BY id
`

func (q *Queries) ListNormalizeRevisionsByRunID(ctx context.Context, pipelineRunID int64) ([]WorkRevision, error) {
	rows, err := q.db.QueryContext(ctx, listNormalizeRevisionsByRunID, pipelineRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkRevision
	for rows.Next() {
		var i WorkRevision
		if err := rows.Scan(
			&i.ID,
			&i.WorkID,
			&i.PipelineRunID,
			&i.FieldSchemaVersion,
			&i.PayloadHash,
			&i.Title,
			&i.Abstract,
			&i.Year,
			&i.Journal,
			&i.Publisher,
			&i.Source,
			&i.Keywords,
			&i.KeywordsPlus,
			&i.CitationCount,
			&i.ReferenceCount,
			&i.ExtensionData,
			&i.ProducerStage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkRevisionsByRunID = `-- name: ListWorkRevisionsByRunID :many
SELECT
    id,
    work_id,
    pipeline_run_id,
    field_schema_version,
    payload_hash,
    title,
    abstract,
    year,
    journal,
    publisher,
    source,
    keywords,
    keywords_plus,
    citation_count,
    reference_count,
    extension_data,
    producer_stage,
    created_at
FROM work_revisions
WHERE pipeline_run_id = ?1
ORDER BY id
`

func (q *Queries) ListWorkRevisionsByRunID(ctx context.Context, pipelineRunID int64) ([]WorkRevision, error) {
	rows, err := q.db.QueryContext(ctx, listWorkRevisionsByRunID, pipelineRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkRevision
	for rows.Next() {
		var i WorkRevision
		if err := rows.Scan(
			&i.ID,
			&i.WorkID,
			&i.PipelineRunID,
			&i.FieldSchemaVersion,
			&i.PayloadHash,
			&i.Title,
			&i.Abstract,
			&i.Year,
			&i.Journal,
			&i.Publisher,
			&i.Source,
			&i.Keywords,
			&i.KeywordsPlus,
			&i.CitationCount,
			&i.ReferenceCount,
			&i.ExtensionData,
			&i.ProducerStage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkRevisionsByWorkID = `-- name: ListWorkRevisionsByWorkID :many
SELECT
    id,
    work_id,
    pipeline_run_id,
    field_schema_version,
    payload_hash,
    title,
    abstract,
    year,
    journal,
    publisher,
    source,
    keywords,
    keywords_plus,
    citation_count,
    reference_count,
    extension_data,
    producer_stage,
    created_at
FROM work_revisions
WHERE work_id = ?1
ORDER BY id
`

func (q *Queries) ListWorkRevisionsByWorkID(ctx context.Context, workID int64) ([]WorkRevision, error) {
	rows, err := q.db.QueryContext(ctx, listWorkRevisionsByWorkID, workID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkRevision
	for rows.Next() {
		var i WorkRevision
		if err := rows.Scan(
			&i.ID,
			&i.WorkID,
			&i.PipelineRunID,
			&i.FieldSchemaVersion,
			&i.PayloadHash,
			&i.Title,
			&i.Abstract,
			&i.Year,
			&i.Journal,
			&i.Publisher,
			&i.Source,
			&i.Keywords,
			&i.KeywordsPlus,
			&i.CitationCount,
			&i.ReferenceCount,
			&i.ExtensionData,
			&i.ProducerStage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
