// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stage.sql

package sql

import (
	"context"
	"database/sql"
)

const countRunWorkStagesByStageAndOutcome = `-- name: CountRunWorkStagesByStageAndOutcome :one
SELECT COUNT(*) FROM run_work_stages
WHERE pipeline_run_id = ?1
  AND stage_name = ?2
  AND outcome = ?3
`

type CountRunWorkStagesByStageAndOutcomeParams struct {
	PipelineRunID int64
	StageName     string
	Outcome       string
}

func (q *Queries) CountRunWorkStagesByStageAndOutcome(ctx context.Context, arg CountRunWorkStagesByStageAndOutcomeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRunWorkStagesByStageAndOutcome, arg.PipelineRunID, arg.StageName, arg.Outcome)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRunWorkStageByRunWorkStage = `-- name: GetRunWorkStageByRunWorkStage :one
SELECT
    id,
    pipeline_run_id,
    work_id,
    stage_name,
    outcome,
    reason,
    created_at,
    updated_at
FROM run_work_stages
WHERE pipeline_run_id = ?1
  AND work_id = ?2
  AND stage_name = ?3
`

type GetRunWorkStageByRunWorkStageParams struct {
	PipelineRunID int64
	WorkID        int64
	StageName     string
}

func (q *Queries) GetRunWorkStageByRunWorkStage(ctx context.Context, arg GetRunWorkStageByRunWorkStageParams) (RunWorkStage, error) {
	row := q.db.QueryRowContext(ctx, getRunWorkStageByRunWorkStage, arg.PipelineRunID, arg.WorkID, arg.StageName)
	var i RunWorkStage
	err := row.Scan(
		&i.ID,
		&i.PipelineRunID,
		&i.WorkID,
		&i.StageName,
		&i.Outcome,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRunWorkStagesByRunID = `-- name: ListRunWorkStagesByRunID :many
SELECT
    id,
    pipeline_run_id,
    work_id,
    stage_name,
    outcome,
    reason,
    created_at,
    updated_at
FROM run_work_stages
WHERE pipeline_run_id = ?1
ORDER BY id
`

func (q *Queries) ListRunWorkStagesByRunID(ctx context.Context, pipelineRunID int64) ([]RunWorkStage, error) {
	rows, err := q.db.QueryContext(ctx, listRunWorkStagesByRunID, pipelineRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunWorkStage
	for rows.Next() {
		var i RunWorkStage
		if err := rows.Scan(
			&i.ID,
			&i.PipelineRunID,
			&i.WorkID,
			&i.StageName,
			&i.Outcome,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunWorkStagesByWorkID = `-- name: ListRunWorkStagesByWorkID :many
SELECT
    id,
    pipeline_run_id,
    work_id,
    stage_name,
    outcome,
    reason,
    created_at,
    updated_at
FROM run_work_stages
WHERE work_id = ?1
ORDER BY id
`

func (q *Queries) ListRunWorkStagesByWorkID(ctx context.Context, workID int64) ([]RunWorkStage, error) {
	rows, err := q.db.QueryContext(ctx, listRunWorkStagesByWorkID, workID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunWorkStage
	for rows.Next() {
		var i RunWorkStage
		if err := rows.Scan(
			&i.ID,
			&i.PipelineRunID,
			&i.WorkID,
			&i.StageName,
			&i.Outcome,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRunWorkStage = `-- name: UpsertRunWorkStage :exec
INSERT INTO run_work_stages (
    pipeline_run_id,
    work_id,
    stage_name,
    outcome,
    reason,
    updated_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    datetime('now')
)
ON CONFLICT (pipeline_run_id, work_id, stage_name)
DO UPDATE SET
    outcome    = excluded.outcome,
    reason     = excluded.reason,
    updated_at = datetime('now')
`

type UpsertRunWorkStageParams struct {
	PipelineRunID int64
	WorkID        int64
	StageName     string
	Outcome       string
	Reason        sql.NullString
}

func (q *Queries) UpsertRunWorkStage(ctx context.Context, arg UpsertRunWorkStageParams) error {
	_, err := q.db.ExecContext(ctx, upsertRunWorkStage,
		arg.PipelineRunID,
		arg.WorkID,
		arg.StageName,
		arg.Outcome,
		arg.Reason,
	)
	return err
}
