// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: term_match.sql

package sql

import (
	"context"
	"strings"
)

const deleteRevisionTermMatches = `-- name: DeleteRevisionTermMatches :exec
DELETE FROM work_revision_term_matches WHERE pipeline_run_id = ?1
`

func (q *Queries) DeleteRevisionTermMatches(ctx context.Context, pipelineRunID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRevisionTermMatches, pipelineRunID)
	return err
}

const deleteRunSearchTerms = `-- name: DeleteRunSearchTerms :exec
DELETE FROM run_search_terms WHERE pipeline_run_id = ?1
`

func (q *Queries) DeleteRunSearchTerms(ctx context.Context, pipelineRunID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRunSearchTerms, pipelineRunID)
	return err
}

const hasRunTermData = `-- name: HasRunTermData :one
SELECT EXISTS(
    SELECT 1 FROM run_term_match_reconciliations
    WHERE pipeline_run_id = ?1
)
`

func (q *Queries) HasRunTermData(ctx context.Context, pipelineRunID int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasRunTermData, pipelineRunID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertRevisionTermMatch = `-- name: InsertRevisionTermMatch :exec
INSERT OR IGNORE INTO work_revision_term_matches (pipeline_run_id, work_revision_id, field, term)
VALUES (
    ?1,
    ?2,
    ?3,
    ?4
)
`

type InsertRevisionTermMatchParams struct {
	PipelineRunID  int64
	WorkRevisionID int64
	Field          string
	Term           string
}

func (q *Queries) InsertRevisionTermMatch(ctx context.Context, arg InsertRevisionTermMatchParams) error {
	_, err := q.db.ExecContext(ctx, insertRevisionTermMatch,
		arg.PipelineRunID,
		arg.WorkRevisionID,
		arg.Field,
		arg.Term,
	)
	return err
}

const insertRunSearchTerm = `-- name: InsertRunSearchTerm :exec
INSERT OR IGNORE INTO run_search_terms (pipeline_run_id, source_name, term)
VALUES (
    ?1,
    ?2,
    ?3
)
`

type InsertRunSearchTermParams struct {
	PipelineRunID int64
	SourceName    string
	Term          string
}

func (q *Queries) InsertRunSearchTerm(ctx context.Context, arg InsertRunSearchTermParams) error {
	_, err := q.db.ExecContext(ctx, insertRunSearchTerm, arg.PipelineRunID, arg.SourceName, arg.Term)
	return err
}

const listRevisionTermMatches = `-- name: ListRevisionTermMatches :many
SELECT field, term
FROM work_revision_term_matches
WHERE pipeline_run_id = ?1
  AND work_revision_id = ?2
ORDER BY id
`

type ListRevisionTermMatchesParams struct {
	PipelineRunID  int64
	WorkRevisionID int64
}

type ListRevisionTermMatchesRow struct {
	Field string
	Term  string
}

func (q *Queries) ListRevisionTermMatches(ctx context.Context, arg ListRevisionTermMatchesParams) ([]ListRevisionTermMatchesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRevisionTermMatches, arg.PipelineRunID, arg.WorkRevisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRevisionTermMatchesRow
	for rows.Next() {
		var i ListRevisionTermMatchesRow
		if err := rows.Scan(&i.Field, &i.Term); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRevisionTermMatchesBulk = `-- name: ListRevisionTermMatchesBulk :many
SELECT work_revision_id, field, term
FROM work_revision_term_matches
WHERE pipeline_run_id = ?1
  AND work_revision_id IN (/*SLICE:revision_ids*/?)
ORDER BY id
`

type ListRevisionTermMatchesBulkParams struct {
	PipelineRunID int64
	RevisionIds   []int64
}

type ListRevisionTermMatchesBulkRow struct {
	WorkRevisionID int64
	Field          string
	Term           string
}

func (q *Queries) ListRevisionTermMatchesBulk(ctx context.Context, arg ListRevisionTermMatchesBulkParams) ([]ListRevisionTermMatchesBulkRow, error) {
	query := listRevisionTermMatchesBulk
	var queryParams []interface{}
	queryParams = append(queryParams, arg.PipelineRunID)
	if len(arg.RevisionIds) > 0 {
		for _, v := range arg.RevisionIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:revision_ids*/?", strings.Repeat(",?", len(arg.RevisionIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:revision_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRevisionTermMatchesBulkRow
	for rows.Next() {
		var i ListRevisionTermMatchesBulkRow
		if err := rows.Scan(&i.WorkRevisionID, &i.Field, &i.Term); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunSearchTermsByRun = `-- name: ListRunSearchTermsByRun :many
SELECT
    id,
    pipeline_run_id,
    source_name,
    term,
    created_at
FROM run_search_terms
WHERE pipeline_run_id = ?1
ORDER BY id
`

func (q *Queries) ListRunSearchTermsByRun(ctx context.Context, pipelineRunID int64) ([]RunSearchTerm, error) {
	rows, err := q.db.QueryContext(ctx, listRunSearchTermsByRun, pipelineRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunSearchTerm
	for rows.Next() {
		var i RunSearchTerm
		if err := rows.Scan(
			&i.ID,
			&i.PipelineRunID,
			&i.SourceName,
			&i.Term,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRunTermReconciliation = `-- name: UpsertRunTermReconciliation :exec
INSERT INTO run_term_match_reconciliations (pipeline_run_id)
VALUES (?1)
ON CONFLICT (pipeline_run_id)
DO UPDATE SET reconciled_at = datetime('now')
`

func (q *Queries) UpsertRunTermReconciliation(ctx context.Context, pipelineRunID int64) error {
	_, err := q.db.ExecContext(ctx, upsertRunTermReconciliation, pipelineRunID)
	return err
}
