// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: work.sql

package sql

import (
	"context"
	"database/sql"
	"strings"
)

const countWorkIdentifiersByWorkID = `-- name: CountWorkIdentifiersByWorkID :one
SELECT COUNT(*) FROM work_identifiers WHERE work_id = ?1
`

func (q *Queries) CountWorkIdentifiersByWorkID(ctx context.Context, workID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWorkIdentifiersByWorkID, workID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorks = `-- name: CountWorks :one
SELECT COUNT(*) FROM works
`

func (q *Queries) CountWorks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWorks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getWorkByDOI = `-- name: GetWorkByDOI :one
SELECT
    id,
    doi,
    created_at
FROM works
WHERE doi = ?1
`

func (q *Queries) GetWorkByDOI(ctx context.Context, doi sql.NullString) (Work, error) {
	row := q.db.QueryRowContext(ctx, getWorkByDOI, doi)
	var i Work
	err := row.Scan(&i.ID, &i.Doi, &i.CreatedAt)
	return i, err
}

const getWorkByID = `-- name: GetWorkByID :one
SELECT
    id,
    doi,
    created_at
FROM works
WHERE id = ?1
`

func (q *Queries) GetWorkByID(ctx context.Context, id int64) (Work, error) {
	row := q.db.QueryRowContext(ctx, getWorkByID, id)
	var i Work
	err := row.Scan(&i.ID, &i.Doi, &i.CreatedAt)
	return i, err
}

const getWorkIdentifierByID = `-- name: GetWorkIdentifierByID :one
SELECT
    id,
    work_id,
    namespace,
    identifier,
    created_at
FROM work_identifiers
WHERE id = ?1
`

func (q *Queries) GetWorkIdentifierByID(ctx context.Context, id int64) (WorkIdentifier, error) {
	row := q.db.QueryRowContext(ctx, getWorkIdentifierByID, id)
	var i WorkIdentifier
	err := row.Scan(
		&i.ID,
		&i.WorkID,
		&i.Namespace,
		&i.Identifier,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkIdentifierByNamespaceAndIdentifier = `-- name: GetWorkIdentifierByNamespaceAndIdentifier :one
SELECT
    id,
    work_id,
    namespace,
    identifier,
    created_at
FROM work_identifiers
WHERE namespace = ?1
  AND identifier = ?2
`

type GetWorkIdentifierByNamespaceAndIdentifierParams struct {
	Namespace  string
	Identifier string
}

func (q *Queries) GetWorkIdentifierByNamespaceAndIdentifier(ctx context.Context, arg GetWorkIdentifierByNamespaceAndIdentifierParams) (WorkIdentifier, error) {
	row := q.db.QueryRowContext(ctx, getWorkIdentifierByNamespaceAndIdentifier, arg.Namespace, arg.Identifier)
	var i WorkIdentifier
	err := row.Scan(
		&i.ID,
		&i.WorkID,
		&i.Namespace,
		&i.Identifier,
		&i.CreatedAt,
	)
	return i, err
}

const insertWorkByDOI = `-- name: InsertWorkByDOI :execresult
INSERT OR IGNORE INTO works (doi)
VALUES (?1)
`

func (q *Queries) InsertWorkByDOI(ctx context.Context, doi sql.NullString) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertWorkByDOI, doi)
}

const insertWorkIdentifier = `-- name: InsertWorkIdentifier :execresult
INSERT OR IGNORE INTO work_identifiers (work_id, namespace, identifier)
VALUES (
    ?1,
    ?2,
    ?3
)
`

type InsertWorkIdentifierParams struct {
	WorkID     int64
	Namespace  string
	Identifier string
}

func (q *Queries) InsertWorkIdentifier(ctx context.Context, arg InsertWorkIdentifierParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertWorkIdentifier, arg.WorkID, arg.Namespace, arg.Identifier)
}

const insertWorkWithoutDOI = `-- name: InsertWorkWithoutDOI :execresult
INSERT INTO works (doi)
VALUES (NULL)
`

func (q *Queries) InsertWorkWithoutDOI(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertWorkWithoutDOI)
}

const listWorkIdentifiersByWorkID = `-- name: ListWorkIdentifiersByWorkID :many
SELECT
    id,
    work_id,
    namespace,
    identifier,
    created_at
FROM work_identifiers
WHERE work_id = ?1
ORDER BY id
`

func (q *Queries) ListWorkIdentifiersByWorkID(ctx context.Context, workID int64) ([]WorkIdentifier, error) {
	rows, err := q.db.QueryContext(ctx, listWorkIdentifiersByWorkID, workID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkIdentifier
	for rows.Next() {
		var i WorkIdentifier
		if err := rows.Scan(
			&i.ID,
			&i.WorkID,
			&i.Namespace,
			&i.Identifier,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorksByIDs = `-- name: ListWorksByIDs :many
SELECT
    id,
    doi,
    created_at
FROM works
WHERE id IN (/*SLICE:ids*/?)
ORDER BY id
`

func (q *Queries) ListWorksByIDs(ctx context.Context, ids []int64) ([]Work, error) {
	query := listWorksByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Work
	for rows.Next() {
		var i Work
		if err := rows.Scan(&i.ID, &i.Doi, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
