// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: anchor.sql

package sql

import (
	"context"
	"database/sql"
)

const countActiveReviewAnchors = `-- name: CountActiveReviewAnchors :one
SELECT COUNT(*)
FROM review_context_anchor_heads head
JOIN review_anchors logical ON logical.id=head.anchor_id
JOIN review_anchor_versions version ON version.id=head.anchor_version_id
WHERE head.review_context_id = ?1
  AND logical.work_id = ?2
  AND version.state='active'
`

type CountActiveReviewAnchorsParams struct {
	ReviewContextID int64
	WorkID          int64
}

func (q *Queries) CountActiveReviewAnchors(ctx context.Context, arg CountActiveReviewAnchorsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveReviewAnchors, arg.ReviewContextID, arg.WorkID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getActiveReviewAnchorVersion = `-- name: GetActiveReviewAnchorVersion :one
SELECT
    pdf_content_hash,
    page,
    selected_text,
    rectangles_json
FROM review_anchor_versions
WHERE id = ?1
  AND anchor_id = ?2
  AND state = 'active'
`

type GetActiveReviewAnchorVersionParams struct {
	ID       int64
	AnchorID string
}

type GetActiveReviewAnchorVersionRow struct {
	PdfContentHash string
	Page           sql.NullInt64
	SelectedText   sql.NullString
	RectanglesJson sql.NullString
}

func (q *Queries) GetActiveReviewAnchorVersion(ctx context.Context, arg GetActiveReviewAnchorVersionParams) (GetActiveReviewAnchorVersionRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveReviewAnchorVersion, arg.ID, arg.AnchorID)
	var i GetActiveReviewAnchorVersionRow
	err := row.Scan(
		&i.PdfContentHash,
		&i.Page,
		&i.SelectedText,
		&i.RectanglesJson,
	)
	return i, err
}

const getReviewAnchorHead = `-- name: GetReviewAnchorHead :one
SELECT
    logical.id,
    CAST(COALESCE(logical.label, logical.id) AS TEXT) AS label,
    logical.work_id,
    logical.created_at,
    head.anchor_version_id
FROM review_context_anchor_heads head
JOIN review_anchors logical ON logical.id = head.anchor_id
WHERE head.review_context_id = ?1
  AND head.anchor_id = ?2
`

type GetReviewAnchorHeadParams struct {
	ReviewContextID int64
	AnchorID        string
}

type GetReviewAnchorHeadRow struct {
	ID              string
	Label           string
	WorkID          int64
	CreatedAt       string
	AnchorVersionID int64
}

func (q *Queries) GetReviewAnchorHead(ctx context.Context, arg GetReviewAnchorHeadParams) (GetReviewAnchorHeadRow, error) {
	row := q.db.QueryRowContext(ctx, getReviewAnchorHead, arg.ReviewContextID, arg.AnchorID)
	var i GetReviewAnchorHeadRow
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.WorkID,
		&i.CreatedAt,
		&i.AnchorVersionID,
	)
	return i, err
}

const getReviewAnchorHeadForUpdate = `-- name: GetReviewAnchorHeadForUpdate :one
SELECT
    rc.pipeline_run_id,
    logical.work_id,
    work_head.work_revision_id,
    head.anchor_version_id,
    CAST(COALESCE(logical.label, logical.id) AS TEXT) AS label,
    logical.created_at,
    pr.status,
    pr.visibility_state
FROM review_context_anchor_heads head
JOIN review_contexts rc ON rc.id = head.review_context_id
JOIN pipeline_runs pr ON pr.id = rc.pipeline_run_id
JOIN review_anchors logical ON logical.id = head.anchor_id
JOIN review_context_work_heads work_head
    ON work_head.review_context_id = head.review_context_id
    AND work_head.work_id = logical.work_id
WHERE head.review_context_id = ?1
  AND head.anchor_id = ?2
`

type GetReviewAnchorHeadForUpdateParams struct {
	ReviewContextID int64
	AnchorID        string
}

type GetReviewAnchorHeadForUpdateRow struct {
	PipelineRunID   int64
	WorkID          int64
	WorkRevisionID  int64
	AnchorVersionID int64
	Label           string
	CreatedAt       string
	Status          string
	VisibilityState string
}

func (q *Queries) GetReviewAnchorHeadForUpdate(ctx context.Context, arg GetReviewAnchorHeadForUpdateParams) (GetReviewAnchorHeadForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getReviewAnchorHeadForUpdate, arg.ReviewContextID, arg.AnchorID)
	var i GetReviewAnchorHeadForUpdateRow
	err := row.Scan(
		&i.PipelineRunID,
		&i.WorkID,
		&i.WorkRevisionID,
		&i.AnchorVersionID,
		&i.Label,
		&i.CreatedAt,
		&i.Status,
		&i.VisibilityState,
	)
	return i, err
}

const getReviewAnchorVersionByID = `-- name: GetReviewAnchorVersionByID :one
SELECT
    version.id,
    version.anchor_id,
    version.parent_version_id,
    version.created_in_context_id,
    version.work_revision_id,
    version.pdf_content_hash,
    version.state,
    version.page,
    version.selected_text,
    version.rectangles_json,
    version.created_at,
    CAST(COALESCE(reviewer.username, '') AS TEXT) AS reviewer_username,
    CAST(COALESCE(reviewer.email, '') AS TEXT) AS reviewer_email
FROM review_anchor_versions version
JOIN review_contexts context ON context.id = version.created_in_context_id
LEFT JOIN pipeline_run_reviewers reviewer ON reviewer.pipeline_run_id = context.pipeline_run_id
WHERE version.id = ?1
`

type GetReviewAnchorVersionByIDRow struct {
	ID                 int64
	AnchorID           string
	ParentVersionID    sql.NullInt64
	CreatedInContextID int64
	WorkRevisionID     int64
	PdfContentHash     string
	State              string
	Page               sql.NullInt64
	SelectedText       sql.NullString
	RectanglesJson     sql.NullString
	CreatedAt          string
	ReviewerUsername   string
	ReviewerEmail      string
}

func (q *Queries) GetReviewAnchorVersionByID(ctx context.Context, id int64) (GetReviewAnchorVersionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getReviewAnchorVersionByID, id)
	var i GetReviewAnchorVersionByIDRow
	err := row.Scan(
		&i.ID,
		&i.AnchorID,
		&i.ParentVersionID,
		&i.CreatedInContextID,
		&i.WorkRevisionID,
		&i.PdfContentHash,
		&i.State,
		&i.Page,
		&i.SelectedText,
		&i.RectanglesJson,
		&i.CreatedAt,
		&i.ReviewerUsername,
		&i.ReviewerEmail,
	)
	return i, err
}

const getReviewAnchorWorkID = `-- name: GetReviewAnchorWorkID :one
SELECT logical.work_id
FROM review_context_anchor_heads head
JOIN review_anchors logical ON logical.id=head.anchor_id
WHERE head.review_context_id = ?1
  AND head.anchor_id = ?2
`

type GetReviewAnchorWorkIDParams struct {
	ReviewContextID int64
	AnchorID        string
}

func (q *Queries) GetReviewAnchorWorkID(ctx context.Context, arg GetReviewAnchorWorkIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getReviewAnchorWorkID, arg.ReviewContextID, arg.AnchorID)
	var work_id int64
	err := row.Scan(&work_id)
	return work_id, err
}

const insertReviewAnchor = `-- name: InsertReviewAnchor :exec
INSERT INTO review_anchors (
    id,
    work_id,
    label,
    created_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4
)
`

type InsertReviewAnchorParams struct {
	ID        string
	WorkID    int64
	Label     sql.NullString
	CreatedAt string
}

func (q *Queries) InsertReviewAnchor(ctx context.Context, arg InsertReviewAnchorParams) error {
	_, err := q.db.ExecContext(ctx, insertReviewAnchor,
		arg.ID,
		arg.WorkID,
		arg.Label,
		arg.CreatedAt,
	)
	return err
}

const insertReviewAnchorFirstVersion = `-- name: InsertReviewAnchorFirstVersion :execresult
INSERT INTO review_anchor_versions (
    anchor_id,
    created_in_context_id,
    work_revision_id,
    pdf_content_hash,
    state,
    page,
    selected_text,
    rectangles_json,
    created_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    'active',
    ?5,
    ?6,
    ?7,
    ?8
)
`

type InsertReviewAnchorFirstVersionParams struct {
	AnchorID           string
	CreatedInContextID int64
	WorkRevisionID     int64
	PdfContentHash     string
	Page               sql.NullInt64
	SelectedText       sql.NullString
	RectanglesJson     sql.NullString
	CreatedAt          string
}

func (q *Queries) InsertReviewAnchorFirstVersion(ctx context.Context, arg InsertReviewAnchorFirstVersionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertReviewAnchorFirstVersion,
		arg.AnchorID,
		arg.CreatedInContextID,
		arg.WorkRevisionID,
		arg.PdfContentHash,
		arg.Page,
		arg.SelectedText,
		arg.RectanglesJson,
		arg.CreatedAt,
	)
}

const insertReviewAnchorHead = `-- name: InsertReviewAnchorHead :exec
INSERT INTO review_context_anchor_heads (
    review_context_id,
    anchor_id,
    anchor_version_id
) VALUES (
    ?1,
    ?2,
    ?3
)
`

type InsertReviewAnchorHeadParams struct {
	ReviewContextID int64
	AnchorID        string
	AnchorVersionID int64
}

func (q *Queries) InsertReviewAnchorHead(ctx context.Context, arg InsertReviewAnchorHeadParams) error {
	_, err := q.db.ExecContext(ctx, insertReviewAnchorHead, arg.ReviewContextID, arg.AnchorID, arg.AnchorVersionID)
	return err
}

const insertReviewAnchorVersion = `-- name: InsertReviewAnchorVersion :execresult
INSERT INTO review_anchor_versions (
    anchor_id,
    parent_version_id,
    created_in_context_id,
    work_revision_id,
    pdf_content_hash,
    state,
    page,
    selected_text,
    rectangles_json,
    created_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10
)
`

type InsertReviewAnchorVersionParams struct {
	AnchorID           string
	ParentVersionID    sql.NullInt64
	CreatedInContextID int64
	WorkRevisionID     int64
	PdfContentHash     string
	State              string
	Page               sql.NullInt64
	SelectedText       sql.NullString
	RectanglesJson     sql.NullString
	CreatedAt          string
}

func (q *Queries) InsertReviewAnchorVersion(ctx context.Context, arg InsertReviewAnchorVersionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertReviewAnchorVersion,
		arg.AnchorID,
		arg.ParentVersionID,
		arg.CreatedInContextID,
		arg.WorkRevisionID,
		arg.PdfContentHash,
		arg.State,
		arg.Page,
		arg.SelectedText,
		arg.RectanglesJson,
		arg.CreatedAt,
	)
}

const listReviewAnchorVersionAncestry = `-- name: ListReviewAnchorVersionAncestry :many
WITH RECURSIVE ancestry(id) AS (
    SELECT anchor_head.anchor_version_id
    FROM review_context_anchor_heads anchor_head
    WHERE anchor_head.review_context_id = ?4
      AND anchor_head.anchor_id = ?5
    UNION ALL
    SELECT version.parent_version_id
    FROM review_anchor_versions version
    JOIN ancestry ON version.id = ancestry.id
    WHERE version.parent_version_id IS NOT NULL
)
SELECT
    version.id,
    version.anchor_id,
    version.parent_version_id,
    version.created_in_context_id,
    version.work_revision_id,
    version.pdf_content_hash,
    version.state,
    version.page,
    CAST(COALESCE(substr(version.selected_text, 1, CAST(?1 AS INTEGER)), '') AS TEXT) AS selected_text_preview,
    CAST(COALESCE(length(CAST(version.selected_text AS BLOB)), 0) AS INTEGER) AS selected_text_bytes,
    CAST(version.selected_text IS NOT NULL AS INTEGER) AS has_selected_text,
    version.rectangles_json,
    version.created_at,
    CAST(COALESCE(reviewer.username, '') AS TEXT) AS reviewer_username,
    CAST(COALESCE(reviewer.email, '') AS TEXT) AS reviewer_email
FROM ancestry
JOIN review_anchor_versions version ON version.id = ancestry.id
JOIN review_contexts version_context ON version_context.id = version.created_in_context_id
LEFT JOIN pipeline_run_reviewers reviewer ON reviewer.pipeline_run_id = version_context.pipeline_run_id
WHERE (CAST(?2 AS INTEGER) = 0 OR version.id < CAST(?2 AS INTEGER))
ORDER BY version.id DESC
LIMIT CAST(?3 AS INTEGER)
`

type ListReviewAnchorVersionAncestryParams struct {
	PreviewBytes    int64
	Cursor          int64
	PageLimit       int64
	ReviewContextID int64
	AnchorID        string
}

type ListReviewAnchorVersionAncestryRow struct {
	ID                  int64
	AnchorID            string
	ParentVersionID     sql.NullInt64
	CreatedInContextID  int64
	WorkRevisionID      int64
	PdfContentHash      string
	State               string
	Page                sql.NullInt64
	SelectedTextPreview string
	SelectedTextBytes   int64
	HasSelectedText     int64
	RectanglesJson      sql.NullString
	CreatedAt           string
	ReviewerUsername    string
	ReviewerEmail       string
}

func (q *Queries) ListReviewAnchorVersionAncestry(ctx context.Context, arg ListReviewAnchorVersionAncestryParams) ([]ListReviewAnchorVersionAncestryRow, error) {
	rows, err := q.db.QueryContext(ctx, listReviewAnchorVersionAncestry,
		arg.PreviewBytes,
		arg.Cursor,
		arg.PageLimit,
		arg.ReviewContextID,
		arg.AnchorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewAnchorVersionAncestryRow
	for rows.Next() {
		var i ListReviewAnchorVersionAncestryRow
		if err := rows.Scan(
			&i.ID,
			&i.AnchorID,
			&i.ParentVersionID,
			&i.CreatedInContextID,
			&i.WorkRevisionID,
			&i.PdfContentHash,
			&i.State,
			&i.Page,
			&i.SelectedTextPreview,
			&i.SelectedTextBytes,
			&i.HasSelectedText,
			&i.RectanglesJson,
			&i.CreatedAt,
			&i.ReviewerUsername,
			&i.ReviewerEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewAnchors = `-- name: ListReviewAnchors :many
SELECT
    logical.id,
    CAST(COALESCE(logical.label, logical.id) AS TEXT) AS label,
    logical.work_id,
    logical.created_at,
    version.id AS version_id,
    version.anchor_id,
    version.parent_version_id,
    version.created_in_context_id,
    version.work_revision_id,
    version.pdf_content_hash,
    version.state,
    version.page,
    CAST(COALESCE(substr(version.selected_text, 1, CAST(?1 AS INTEGER)), '') AS TEXT) AS selected_text_preview,
    CAST(COALESCE(length(CAST(version.selected_text AS BLOB)), 0) AS INTEGER) AS selected_text_bytes,
    CAST(version.selected_text IS NOT NULL AS INTEGER) AS has_selected_text,
    version.rectangles_json,
    version.created_at AS version_created_at,
    CAST(COALESCE(reviewer.username, '') AS TEXT) AS reviewer_username,
    CAST(COALESCE(reviewer.email, '') AS TEXT) AS reviewer_email
FROM review_context_anchor_heads head
JOIN review_anchors logical ON logical.id = head.anchor_id
JOIN review_context_work_heads work_head
    ON work_head.review_context_id = head.review_context_id
    AND work_head.work_id = logical.work_id
JOIN review_anchor_versions version
    ON version.id = head.anchor_version_id
    AND version.state = 'active'
JOIN review_contexts version_context ON version_context.id = version.created_in_context_id
LEFT JOIN pipeline_run_reviewers reviewer ON reviewer.pipeline_run_id = version_context.pipeline_run_id
WHERE head.review_context_id = ?2
  AND work_head.work_revision_id = ?3
  AND (CAST(?4 AS TEXT) = '' OR head.anchor_id > CAST(?4 AS TEXT))
ORDER BY head.anchor_id
LIMIT CAST(?5 AS INTEGER)
`

type ListReviewAnchorsParams struct {
	PreviewBytes    int64
	ReviewContextID int64
	WorkRevisionID  int64
	Cursor          string
	PageLimit       int64
}

type ListReviewAnchorsRow struct {
	ID                  string
	Label               string
	WorkID              int64
	CreatedAt           string
	VersionID           int64
	AnchorID            string
	ParentVersionID     sql.NullInt64
	CreatedInContextID  int64
	WorkRevisionID      int64
	PdfContentHash      string
	State               string
	Page                sql.NullInt64
	SelectedTextPreview string
	SelectedTextBytes   int64
	HasSelectedText     int64
	RectanglesJson      sql.NullString
	VersionCreatedAt    string
	ReviewerUsername    string
	ReviewerEmail       string
}

func (q *Queries) ListReviewAnchors(ctx context.Context, arg ListReviewAnchorsParams) ([]ListReviewAnchorsRow, error) {
	rows, err := q.db.QueryContext(ctx, listReviewAnchors,
		arg.PreviewBytes,
		arg.ReviewContextID,
		arg.WorkRevisionID,
		arg.Cursor,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewAnchorsRow
	for rows.Next() {
		var i ListReviewAnchorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.WorkID,
			&i.CreatedAt,
			&i.VersionID,
			&i.AnchorID,
			&i.ParentVersionID,
			&i.CreatedInContextID,
			&i.WorkRevisionID,
			&i.PdfContentHash,
			&i.State,
			&i.Page,
			&i.SelectedTextPreview,
			&i.SelectedTextBytes,
			&i.HasSelectedText,
			&i.RectanglesJson,
			&i.VersionCreatedAt,
			&i.ReviewerUsername,
			&i.ReviewerEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewAnchorLabelExists = `-- name: ReviewAnchorLabelExists :one
SELECT EXISTS(
    SELECT 1 FROM review_anchors
    WHERE work_id = ?1
      AND label = ?2
)
`

type ReviewAnchorLabelExistsParams struct {
	WorkID int64
	Label  sql.NullString
}

func (q *Queries) ReviewAnchorLabelExists(ctx context.Context, arg ReviewAnchorLabelExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, reviewAnchorLabelExists, arg.WorkID, arg.Label)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const reviewAnchorVersionInAncestry = `-- name: ReviewAnchorVersionInAncestry :one
WITH RECURSIVE ancestry(id) AS (
    SELECT anchor_head.anchor_version_id
    FROM review_context_anchor_heads anchor_head
    WHERE anchor_head.review_context_id = ?2
      AND anchor_head.anchor_id = ?3
    UNION ALL
    SELECT version.parent_version_id
    FROM review_anchor_versions version
    JOIN ancestry ON version.id = ancestry.id
    WHERE version.parent_version_id IS NOT NULL
)
SELECT EXISTS(SELECT 1 FROM ancestry WHERE id = ?1)
`

type ReviewAnchorVersionInAncestryParams struct {
	VersionID       int64
	ReviewContextID int64
	AnchorID        string
}

func (q *Queries) ReviewAnchorVersionInAncestry(ctx context.Context, arg ReviewAnchorVersionInAncestryParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, reviewAnchorVersionInAncestry, arg.VersionID, arg.ReviewContextID, arg.AnchorID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateReviewAnchorHeadCAS = `-- name: UpdateReviewAnchorHeadCAS :execresult
UPDATE review_context_anchor_heads
SET anchor_version_id = ?1
WHERE review_context_id = ?2
  AND anchor_id = ?3
  AND anchor_version_id = ?4
`

type UpdateReviewAnchorHeadCASParams struct {
	AnchorVersionID   int64
	ReviewContextID   int64
	AnchorID          string
	ExpectedVersionID int64
}

func (q *Queries) UpdateReviewAnchorHeadCAS(ctx context.Context, arg UpdateReviewAnchorHeadCASParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateReviewAnchorHeadCAS,
		arg.AnchorVersionID,
		arg.ReviewContextID,
		arg.AnchorID,
		arg.ExpectedVersionID,
	)
}
