// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sql

import (
	"context"
	"database/sql"
)

const insertReviewAuditEvent = `-- name: InsertReviewAuditEvent :exec
INSERT INTO audit_events (
    occurred_at,
    actor,
    pipeline_run_id,
    entity_type,
    entity_id,
    action,
    before_json,
    after_json,
    metadata_json
) VALUES (
    ?1,
    'reviewer',
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8
)
`

type InsertReviewAuditEventParams struct {
	OccurredAt    string
	PipelineRunID sql.NullInt64
	EntityType    string
	EntityID      string
	Action        string
	BeforeJson    sql.NullString
	AfterJson     sql.NullString
	MetadataJson  sql.NullString
}

func (q *Queries) InsertReviewAuditEvent(ctx context.Context, arg InsertReviewAuditEventParams) error {
	_, err := q.db.ExecContext(ctx, insertReviewAuditEvent,
		arg.OccurredAt,
		arg.PipelineRunID,
		arg.EntityType,
		arg.EntityID,
		arg.Action,
		arg.BeforeJson,
		arg.AfterJson,
		arg.MetadataJson,
	)
	return err
}
