// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: context.sql

package sql

import (
	"context"
	"database/sql"
)

const getReviewContextByRun = `-- name: GetReviewContextByRun :one
SELECT
    id,
    pipeline_run_id,
    parent_context_id,
    created_at
FROM review_contexts
WHERE pipeline_run_id = ?1
`

func (q *Queries) GetReviewContextByRun(ctx context.Context, pipelineRunID int64) (ReviewContext, error) {
	row := q.db.QueryRowContext(ctx, getReviewContextByRun, pipelineRunID)
	var i ReviewContext
	err := row.Scan(
		&i.ID,
		&i.PipelineRunID,
		&i.ParentContextID,
		&i.CreatedAt,
	)
	return i, err
}

const getReviewCorpusID = `-- name: GetReviewCorpusID :one
SELECT corpus_id
FROM review_settings
WHERE id = 1
`

func (q *Queries) GetReviewCorpusID(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getReviewCorpusID)
	var corpus_id string
	err := row.Scan(&corpus_id)
	return corpus_id, err
}

const getReviewParentContextRun = `-- name: GetReviewParentContextRun :one
SELECT
    pr.id AS run_id,
    pr.started_at,
    pr.status,
    pr.visibility_state
FROM review_contexts rc
JOIN pipeline_runs pr ON pr.id = rc.pipeline_run_id
WHERE rc.id = ?1
`

type GetReviewParentContextRunRow struct {
	RunID           int64
	StartedAt       string
	Status          string
	VisibilityState string
}

func (q *Queries) GetReviewParentContextRun(ctx context.Context, contextID int64) (GetReviewParentContextRunRow, error) {
	row := q.db.QueryRowContext(ctx, getReviewParentContextRun, contextID)
	var i GetReviewParentContextRunRow
	err := row.Scan(
		&i.RunID,
		&i.StartedAt,
		&i.Status,
		&i.VisibilityState,
	)
	return i, err
}

const getReviewTarget = `-- name: GetReviewTarget :one
SELECT
    pr.id AS run_id,
    CAST(COALESCE(pr.execution_plan_id, 0) AS INTEGER) AS execution_plan_id,
    s.id AS search_db_id,
    pr.started_at,
    pr.status,
    pr.visibility_state
FROM pipeline_runs pr
JOIN execution_plans ep ON ep.id = pr.execution_plan_id
JOIN search_revisions sr ON sr.id = ep.search_revision_id
JOIN searches s ON s.id = sr.search_id
WHERE pr.id = ?1
`

type GetReviewTargetRow struct {
	RunID           int64
	ExecutionPlanID int64
	SearchDbID      int64
	StartedAt       string
	Status          string
	VisibilityState string
}

func (q *Queries) GetReviewTarget(ctx context.Context, runID int64) (GetReviewTargetRow, error) {
	row := q.db.QueryRowContext(ctx, getReviewTarget, runID)
	var i GetReviewTargetRow
	err := row.Scan(
		&i.RunID,
		&i.ExecutionPlanID,
		&i.SearchDbID,
		&i.StartedAt,
		&i.Status,
		&i.VisibilityState,
	)
	return i, err
}

const insertReviewContext = `-- name: InsertReviewContext :execresult
INSERT INTO review_contexts (
    pipeline_run_id,
    parent_context_id,
    created_at
) VALUES (
    ?1,
    ?2,
    ?3
)
`

type InsertReviewContextParams struct {
	PipelineRunID   int64
	ParentContextID sql.NullInt64
	CreatedAt       string
}

func (q *Queries) InsertReviewContext(ctx context.Context, arg InsertReviewContextParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertReviewContext, arg.PipelineRunID, arg.ParentContextID, arg.CreatedAt)
}

const insertReviewContextAnchorHeads = `-- name: InsertReviewContextAnchorHeads :exec
INSERT INTO review_context_anchor_heads (
    review_context_id,
    anchor_id,
    anchor_version_id
)
SELECT
    ?1,
    parent.anchor_id,
    parent.anchor_version_id
FROM review_context_anchor_heads parent
JOIN review_anchors anchor ON anchor.id = parent.anchor_id
JOIN review_context_work_heads target
    ON target.review_context_id = ?1
    AND target.work_id = anchor.work_id
WHERE parent.review_context_id = ?2
`

type InsertReviewContextAnchorHeadsParams struct {
	ReviewContextID int64
	ParentContextID int64
}

func (q *Queries) InsertReviewContextAnchorHeads(ctx context.Context, arg InsertReviewContextAnchorHeadsParams) error {
	_, err := q.db.ExecContext(ctx, insertReviewContextAnchorHeads, arg.ReviewContextID, arg.ParentContextID)
	return err
}

const insertReviewContextNoteHeads = `-- name: InsertReviewContextNoteHeads :exec
INSERT INTO review_context_note_heads (
    review_context_id,
    note_id,
    note_version_id
)
SELECT
    ?1,
    parent.note_id,
    parent.note_version_id
FROM review_context_note_heads parent
JOIN review_notes note ON note.id = parent.note_id
JOIN review_context_work_heads target
    ON target.review_context_id = ?1
    AND target.work_id = note.work_id
WHERE parent.review_context_id = ?2
`

type InsertReviewContextNoteHeadsParams struct {
	ReviewContextID int64
	ParentContextID int64
}

func (q *Queries) InsertReviewContextNoteHeads(ctx context.Context, arg InsertReviewContextNoteHeadsParams) error {
	_, err := q.db.ExecContext(ctx, insertReviewContextNoteHeads, arg.ReviewContextID, arg.ParentContextID)
	return err
}

const insertReviewContextWorkHeads = `-- name: InsertReviewContextWorkHeads :exec
INSERT INTO review_context_work_heads (
    review_context_id,
    work_id,
    work_revision_id,
    review_version_id
)
SELECT
    ?1,
    latest.work_id,
    latest.id,
    parent.review_version_id
FROM work_revisions latest
LEFT JOIN review_context_work_heads parent
    ON parent.review_context_id = ?2
    AND parent.work_id = latest.work_id
WHERE latest.pipeline_run_id = ?3
  AND latest.producer_stage = 'normalize'
  AND latest.id = (SELECT MAX(normalized_candidate.id) FROM work_revisions normalized_candidate
      WHERE normalized_candidate.pipeline_run_id = latest.pipeline_run_id
        AND normalized_candidate.work_id = latest.work_id
        AND normalized_candidate.producer_stage = 'normalize')
  AND EXISTS (SELECT 1 FROM run_work_stages current_validation
      WHERE current_validation.pipeline_run_id = latest.pipeline_run_id
        AND current_validation.work_id = latest.work_id
        AND current_validation.stage_name = 'validate'
        AND current_validation.outcome = 'valid')
`

type InsertReviewContextWorkHeadsParams struct {
	ReviewContextID int64
	ParentContextID sql.NullInt64
	PipelineRunID   int64
}

func (q *Queries) InsertReviewContextWorkHeads(ctx context.Context, arg InsertReviewContextWorkHeadsParams) error {
	_, err := q.db.ExecContext(ctx, insertReviewContextWorkHeads, arg.ReviewContextID, arg.ParentContextID, arg.PipelineRunID)
	return err
}
