// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: decision.sql

package sql

import (
	"context"
	"database/sql"
)

const getMutableWorkReviewHead = `-- name: GetMutableWorkReviewHead :one
SELECT
    rc.pipeline_run_id,
    head.work_id,
    head.review_version_id,
    pr.status,
    pr.visibility_state
FROM review_context_work_heads head
JOIN review_contexts rc ON rc.id = head.review_context_id
JOIN pipeline_runs pr ON pr.id = rc.pipeline_run_id
JOIN work_revisions wr
    ON wr.id = head.work_revision_id
    AND wr.pipeline_run_id = rc.pipeline_run_id
    AND wr.work_id = head.work_id
WHERE head.review_context_id = ?1
  AND head.work_revision_id = ?2
`

type GetMutableWorkReviewHeadParams struct {
	ReviewContextID int64
	WorkRevisionID  int64
}

type GetMutableWorkReviewHeadRow struct {
	PipelineRunID   int64
	WorkID          int64
	ReviewVersionID sql.NullInt64
	Status          string
	VisibilityState string
}

func (q *Queries) GetMutableWorkReviewHead(ctx context.Context, arg GetMutableWorkReviewHeadParams) (GetMutableWorkReviewHeadRow, error) {
	row := q.db.QueryRowContext(ctx, getMutableWorkReviewHead, arg.ReviewContextID, arg.WorkRevisionID)
	var i GetMutableWorkReviewHeadRow
	err := row.Scan(
		&i.PipelineRunID,
		&i.WorkID,
		&i.ReviewVersionID,
		&i.Status,
		&i.VisibilityState,
	)
	return i, err
}

const getWorkReviewHead = `-- name: GetWorkReviewHead :one
SELECT
    review_context_id,
    work_id,
    work_revision_id,
    review_version_id
FROM review_context_work_heads
WHERE review_context_id = ?1
  AND work_revision_id = ?2
`

type GetWorkReviewHeadParams struct {
	ReviewContextID int64
	WorkRevisionID  int64
}

func (q *Queries) GetWorkReviewHead(ctx context.Context, arg GetWorkReviewHeadParams) (ReviewContextWorkHead, error) {
	row := q.db.QueryRowContext(ctx, getWorkReviewHead, arg.ReviewContextID, arg.WorkRevisionID)
	var i ReviewContextWorkHead
	err := row.Scan(
		&i.ReviewContextID,
		&i.WorkID,
		&i.WorkRevisionID,
		&i.ReviewVersionID,
	)
	return i, err
}

const getWorkReviewVersionByID = `-- name: GetWorkReviewVersionByID :one
SELECT
    version.id,
    version.work_id,
    version.work_revision_id,
    version.created_in_context_id,
    version.parent_version_id,
    version.status,
    version.reason,
    version.created_at,
    CAST(COALESCE(reviewer.username, '') AS TEXT) AS reviewer_username,
    CAST(COALESCE(reviewer.email, '') AS TEXT) AS reviewer_email
FROM work_review_versions version
JOIN review_contexts context ON context.id = version.created_in_context_id
LEFT JOIN pipeline_run_reviewers reviewer ON reviewer.pipeline_run_id = context.pipeline_run_id
WHERE version.id = ?1
`

type GetWorkReviewVersionByIDRow struct {
	ID                 int64
	WorkID             int64
	WorkRevisionID     int64
	CreatedInContextID int64
	ParentVersionID    sql.NullInt64
	Status             string
	Reason             sql.NullString
	CreatedAt          string
	ReviewerUsername   string
	ReviewerEmail      string
}

func (q *Queries) GetWorkReviewVersionByID(ctx context.Context, id int64) (GetWorkReviewVersionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkReviewVersionByID, id)
	var i GetWorkReviewVersionByIDRow
	err := row.Scan(
		&i.ID,
		&i.WorkID,
		&i.WorkRevisionID,
		&i.CreatedInContextID,
		&i.ParentVersionID,
		&i.Status,
		&i.Reason,
		&i.CreatedAt,
		&i.ReviewerUsername,
		&i.ReviewerEmail,
	)
	return i, err
}

const insertWorkReviewSubstatus = `-- name: InsertWorkReviewSubstatus :exec
INSERT INTO work_review_version_substatuses (
    review_version_id,
    sub_status
) VALUES (
    ?1,
    ?2
)
`

type InsertWorkReviewSubstatusParams struct {
	ReviewVersionID int64
	SubStatus       string
}

func (q *Queries) InsertWorkReviewSubstatus(ctx context.Context, arg InsertWorkReviewSubstatusParams) error {
	_, err := q.db.ExecContext(ctx, insertWorkReviewSubstatus, arg.ReviewVersionID, arg.SubStatus)
	return err
}

const insertWorkReviewVersion = `-- name: InsertWorkReviewVersion :execresult
INSERT INTO work_review_versions (
    work_id,
    work_revision_id,
    created_in_context_id,
    parent_version_id,
    status,
    reason,
    created_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7
)
`

type InsertWorkReviewVersionParams struct {
	WorkID             int64
	WorkRevisionID     int64
	CreatedInContextID int64
	ParentVersionID    sql.NullInt64
	Status             string
	Reason             sql.NullString
	CreatedAt          string
}

func (q *Queries) InsertWorkReviewVersion(ctx context.Context, arg InsertWorkReviewVersionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertWorkReviewVersion,
		arg.WorkID,
		arg.WorkRevisionID,
		arg.CreatedInContextID,
		arg.ParentVersionID,
		arg.Status,
		arg.Reason,
		arg.CreatedAt,
	)
}

const listWorkReviewSubstatuses = `-- name: ListWorkReviewSubstatuses :many
SELECT sub_status
FROM work_review_version_substatuses
WHERE review_version_id = ?1
ORDER BY sub_status
`

func (q *Queries) ListWorkReviewSubstatuses(ctx context.Context, reviewVersionID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listWorkReviewSubstatuses, reviewVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var sub_status string
		if err := rows.Scan(&sub_status); err != nil {
			return nil, err
		}
		items = append(items, sub_status)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkReviewVersionAncestry = `-- name: ListWorkReviewVersionAncestry :many
WITH RECURSIVE ancestry(id) AS (
    SELECT review_head.review_version_id
    FROM review_context_work_heads review_head
    WHERE review_head.review_context_id = ?4
      AND review_head.work_revision_id = ?5
      AND review_head.review_version_id IS NOT NULL
    UNION ALL
    SELECT version.parent_version_id
    FROM work_review_versions version
    JOIN ancestry ON version.id = ancestry.id
    WHERE version.parent_version_id IS NOT NULL
)
SELECT
    version.id,
    version.work_id,
    version.work_revision_id,
    version.created_in_context_id,
    version.parent_version_id,
    version.status,
    CAST(COALESCE(substr(version.reason, 1, CAST(?1 AS INTEGER)), '') AS TEXT) AS reason_preview,
    CAST(COALESCE(length(CAST(version.reason AS BLOB)), 0) AS INTEGER) AS reason_bytes,
    CAST(version.reason IS NOT NULL AS INTEGER) AS has_reason,
    version.created_at,
    CAST(COALESCE(reviewer.username, '') AS TEXT) AS reviewer_username,
    CAST(COALESCE(reviewer.email, '') AS TEXT) AS reviewer_email,
    CAST(COALESCE((SELECT json_group_array(sub_status) FROM (
        SELECT sub_status FROM work_review_version_substatuses
        WHERE review_version_id = version.id
        ORDER BY sub_status
    )), '[]') AS TEXT) AS substatuses_json
FROM ancestry
JOIN work_review_versions version ON version.id = ancestry.id
JOIN review_contexts version_context ON version_context.id = version.created_in_context_id
LEFT JOIN pipeline_run_reviewers reviewer ON reviewer.pipeline_run_id = version_context.pipeline_run_id
WHERE (CAST(?2 AS INTEGER) = 0 OR version.id < CAST(?2 AS INTEGER))
ORDER BY version.id DESC
LIMIT CAST(?3 AS INTEGER)
`

type ListWorkReviewVersionAncestryParams struct {
	PreviewBytes    int64
	Cursor          int64
	PageLimit       int64
	ReviewContextID int64
	WorkRevisionID  int64
}

type ListWorkReviewVersionAncestryRow struct {
	ID                 int64
	WorkID             int64
	WorkRevisionID     int64
	CreatedInContextID int64
	ParentVersionID    sql.NullInt64
	Status             string
	ReasonPreview      string
	ReasonBytes        int64
	HasReason          int64
	CreatedAt          string
	ReviewerUsername   string
	ReviewerEmail      string
	SubstatusesJson    string
}

func (q *Queries) ListWorkReviewVersionAncestry(ctx context.Context, arg ListWorkReviewVersionAncestryParams) ([]ListWorkReviewVersionAncestryRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkReviewVersionAncestry,
		arg.PreviewBytes,
		arg.Cursor,
		arg.PageLimit,
		arg.ReviewContextID,
		arg.WorkRevisionID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkReviewVersionAncestryRow
	for rows.Next() {
		var i ListWorkReviewVersionAncestryRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkID,
			&i.WorkRevisionID,
			&i.CreatedInContextID,
			&i.ParentVersionID,
			&i.Status,
			&i.ReasonPreview,
			&i.ReasonBytes,
			&i.HasReason,
			&i.CreatedAt,
			&i.ReviewerUsername,
			&i.ReviewerEmail,
			&i.SubstatusesJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewWorkReviewVersionInAncestry = `-- name: ReviewWorkReviewVersionInAncestry :one
WITH RECURSIVE ancestry(id) AS (
    SELECT review_head.review_version_id
    FROM review_context_work_heads review_head
    WHERE review_head.review_context_id = ?2
      AND review_head.work_revision_id = ?3
      AND review_head.review_version_id IS NOT NULL
    UNION ALL
    SELECT version.parent_version_id
    FROM work_review_versions version
    JOIN ancestry ON version.id = ancestry.id
    WHERE version.parent_version_id IS NOT NULL
)
SELECT EXISTS(SELECT 1 FROM ancestry WHERE id = ?1)
`

type ReviewWorkReviewVersionInAncestryParams struct {
	VersionID       int64
	ReviewContextID int64
	WorkRevisionID  int64
}

func (q *Queries) ReviewWorkReviewVersionInAncestry(ctx context.Context, arg ReviewWorkReviewVersionInAncestryParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, reviewWorkReviewVersionInAncestry, arg.VersionID, arg.ReviewContextID, arg.WorkRevisionID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateWorkReviewHeadCASNull = `-- name: UpdateWorkReviewHeadCASNull :execresult
UPDATE review_context_work_heads
SET review_version_id = ?1
WHERE review_context_id = ?2
  AND work_revision_id = ?3
  AND review_version_id IS NULL
`

type UpdateWorkReviewHeadCASNullParams struct {
	ReviewVersionID sql.NullInt64
	ReviewContextID int64
	WorkRevisionID  int64
}

func (q *Queries) UpdateWorkReviewHeadCASNull(ctx context.Context, arg UpdateWorkReviewHeadCASNullParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateWorkReviewHeadCASNull, arg.ReviewVersionID, arg.ReviewContextID, arg.WorkRevisionID)
}

const updateWorkReviewHeadCASValue = `-- name: UpdateWorkReviewHeadCASValue :execresult
UPDATE review_context_work_heads
SET review_version_id = ?1
WHERE review_context_id = ?2
  AND work_revision_id = ?3
  AND review_version_id = ?4
`

type UpdateWorkReviewHeadCASValueParams struct {
	ReviewVersionID   sql.NullInt64
	ReviewContextID   int64
	WorkRevisionID    int64
	ExpectedVersionID sql.NullInt64
}

func (q *Queries) UpdateWorkReviewHeadCASValue(ctx context.Context, arg UpdateWorkReviewHeadCASValueParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateWorkReviewHeadCASValue,
		arg.ReviewVersionID,
		arg.ReviewContextID,
		arg.WorkRevisionID,
		arg.ExpectedVersionID,
	)
}
