// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sql

import (
	"database/sql"
)

type ReviewContext struct {
	ID              int64
	PipelineRunID   int64
	ParentContextID sql.NullInt64
	CreatedAt       string
}

type ReviewContextWorkHead struct {
	ReviewContextID int64
	WorkID          int64
	WorkRevisionID  int64
	ReviewVersionID sql.NullInt64
}
