// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: note.sql

package sql

import (
	"context"
	"database/sql"
)

const getReviewNoteHead = `-- name: GetReviewNoteHead :one
SELECT
    logical.id,
    logical.work_id,
    work_head.work_revision_id,
    logical.created_at,
    head.note_version_id
FROM review_context_note_heads head
JOIN review_notes logical ON logical.id = head.note_id
JOIN review_context_work_heads work_head
    ON work_head.review_context_id = head.review_context_id
    AND work_head.work_id = logical.work_id
WHERE head.review_context_id = ?1
  AND head.note_id = ?2
`

type GetReviewNoteHeadParams struct {
	ReviewContextID int64
	NoteID          int64
}

type GetReviewNoteHeadRow struct {
	ID             int64
	WorkID         int64
	WorkRevisionID int64
	CreatedAt      string
	NoteVersionID  int64
}

func (q *Queries) GetReviewNoteHead(ctx context.Context, arg GetReviewNoteHeadParams) (GetReviewNoteHeadRow, error) {
	row := q.db.QueryRowContext(ctx, getReviewNoteHead, arg.ReviewContextID, arg.NoteID)
	var i GetReviewNoteHeadRow
	err := row.Scan(
		&i.ID,
		&i.WorkID,
		&i.WorkRevisionID,
		&i.CreatedAt,
		&i.NoteVersionID,
	)
	return i, err
}

const getReviewNoteHeadForUpdate = `-- name: GetReviewNoteHeadForUpdate :one
SELECT
    rc.pipeline_run_id,
    logical.work_id,
    work_head.work_revision_id,
    head.note_version_id,
    logical.created_at,
    pr.status,
    pr.visibility_state
FROM review_context_note_heads head
JOIN review_contexts rc ON rc.id = head.review_context_id
JOIN pipeline_runs pr ON pr.id = rc.pipeline_run_id
JOIN review_notes logical ON logical.id = head.note_id
JOIN review_context_work_heads work_head
    ON work_head.review_context_id = head.review_context_id
    AND work_head.work_id = logical.work_id
WHERE head.review_context_id = ?1
  AND head.note_id = ?2
`

type GetReviewNoteHeadForUpdateParams struct {
	ReviewContextID int64
	NoteID          int64
}

type GetReviewNoteHeadForUpdateRow struct {
	PipelineRunID   int64
	WorkID          int64
	WorkRevisionID  int64
	NoteVersionID   int64
	CreatedAt       string
	Status          string
	VisibilityState string
}

func (q *Queries) GetReviewNoteHeadForUpdate(ctx context.Context, arg GetReviewNoteHeadForUpdateParams) (GetReviewNoteHeadForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getReviewNoteHeadForUpdate, arg.ReviewContextID, arg.NoteID)
	var i GetReviewNoteHeadForUpdateRow
	err := row.Scan(
		&i.PipelineRunID,
		&i.WorkID,
		&i.WorkRevisionID,
		&i.NoteVersionID,
		&i.CreatedAt,
		&i.Status,
		&i.VisibilityState,
	)
	return i, err
}

const getReviewNoteVersionByID = `-- name: GetReviewNoteVersionByID :one
SELECT
    version.id,
    version.note_id,
    version.parent_version_id,
    version.created_in_context_id,
    version.state,
    version.body,
    version.created_at,
    CAST(COALESCE(reviewer.username, '') AS TEXT) AS reviewer_username,
    CAST(COALESCE(reviewer.email, '') AS TEXT) AS reviewer_email
FROM review_note_versions version
JOIN review_contexts context ON context.id = version.created_in_context_id
LEFT JOIN pipeline_run_reviewers reviewer ON reviewer.pipeline_run_id = context.pipeline_run_id
WHERE version.id = ?1
`

type GetReviewNoteVersionByIDRow struct {
	ID                 int64
	NoteID             int64
	ParentVersionID    sql.NullInt64
	CreatedInContextID int64
	State              string
	Body               sql.NullString
	CreatedAt          string
	ReviewerUsername   string
	ReviewerEmail      string
}

func (q *Queries) GetReviewNoteVersionByID(ctx context.Context, id int64) (GetReviewNoteVersionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getReviewNoteVersionByID, id)
	var i GetReviewNoteVersionByIDRow
	err := row.Scan(
		&i.ID,
		&i.NoteID,
		&i.ParentVersionID,
		&i.CreatedInContextID,
		&i.State,
		&i.Body,
		&i.CreatedAt,
		&i.ReviewerUsername,
		&i.ReviewerEmail,
	)
	return i, err
}

const insertReviewNote = `-- name: InsertReviewNote :execresult
INSERT INTO review_notes (
    work_id,
    created_at
) VALUES (
    ?1,
    ?2
)
`

type InsertReviewNoteParams struct {
	WorkID    int64
	CreatedAt string
}

func (q *Queries) InsertReviewNote(ctx context.Context, arg InsertReviewNoteParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertReviewNote, arg.WorkID, arg.CreatedAt)
}

const insertReviewNoteFirstVersion = `-- name: InsertReviewNoteFirstVersion :execresult
INSERT INTO review_note_versions (
    note_id,
    created_in_context_id,
    state,
    body,
    created_at
) VALUES (
    ?1,
    ?2,
    'active',
    ?3,
    ?4
)
`

type InsertReviewNoteFirstVersionParams struct {
	NoteID             int64
	CreatedInContextID int64
	Body               sql.NullString
	CreatedAt          string
}

func (q *Queries) InsertReviewNoteFirstVersion(ctx context.Context, arg InsertReviewNoteFirstVersionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertReviewNoteFirstVersion,
		arg.NoteID,
		arg.CreatedInContextID,
		arg.Body,
		arg.CreatedAt,
	)
}

const insertReviewNoteHead = `-- name: InsertReviewNoteHead :exec
INSERT INTO review_context_note_heads (
    review_context_id,
    note_id,
    note_version_id
) VALUES (
    ?1,
    ?2,
    ?3
)
`

type InsertReviewNoteHeadParams struct {
	ReviewContextID int64
	NoteID          int64
	NoteVersionID   int64
}

func (q *Queries) InsertReviewNoteHead(ctx context.Context, arg InsertReviewNoteHeadParams) error {
	_, err := q.db.ExecContext(ctx, insertReviewNoteHead, arg.ReviewContextID, arg.NoteID, arg.NoteVersionID)
	return err
}

const insertReviewNoteLink = `-- name: InsertReviewNoteLink :exec
INSERT INTO review_note_links (
    note_version_id,
    ordinal,
    target_type,
    raw_target,
    display_text,
    utf16_position,
    utf16_length,
    created_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8
)
`

type InsertReviewNoteLinkParams struct {
	NoteVersionID int64
	Ordinal       int64
	TargetType    string
	RawTarget     string
	DisplayText   sql.NullString
	Utf16Position int64
	Utf16Length   int64
	CreatedAt     string
}

func (q *Queries) InsertReviewNoteLink(ctx context.Context, arg InsertReviewNoteLinkParams) error {
	_, err := q.db.ExecContext(ctx, insertReviewNoteLink,
		arg.NoteVersionID,
		arg.Ordinal,
		arg.TargetType,
		arg.RawTarget,
		arg.DisplayText,
		arg.Utf16Position,
		arg.Utf16Length,
		arg.CreatedAt,
	)
	return err
}

const insertReviewNoteVersion = `-- name: InsertReviewNoteVersion :execresult
INSERT INTO review_note_versions (
    note_id,
    parent_version_id,
    created_in_context_id,
    state,
    body,
    created_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6
)
`

type InsertReviewNoteVersionParams struct {
	NoteID             int64
	ParentVersionID    sql.NullInt64
	CreatedInContextID int64
	State              string
	Body               sql.NullString
	CreatedAt          string
}

func (q *Queries) InsertReviewNoteVersion(ctx context.Context, arg InsertReviewNoteVersionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertReviewNoteVersion,
		arg.NoteID,
		arg.ParentVersionID,
		arg.CreatedInContextID,
		arg.State,
		arg.Body,
		arg.CreatedAt,
	)
}

const listReviewNoteHeads = `-- name: ListReviewNoteHeads :many
SELECT
    logical.id,
    logical.work_id,
    work_head.work_revision_id,
    logical.created_at,
    version.id AS version_id,
    version.note_id,
    version.parent_version_id,
    version.created_in_context_id,
    version.state,
    CAST(COALESCE(substr(version.body, 1, CAST(?1 AS INTEGER)), '') AS TEXT) AS body_preview,
    CAST(COALESCE(length(CAST(version.body AS BLOB)), 0) AS INTEGER) AS body_bytes,
    CAST(version.body IS NOT NULL AS INTEGER) AS has_body,
    version.created_at AS version_created_at,
    CAST(COALESCE(reviewer.username, '') AS TEXT) AS reviewer_username,
    CAST(COALESCE(reviewer.email, '') AS TEXT) AS reviewer_email,
    CAST((SELECT COUNT(*) FROM review_note_links link WHERE link.note_version_id = version.id) AS INTEGER) AS link_count
FROM review_context_note_heads head
JOIN review_context_work_heads work_head ON work_head.review_context_id = head.review_context_id
JOIN review_notes logical ON logical.id = head.note_id AND logical.work_id = work_head.work_id
JOIN review_note_versions version ON version.id = head.note_version_id
JOIN review_contexts version_context ON version_context.id = version.created_in_context_id
LEFT JOIN pipeline_run_reviewers reviewer ON reviewer.pipeline_run_id = version_context.pipeline_run_id
WHERE head.review_context_id = ?2
  AND (CAST(?3 AS INTEGER) = 0 OR head.note_id < CAST(?3 AS INTEGER))
  AND (CAST(?4 AS TEXT) = 'all'
       OR (CAST(?4 AS TEXT) = 'active' AND version.state = 'active')
       OR (CAST(?4 AS TEXT) = 'removed' AND version.state = 'deleted'))
  AND (CAST(?5 AS INTEGER) = 0
       OR work_head.work_revision_id = CAST(?6 AS INTEGER))
  AND (CAST(?7 AS INTEGER) = 0
       OR (version.body LIKE ?8 ESCAPE '\'))
ORDER BY head.note_id DESC
LIMIT CAST(?9 AS INTEGER)
`

type ListReviewNoteHeadsParams struct {
	PreviewBytes    int64
	ReviewContextID int64
	Cursor          int64
	StateFilter     string
	HasWorkRevision int64
	WorkRevisionID  int64
	HasQuery        int64
	QueryPattern    sql.NullString
	PageLimit       int64
}

type ListReviewNoteHeadsRow struct {
	ID                 int64
	WorkID             int64
	WorkRevisionID     int64
	CreatedAt          string
	VersionID          int64
	NoteID             int64
	ParentVersionID    sql.NullInt64
	CreatedInContextID int64
	State              string
	BodyPreview        string
	BodyBytes          int64
	HasBody            int64
	VersionCreatedAt   string
	ReviewerUsername   string
	ReviewerEmail      string
	LinkCount          int64
}

func (q *Queries) ListReviewNoteHeads(ctx context.Context, arg ListReviewNoteHeadsParams) ([]ListReviewNoteHeadsRow, error) {
	rows, err := q.db.QueryContext(ctx, listReviewNoteHeads,
		arg.PreviewBytes,
		arg.ReviewContextID,
		arg.Cursor,
		arg.StateFilter,
		arg.HasWorkRevision,
		arg.WorkRevisionID,
		arg.HasQuery,
		arg.QueryPattern,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewNoteHeadsRow
	for rows.Next() {
		var i ListReviewNoteHeadsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkID,
			&i.WorkRevisionID,
			&i.CreatedAt,
			&i.VersionID,
			&i.NoteID,
			&i.ParentVersionID,
			&i.CreatedInContextID,
			&i.State,
			&i.BodyPreview,
			&i.BodyBytes,
			&i.HasBody,
			&i.VersionCreatedAt,
			&i.ReviewerUsername,
			&i.ReviewerEmail,
			&i.LinkCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewNoteLinks = `-- name: ListReviewNoteLinks :many
SELECT
    ordinal,
    target_type,
    raw_target,
    display_text,
    utf16_position,
    utf16_length
FROM review_note_links
WHERE note_version_id = ?1
ORDER BY ordinal
`

type ListReviewNoteLinksRow struct {
	Ordinal       int64
	TargetType    string
	RawTarget     string
	DisplayText   sql.NullString
	Utf16Position int64
	Utf16Length   int64
}

func (q *Queries) ListReviewNoteLinks(ctx context.Context, noteVersionID int64) ([]ListReviewNoteLinksRow, error) {
	rows, err := q.db.QueryContext(ctx, listReviewNoteLinks, noteVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewNoteLinksRow
	for rows.Next() {
		var i ListReviewNoteLinksRow
		if err := rows.Scan(
			&i.Ordinal,
			&i.TargetType,
			&i.RawTarget,
			&i.DisplayText,
			&i.Utf16Position,
			&i.Utf16Length,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewNoteVersionAncestry = `-- name: ListReviewNoteVersionAncestry :many
WITH RECURSIVE ancestry(id) AS (
    SELECT note_head.note_version_id
    FROM review_context_note_heads note_head
    WHERE note_head.review_context_id = ?4
      AND note_head.note_id = ?5
    UNION ALL
    SELECT version.parent_version_id
    FROM review_note_versions version
    JOIN ancestry ON version.id = ancestry.id
    WHERE version.parent_version_id IS NOT NULL
)
SELECT
    version.id,
    version.note_id,
    version.parent_version_id,
    version.created_in_context_id,
    version.state,
    CAST(COALESCE(substr(version.body, 1, CAST(?1 AS INTEGER)), '') AS TEXT) AS body_preview,
    CAST(COALESCE(length(CAST(version.body AS BLOB)), 0) AS INTEGER) AS body_bytes,
    CAST(version.body IS NOT NULL AS INTEGER) AS has_body,
    version.created_at,
    CAST(COALESCE(reviewer.username, '') AS TEXT) AS reviewer_username,
    CAST(COALESCE(reviewer.email, '') AS TEXT) AS reviewer_email,
    CAST((SELECT COUNT(*) FROM review_note_links link WHERE link.note_version_id = version.id) AS INTEGER) AS link_count
FROM ancestry
JOIN review_note_versions version ON version.id = ancestry.id
JOIN review_contexts version_context ON version_context.id = version.created_in_context_id
LEFT JOIN pipeline_run_reviewers reviewer ON reviewer.pipeline_run_id = version_context.pipeline_run_id
WHERE (CAST(?2 AS INTEGER) = 0 OR version.id < CAST(?2 AS INTEGER))
ORDER BY version.id DESC
LIMIT CAST(?3 AS INTEGER)
`

type ListReviewNoteVersionAncestryParams struct {
	PreviewBytes    int64
	Cursor          int64
	PageLimit       int64
	ReviewContextID int64
	NoteID          int64
}

type ListReviewNoteVersionAncestryRow struct {
	ID                 int64
	NoteID             int64
	ParentVersionID    sql.NullInt64
	CreatedInContextID int64
	State              string
	BodyPreview        string
	BodyBytes          int64
	HasBody            int64
	CreatedAt          string
	ReviewerUsername   string
	ReviewerEmail      string
	LinkCount          int64
}

func (q *Queries) ListReviewNoteVersionAncestry(ctx context.Context, arg ListReviewNoteVersionAncestryParams) ([]ListReviewNoteVersionAncestryRow, error) {
	rows, err := q.db.QueryContext(ctx, listReviewNoteVersionAncestry,
		arg.PreviewBytes,
		arg.Cursor,
		arg.PageLimit,
		arg.ReviewContextID,
		arg.NoteID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewNoteVersionAncestryRow
	for rows.Next() {
		var i ListReviewNoteVersionAncestryRow
		if err := rows.Scan(
			&i.ID,
			&i.NoteID,
			&i.ParentVersionID,
			&i.CreatedInContextID,
			&i.State,
			&i.BodyPreview,
			&i.BodyBytes,
			&i.HasBody,
			&i.CreatedAt,
			&i.ReviewerUsername,
			&i.ReviewerEmail,
			&i.LinkCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewNoteVersionInAncestry = `-- name: ReviewNoteVersionInAncestry :one
WITH RECURSIVE ancestry(id) AS (
    SELECT note_head.note_version_id
    FROM review_context_note_heads note_head
    WHERE note_head.review_context_id = ?2
      AND note_head.note_id = ?3
    UNION ALL
    SELECT version.parent_version_id
    FROM review_note_versions version
    JOIN ancestry ON version.id = ancestry.id
    WHERE version.parent_version_id IS NOT NULL
)
SELECT EXISTS(SELECT 1 FROM ancestry WHERE id = ?1)
`

type ReviewNoteVersionInAncestryParams struct {
	VersionID       int64
	ReviewContextID int64
	NoteID          int64
}

func (q *Queries) ReviewNoteVersionInAncestry(ctx context.Context, arg ReviewNoteVersionInAncestryParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, reviewNoteVersionInAncestry, arg.VersionID, arg.ReviewContextID, arg.NoteID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateReviewNoteHeadCAS = `-- name: UpdateReviewNoteHeadCAS :execresult
UPDATE review_context_note_heads
SET note_version_id = ?1
WHERE review_context_id = ?2
  AND note_id = ?3
  AND note_version_id = ?4
`

type UpdateReviewNoteHeadCASParams struct {
	NoteVersionID     int64
	ReviewContextID   int64
	NoteID            int64
	ExpectedVersionID int64
}

func (q *Queries) UpdateReviewNoteHeadCAS(ctx context.Context, arg UpdateReviewNoteHeadCASParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateReviewNoteHeadCAS,
		arg.NoteVersionID,
		arg.ReviewContextID,
		arg.NoteID,
		arg.ExpectedVersionID,
	)
}
