// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: relationships.sql

package sql

import (
	"context"
	"database/sql"
)

const getReviewParentCandidateByPlan = `-- name: GetReviewParentCandidateByPlan :one
SELECT
    rc.id AS context_id,
    pr.id AS pipeline_run_id,
    s.search_id,
    sr.revision_label,
    ep.id AS execution_plan_id,
    CAST(COALESCE(pr.attempt_number, 0) AS INTEGER) AS attempt_number,
    pr.started_at,
    CAST((SELECT COUNT(*) FROM review_context_work_heads parent_head
        WHERE parent_head.review_context_id = rc.id
          AND EXISTS (
              SELECT 1 FROM work_revisions target_wr
              WHERE target_wr.pipeline_run_id = ?1
                AND target_wr.producer_stage = 'normalize'
                AND target_wr.id = (SELECT MAX(normalized_candidate.id) FROM work_revisions normalized_candidate
                    WHERE normalized_candidate.pipeline_run_id = target_wr.pipeline_run_id
                      AND normalized_candidate.work_id = target_wr.work_id
                      AND normalized_candidate.producer_stage = 'normalize')
                AND EXISTS (SELECT 1 FROM run_work_stages current_validation
                    WHERE current_validation.pipeline_run_id = target_wr.pipeline_run_id
                      AND current_validation.work_id = target_wr.work_id
                      AND current_validation.stage_name = 'validate'
                      AND current_validation.outcome = 'valid')
                AND target_wr.work_id = parent_head.work_id)) AS INTEGER) AS inherited_work_count
FROM review_contexts rc
JOIN pipeline_runs pr ON pr.id = rc.pipeline_run_id
JOIN execution_plans ep ON ep.id = pr.execution_plan_id
JOIN search_revisions sr ON sr.id = ep.search_revision_id
JOIN searches s ON s.id = sr.search_id
WHERE ep.id = ?2
  AND pr.status = 'completed'
  AND pr.visibility_state != 'trashed'
  AND (pr.started_at < ?3
       OR (pr.started_at = ?3 AND pr.id < ?1))
ORDER BY pr.started_at DESC, pr.id DESC
LIMIT 1
`

type GetReviewParentCandidateByPlanParams struct {
	TargetRunID     int64
	PlanID          int64
	TargetStartedAt string
}

type GetReviewParentCandidateByPlanRow struct {
	ContextID          int64
	PipelineRunID      int64
	SearchID           string
	RevisionLabel      string
	ExecutionPlanID    int64
	AttemptNumber      int64
	StartedAt          string
	InheritedWorkCount int64
}

func (q *Queries) GetReviewParentCandidateByPlan(ctx context.Context, arg GetReviewParentCandidateByPlanParams) (GetReviewParentCandidateByPlanRow, error) {
	row := q.db.QueryRowContext(ctx, getReviewParentCandidateByPlan, arg.TargetRunID, arg.PlanID, arg.TargetStartedAt)
	var i GetReviewParentCandidateByPlanRow
	err := row.Scan(
		&i.ContextID,
		&i.PipelineRunID,
		&i.SearchID,
		&i.RevisionLabel,
		&i.ExecutionPlanID,
		&i.AttemptNumber,
		&i.StartedAt,
		&i.InheritedWorkCount,
	)
	return i, err
}

const getReviewParentCandidateBySearch = `-- name: GetReviewParentCandidateBySearch :one
SELECT
    rc.id AS context_id,
    pr.id AS pipeline_run_id,
    s.search_id,
    sr.revision_label,
    ep.id AS execution_plan_id,
    CAST(COALESCE(pr.attempt_number, 0) AS INTEGER) AS attempt_number,
    pr.started_at,
    CAST((SELECT COUNT(*) FROM review_context_work_heads parent_head
        WHERE parent_head.review_context_id = rc.id
          AND EXISTS (
              SELECT 1 FROM work_revisions target_wr
              WHERE target_wr.pipeline_run_id = ?1
                AND target_wr.producer_stage = 'normalize'
                AND target_wr.id = (SELECT MAX(normalized_candidate.id) FROM work_revisions normalized_candidate
                    WHERE normalized_candidate.pipeline_run_id = target_wr.pipeline_run_id
                      AND normalized_candidate.work_id = target_wr.work_id
                      AND normalized_candidate.producer_stage = 'normalize')
                AND EXISTS (SELECT 1 FROM run_work_stages current_validation
                    WHERE current_validation.pipeline_run_id = target_wr.pipeline_run_id
                      AND current_validation.work_id = target_wr.work_id
                      AND current_validation.stage_name = 'validate'
                      AND current_validation.outcome = 'valid')
                AND target_wr.work_id = parent_head.work_id)) AS INTEGER) AS inherited_work_count
FROM review_contexts rc
JOIN pipeline_runs pr ON pr.id = rc.pipeline_run_id
JOIN execution_plans ep ON ep.id = pr.execution_plan_id
JOIN search_revisions sr ON sr.id = ep.search_revision_id
JOIN searches s ON s.id = sr.search_id
WHERE s.id = ?2
  AND pr.status = 'completed'
  AND pr.visibility_state != 'trashed'
  AND (pr.started_at < ?3
       OR (pr.started_at = ?3 AND pr.id < ?1))
ORDER BY pr.started_at DESC, pr.id DESC
LIMIT 1
`

type GetReviewParentCandidateBySearchParams struct {
	TargetRunID     int64
	SearchDbID      int64
	TargetStartedAt string
}

type GetReviewParentCandidateBySearchRow struct {
	ContextID          int64
	PipelineRunID      int64
	SearchID           string
	RevisionLabel      string
	ExecutionPlanID    int64
	AttemptNumber      int64
	StartedAt          string
	InheritedWorkCount int64
}

func (q *Queries) GetReviewParentCandidateBySearch(ctx context.Context, arg GetReviewParentCandidateBySearchParams) (GetReviewParentCandidateBySearchRow, error) {
	row := q.db.QueryRowContext(ctx, getReviewParentCandidateBySearch, arg.TargetRunID, arg.SearchDbID, arg.TargetStartedAt)
	var i GetReviewParentCandidateBySearchRow
	err := row.Scan(
		&i.ContextID,
		&i.PipelineRunID,
		&i.SearchID,
		&i.RevisionLabel,
		&i.ExecutionPlanID,
		&i.AttemptNumber,
		&i.StartedAt,
		&i.InheritedWorkCount,
	)
	return i, err
}

const listReviewBacklinks = `-- name: ListReviewBacklinks :many
SELECT
    logical.id,
    logical.work_id,
    work_head.work_revision_id,
    logical.created_at,
    version.id AS version_id,
    version.note_id,
    version.parent_version_id,
    version.created_in_context_id,
    version.state,
    CAST(COALESCE(substr(version.body, 1, CAST(?1 AS INTEGER)), '') AS TEXT) AS body_preview,
    CAST(COALESCE(length(CAST(version.body AS BLOB)), 0) AS INTEGER) AS body_bytes,
    CAST(version.body IS NOT NULL AS INTEGER) AS has_body,
    version.created_at AS version_created_at,
    CAST(COALESCE(reviewer.username, '') AS TEXT) AS reviewer_username,
    CAST(COALESCE(reviewer.email, '') AS TEXT) AS reviewer_email,
    CAST((SELECT COUNT(*) FROM review_note_links all_links WHERE all_links.note_version_id = version.id) AS INTEGER) AS link_count
FROM review_context_note_heads head
JOIN review_note_versions version ON version.id = head.note_version_id AND version.state = 'active'
JOIN review_notes logical ON logical.id = head.note_id
JOIN review_context_work_heads work_head
    ON work_head.review_context_id = head.review_context_id
    AND work_head.work_id = logical.work_id
JOIN review_contexts version_context ON version_context.id = version.created_in_context_id
LEFT JOIN pipeline_run_reviewers reviewer ON reviewer.pipeline_run_id = version_context.pipeline_run_id
JOIN review_note_links link ON link.note_version_id = head.note_version_id
WHERE head.review_context_id = ?2
  AND link.target_type = ?3
  AND link.raw_target = ?4
  AND (CAST(?5 AS INTEGER) = 0
       OR logical.work_id = CAST(?5 AS INTEGER))
  AND (CAST(?6 AS INTEGER) = 0 OR head.note_id < CAST(?6 AS INTEGER))
GROUP BY logical.id, version.id
ORDER BY head.note_id DESC
LIMIT CAST(?7 AS INTEGER)
`

type ListReviewBacklinksParams struct {
	PreviewBytes    int64
	ReviewContextID int64
	TargetType      string
	TargetID        string
	SourceWorkID    int64
	Cursor          int64
	PageLimit       int64
}

type ListReviewBacklinksRow struct {
	ID                 int64
	WorkID             int64
	WorkRevisionID     int64
	CreatedAt          string
	VersionID          int64
	NoteID             int64
	ParentVersionID    sql.NullInt64
	CreatedInContextID int64
	State              string
	BodyPreview        string
	BodyBytes          int64
	HasBody            int64
	VersionCreatedAt   string
	ReviewerUsername   string
	ReviewerEmail      string
	LinkCount          int64
}

func (q *Queries) ListReviewBacklinks(ctx context.Context, arg ListReviewBacklinksParams) ([]ListReviewBacklinksRow, error) {
	rows, err := q.db.QueryContext(ctx, listReviewBacklinks,
		arg.PreviewBytes,
		arg.ReviewContextID,
		arg.TargetType,
		arg.TargetID,
		arg.SourceWorkID,
		arg.Cursor,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewBacklinksRow
	for rows.Next() {
		var i ListReviewBacklinksRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkID,
			&i.WorkRevisionID,
			&i.CreatedAt,
			&i.VersionID,
			&i.NoteID,
			&i.ParentVersionID,
			&i.CreatedInContextID,
			&i.State,
			&i.BodyPreview,
			&i.BodyBytes,
			&i.HasBody,
			&i.VersionCreatedAt,
			&i.ReviewerUsername,
			&i.ReviewerEmail,
			&i.LinkCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewParentCandidates = `-- name: ListReviewParentCandidates :many
SELECT
    rc.id AS context_id,
    pr.id AS pipeline_run_id,
    s.search_id,
    sr.revision_label,
    ep.id AS execution_plan_id,
    CAST(COALESCE(pr.attempt_number, 0) AS INTEGER) AS attempt_number,
    pr.started_at,
    CAST((SELECT COUNT(*) FROM review_context_work_heads parent_head
        WHERE parent_head.review_context_id = rc.id
          AND EXISTS (
              SELECT 1 FROM work_revisions target_wr
              WHERE target_wr.pipeline_run_id = ?1
                AND target_wr.producer_stage = 'normalize'
                AND target_wr.id = (SELECT MAX(normalized_candidate.id) FROM work_revisions normalized_candidate
                    WHERE normalized_candidate.pipeline_run_id = target_wr.pipeline_run_id
                      AND normalized_candidate.work_id = target_wr.work_id
                      AND normalized_candidate.producer_stage = 'normalize')
                AND EXISTS (SELECT 1 FROM run_work_stages current_validation
                    WHERE current_validation.pipeline_run_id = target_wr.pipeline_run_id
                      AND current_validation.work_id = target_wr.work_id
                      AND current_validation.stage_name = 'validate'
                      AND current_validation.outcome = 'valid')
                AND target_wr.work_id = parent_head.work_id)) AS INTEGER) AS inherited_work_count
FROM review_contexts rc
JOIN pipeline_runs pr ON pr.id = rc.pipeline_run_id
JOIN execution_plans ep ON ep.id = pr.execution_plan_id
JOIN search_revisions sr ON sr.id = ep.search_revision_id
JOIN searches s ON s.id = sr.search_id
WHERE pr.status = 'completed'
  AND pr.visibility_state != 'trashed'
  AND (pr.started_at < ?2
       OR (pr.started_at = ?2 AND pr.id < ?1))
  AND (CAST(?3 AS INTEGER) = 1 OR s.id = CAST(?4 AS INTEGER))
  AND (CAST(?5 AS INTEGER) = 0
       OR pr.started_at < CAST(?6 AS TEXT)
       OR (pr.started_at = CAST(?6 AS TEXT) AND pr.id < CAST(?7 AS INTEGER)))
  AND (CAST(?8 AS INTEGER) = 0
       OR s.search_id LIKE CAST(?9 AS TEXT)
       OR sr.revision_label LIKE CAST(?9 AS TEXT))
ORDER BY pr.started_at DESC, pr.id DESC
LIMIT CAST(?10 AS INTEGER)
`

type ListReviewParentCandidatesParams struct {
	TargetRunID     int64
	TargetStartedAt string
	ScopeAll        int64
	SearchDbID      int64
	HasCursor       int64
	CursorStartedAt string
	CursorRunID     int64
	HasQuery        int64
	QueryPattern    string
	PageLimit       int64
}

type ListReviewParentCandidatesRow struct {
	ContextID          int64
	PipelineRunID      int64
	SearchID           string
	RevisionLabel      string
	ExecutionPlanID    int64
	AttemptNumber      int64
	StartedAt          string
	InheritedWorkCount int64
}

func (q *Queries) ListReviewParentCandidates(ctx context.Context, arg ListReviewParentCandidatesParams) ([]ListReviewParentCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listReviewParentCandidates,
		arg.TargetRunID,
		arg.TargetStartedAt,
		arg.ScopeAll,
		arg.SearchDbID,
		arg.HasCursor,
		arg.CursorStartedAt,
		arg.CursorRunID,
		arg.HasQuery,
		arg.QueryPattern,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewParentCandidatesRow
	for rows.Next() {
		var i ListReviewParentCandidatesRow
		if err := rows.Scan(
			&i.ContextID,
			&i.PipelineRunID,
			&i.SearchID,
			&i.RevisionLabel,
			&i.ExecutionPlanID,
			&i.AttemptNumber,
			&i.StartedAt,
			&i.InheritedWorkCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveReviewLinkAnchor = `-- name: ResolveReviewLinkAnchor :one
SELECT
    work_head.work_revision_id,
    version.page
FROM review_context_anchor_heads anchor_head
JOIN review_anchors logical ON logical.id = anchor_head.anchor_id
JOIN review_anchor_versions version
    ON version.id = anchor_head.anchor_version_id
    AND version.state = 'active'
JOIN review_context_work_heads work_head
    ON work_head.review_context_id = anchor_head.review_context_id
    AND work_head.work_id = logical.work_id
WHERE anchor_head.review_context_id = ?1
  AND anchor_head.anchor_id = ?2
`

type ResolveReviewLinkAnchorParams struct {
	ReviewContextID int64
	AnchorID        string
}

type ResolveReviewLinkAnchorRow struct {
	WorkRevisionID int64
	Page           sql.NullInt64
}

func (q *Queries) ResolveReviewLinkAnchor(ctx context.Context, arg ResolveReviewLinkAnchorParams) (ResolveReviewLinkAnchorRow, error) {
	row := q.db.QueryRowContext(ctx, resolveReviewLinkAnchor, arg.ReviewContextID, arg.AnchorID)
	var i ResolveReviewLinkAnchorRow
	err := row.Scan(&i.WorkRevisionID, &i.Page)
	return i, err
}

const resolveReviewLinkArticle = `-- name: ResolveReviewLinkArticle :one
SELECT head.work_revision_id
FROM review_context_work_heads head
JOIN works work ON work.id = head.work_id
WHERE head.review_context_id = ?1
  AND work.doi = ?2
`

type ResolveReviewLinkArticleParams struct {
	ReviewContextID int64
	Doi             sql.NullString
}

func (q *Queries) ResolveReviewLinkArticle(ctx context.Context, arg ResolveReviewLinkArticleParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, resolveReviewLinkArticle, arg.ReviewContextID, arg.Doi)
	var work_revision_id int64
	err := row.Scan(&work_revision_id)
	return work_revision_id, err
}

const resolveReviewLinkNote = `-- name: ResolveReviewLinkNote :one
SELECT work_head.work_revision_id
FROM review_context_note_heads note_head
JOIN review_notes logical ON logical.id = note_head.note_id
JOIN review_context_work_heads work_head
    ON work_head.review_context_id = note_head.review_context_id
    AND work_head.work_id = logical.work_id
WHERE note_head.review_context_id = ?1
  AND note_head.note_id = ?2
`

type ResolveReviewLinkNoteParams struct {
	ReviewContextID int64
	NoteID          int64
}

func (q *Queries) ResolveReviewLinkNote(ctx context.Context, arg ResolveReviewLinkNoteParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, resolveReviewLinkNote, arg.ReviewContextID, arg.NoteID)
	var work_revision_id int64
	err := row.Scan(&work_revision_id)
	return work_revision_id, err
}

const resolveReviewLinkPDFPage = `-- name: ResolveReviewLinkPDFPage :one
SELECT work_head.work_revision_id
FROM review_notes logical
JOIN review_context_work_heads work_head
    ON work_head.review_context_id = ?1
    AND work_head.work_id = logical.work_id
WHERE logical.id = ?2
`

type ResolveReviewLinkPDFPageParams struct {
	ReviewContextID int64
	NoteID          int64
}

func (q *Queries) ResolveReviewLinkPDFPage(ctx context.Context, arg ResolveReviewLinkPDFPageParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, resolveReviewLinkPDFPage, arg.ReviewContextID, arg.NoteID)
	var work_revision_id int64
	err := row.Scan(&work_revision_id)
	return work_revision_id, err
}
