// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sql

import (
	"context"
	"database/sql"
)

const getAuditEventOccurredAt = `-- name: GetAuditEventOccurredAt :one
SELECT occurred_at
FROM audit_events
WHERE id = ?1
`

func (q *Queries) GetAuditEventOccurredAt(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getAuditEventOccurredAt, id)
	var occurred_at string
	err := row.Scan(&occurred_at)
	return occurred_at, err
}

const insertAuditEvent = `-- name: InsertAuditEvent :execresult
INSERT INTO audit_events (
    occurred_at,
    actor,
    pipeline_run_id,
    entity_type,
    entity_id,
    action,
    before_json,
    after_json,
    metadata_json,
    correlation_id
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10
)
`

type InsertAuditEventParams struct {
	OccurredAt    string
	Actor         string
	PipelineRunID sql.NullInt64
	EntityType    string
	EntityID      string
	Action        string
	BeforeJson    sql.NullString
	AfterJson     sql.NullString
	MetadataJson  sql.NullString
	CorrelationID sql.NullString
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertAuditEvent,
		arg.OccurredAt,
		arg.Actor,
		arg.PipelineRunID,
		arg.EntityType,
		arg.EntityID,
		arg.Action,
		arg.BeforeJson,
		arg.AfterJson,
		arg.MetadataJson,
		arg.CorrelationID,
	)
}

const listAuditEventsByEntity = `-- name: ListAuditEventsByEntity :many
SELECT
    id,
    occurred_at,
    actor,
    pipeline_run_id,
    entity_type,
    entity_id,
    action,
    before_json,
    after_json,
    metadata_json,
    correlation_id
FROM audit_events
WHERE entity_type = ?1
  AND entity_id = ?2
ORDER BY id
`

type ListAuditEventsByEntityParams struct {
	EntityType string
	EntityID   string
}

func (q *Queries) ListAuditEventsByEntity(ctx context.Context, arg ListAuditEventsByEntityParams) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEventsByEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.Actor,
			&i.PipelineRunID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.BeforeJson,
			&i.AfterJson,
			&i.MetadataJson,
			&i.CorrelationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEventsByRun = `-- name: ListAuditEventsByRun :many
SELECT
    id,
    occurred_at,
    actor,
    pipeline_run_id,
    entity_type,
    entity_id,
    action,
    before_json,
    after_json,
    metadata_json,
    correlation_id
FROM audit_events
WHERE pipeline_run_id = ?1
ORDER BY id
`

func (q *Queries) ListAuditEventsByRun(ctx context.Context, pipelineRunID sql.NullInt64) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEventsByRun, pipelineRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.Actor,
			&i.PipelineRunID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.BeforeJson,
			&i.AfterJson,
			&i.MetadataJson,
			&i.CorrelationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
