// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: evidence.sql

package sql

import (
	"context"
	"database/sql"
)

const countAuthorDetailEvents = `-- name: CountAuthorDetailEvents :one
SELECT COUNT(*)
FROM audit_events
WHERE entity_type='author_occurrence'
  AND entity_id = ?1
  AND pipeline_run_id = ?2
`

type CountAuthorDetailEventsParams struct {
	EntityID      string
	PipelineRunID sql.NullInt64
}

func (q *Queries) CountAuthorDetailEvents(ctx context.Context, arg CountAuthorDetailEventsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuthorDetailEvents, arg.EntityID, arg.PipelineRunID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAuditEventRecordedData = `-- name: GetAuditEventRecordedData :one
SELECT
    event.id,
    event.before_json,
    event.after_json,
    event.metadata_json
FROM audit_events event
WHERE event.id = ?1
  AND (
    event.pipeline_run_id = ?2
    OR (
        event.pipeline_run_id IS NULL
        AND event.action LIKE 'pdf_%'
        AND event.entity_type = 'work'
        AND EXISTS (
            SELECT 1 FROM work_revisions scoped_revision
            WHERE scoped_revision.pipeline_run_id = ?2
              AND CAST(scoped_revision.work_id AS TEXT) = event.entity_id
        )
    )
  )
`

type GetAuditEventRecordedDataParams struct {
	ID            int64
	PipelineRunID sql.NullInt64
}

type GetAuditEventRecordedDataRow struct {
	ID           int64
	BeforeJson   sql.NullString
	AfterJson    sql.NullString
	MetadataJson sql.NullString
}

func (q *Queries) GetAuditEventRecordedData(ctx context.Context, arg GetAuditEventRecordedDataParams) (GetAuditEventRecordedDataRow, error) {
	row := q.db.QueryRowContext(ctx, getAuditEventRecordedData, arg.ID, arg.PipelineRunID)
	var i GetAuditEventRecordedDataRow
	err := row.Scan(
		&i.ID,
		&i.BeforeJson,
		&i.AfterJson,
		&i.MetadataJson,
	)
	return i, err
}

const listAuthorDetailEvents = `-- name: ListAuthorDetailEvents :many
SELECT
    id,
    occurred_at,
    actor,
    pipeline_run_id,
    entity_type,
    entity_id,
    action,
    before_json,
    after_json,
    metadata_json,
    correlation_id
FROM audit_events
WHERE entity_type='author_occurrence'
  AND entity_id = ?1
  AND pipeline_run_id = ?2
  AND (CAST(?3 AS INTEGER)=0 OR id < ?3)
ORDER BY id DESC
LIMIT ?4
`

type ListAuthorDetailEventsParams struct {
	EntityID      string
	PipelineRunID sql.NullInt64
	CursorID      int64
	Limit         int64
}

func (q *Queries) ListAuthorDetailEvents(ctx context.Context, arg ListAuthorDetailEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAuthorDetailEvents,
		arg.EntityID,
		arg.PipelineRunID,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.Actor,
			&i.PipelineRunID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.BeforeJson,
			&i.AfterJson,
			&i.MetadataJson,
			&i.CorrelationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnrichmentSummary = `-- name: ListEnrichmentSummary :many
SELECT DISTINCT
    CASE WHEN json_valid(event.metadata_json) THEN COALESCE(json_extract(event.metadata_json, '$.provider'), '') ELSE '' END AS provider,
    CASE WHEN json_valid(event.metadata_json) THEN COALESCE(json_extract(event.metadata_json, '$.field'), '') ELSE '' END AS field
FROM audit_events event
WHERE event.entity_type = 'work_revision'
  AND event.action = 'field_enriched'
  AND event.entity_id IN (
      SELECT CAST(revision.id AS TEXT) FROM work_revisions revision
      WHERE revision.work_id = ?1
        AND revision.pipeline_run_id = ?2
  )
ORDER BY provider, field
LIMIT 101
`

type ListEnrichmentSummaryParams struct {
	WorkID        int64
	PipelineRunID int64
}

type ListEnrichmentSummaryRow struct {
	Provider string
	Field    string
}

func (q *Queries) ListEnrichmentSummary(ctx context.Context, arg ListEnrichmentSummaryParams) ([]ListEnrichmentSummaryRow, error) {
	rows, err := q.db.QueryContext(ctx, listEnrichmentSummary, arg.WorkID, arg.PipelineRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnrichmentSummaryRow
	for rows.Next() {
		var i ListEnrichmentSummaryRow
		if err := rows.Scan(&i.Provider, &i.Field); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
