// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sql

import (
	"database/sql"
)

type AuditEvent struct {
	ID            int64
	OccurredAt    string
	Actor         string
	PipelineRunID sql.NullInt64
	EntityType    string
	EntityID      string
	Action        string
	BeforeJson    sql.NullString
	AfterJson     sql.NullString
	MetadataJson  sql.NullString
	CorrelationID sql.NullString
}
